import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getTreasuryTransactionReconciliation } from "@/lib/company-funds-transaction-reconciliation";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2, AlertTriangle, SearchCheck, Copy, ReceiptText, Landmark, ShieldAlert } from "lucide-react";
import { acceptTreasurySuggestedMatchAction, ignoreTreasuryBankTransactionAction } from "@/services/company-funds-transaction-reconciliation";

export const dynamic="force-dynamic";

export default async function TreasuryReconciliationPage(){
  const user=await requireUser();if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
  const data=await getTreasuryTransactionReconciliation();
  return <div className="space-y-5">
    <div><p className="text-xs uppercase tracking-[.18em] text-muted2">Super Admin · Contrôle financier</p><h1 className="mt-1 text-3xl font-semibold">Réconciliation transaction par transaction</h1><p className="mt-1 max-w-4xl text-sm text-muted2">JUN compare les opérations Finance aux transactions bancaires importées afin de détecter les paiements absents, sorties inexpliquées, doublons, frais imprévus et écarts de montant.</p></div>

    <div className="grid gap-3 md:grid-cols-4 xl:grid-cols-8">
      <Metric label="Finance" value={data.summary.financeTotal}/><Metric label="Banque" value={data.summary.bankTotal}/><Metric label="Rapprochées" value={data.summary.matched}/><Metric label="Suggestions" value={data.summary.suggested}/><Metric label="Banque inexpliquée" value={data.summary.unexplainedBank}/><Metric label="Absentes banque" value={data.summary.missingInBank}/><Metric label="Doublons" value={data.summary.duplicates}/><Metric label="Frais suspects" value={data.summary.unexpectedFees}/>
    </div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><SearchCheck className="h-5 w-5"/>Suggestions automatiques</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-muted2">Une suggestion exige même devise, sens cohérent, montant proche et date à ±7 jours. La référence augmente le score.</p>{data.suggestions.length?data.suggestions.slice(0,100).map(s=><div key={`${s.bank.id}:${s.finance.id}`} className="grid gap-3 rounded-xl border border-line p-4 lg:grid-cols-[1fr_1fr_auto] lg:items-center"><div><div className="text-[10px] uppercase tracking-wide text-muted2">Finance JUN</div><div className="font-semibold">{s.finance.reference}</div><div className="text-xs text-muted2">{s.finance.category} · {formatMoney(s.finance.amount,s.finance.currency)} · {formatDateTime(s.finance.occurredAt)}</div></div><div><div className="text-[10px] uppercase tracking-wide text-muted2">Transaction bancaire</div><div className="font-semibold">{s.bank.description||s.bank.bankReference}</div><div className="text-xs text-muted2">{formatMoney(s.bank.amount,s.bank.currency)} · {formatDateTime(s.bank.date)} · score {s.score}%</div></div><form action={acceptTreasurySuggestedMatchAction.bind(null,s.finance.id,s.bank.id)}><button className="rounded-lg bg-ink px-3 py-2 text-xs font-semibold text-white">Confirmer</button></form></div>):<Empty text="Aucune suggestion automatique actuellement."/>}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5"/>Transactions bancaires sans explication</CardTitle></CardHeader><CardContent className="space-y-2">{data.unexplainedBank.length?data.unexplainedBank.slice(0,100).map(b=><div key={b.id} className="rounded-xl border border-line p-3"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{b.description||"Transaction bancaire"}</div><div className="text-xs text-muted2">{b.bankReference||"Sans référence"} · {formatDateTime(b.date)}</div></div><div className={`font-semibold ${b.amount<0?"text-red-700":"text-emerald-700"}`}>{formatMoney(b.amount,b.currency)}</div></div><form action={ignoreTreasuryBankTransactionAction.bind(null,b.id)} className="mt-2 flex gap-2"><input name="reason" placeholder="Motif si hors opérations JUN" className="min-w-0 flex-1 rounded border border-line px-2 py-1 text-xs"/><button className="rounded border border-line px-2 py-1 text-xs">Ignorer</button></form></div>):<Empty text="Aucune transaction bancaire inexpliquée."/>}</CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText className="h-5 w-5"/>Opérations Finance absentes du relevé</CardTitle></CardHeader><CardContent className="space-y-2">{data.missingInBank.length?data.missingInBank.slice(0,100).map(f=><div key={f.id} className="flex items-start justify-between gap-3 rounded-xl border border-line p-3"><div><div className="font-medium">{f.reference}</div><div className="text-xs text-muted2">{f.category} · {formatDateTime(f.occurredAt)}{f.treasuryAccountId?" · compte affecté":" · compte non affecté"}</div></div><div className={`font-semibold ${f.direction==="OUT"?"text-red-700":"text-emerald-700"}`}>{f.direction==="OUT"?"−":"+"}{formatMoney(f.amount,f.currency)}</div></div>):<Empty text="Toutes les opérations Finance ont une correspondance ou une suggestion."/>}</CardContent></Card>
    </div>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Copy className="h-5 w-5"/>Doublons bancaires potentiels</CardTitle></CardHeader><CardContent className="space-y-3">{data.possibleDuplicates.length?data.possibleDuplicates.slice(0,50).map((group,index)=><div key={index} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><div className="text-xs font-semibold text-amber-800">{group.length} transactions · {formatMoney(group[0].amount,group[0].currency)} · {group[0].date.slice(0,10)}</div>{group.map(b=><div key={b.id} className="mt-1 text-xs text-amber-900">{b.description||"—"} · {b.bankReference||"sans référence"}</div>)}</div>):<Empty text="Aucun doublon potentiel détecté."/>}</CardContent></Card>

      <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5"/>Frais bancaires imprévus</CardTitle></CardHeader><CardContent className="space-y-2">{data.unexpectedFees.length?data.unexpectedFees.slice(0,100).map(b=><div key={b.id} className="flex items-center justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-3"><div><div className="font-medium text-red-900">{b.description||"Frais bancaire"}</div><div className="text-xs text-red-700">{b.bankReference||"—"} · {formatDateTime(b.date)}</div></div><div className="font-semibold text-red-700">{formatMoney(b.amount,b.currency)}</div></div>):<Empty text="Aucun frais bancaire imprévu détecté."/>}</CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5"/>Couverture des comptes</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Compte</th><th className="p-2">Devise</th><th className="p-2 text-right">Relevés liés</th><th className="p-2 text-right">Transactions</th><th className="p-2 text-right">Rapprochées</th><th className="p-2 text-right">Non rapprochées</th></tr></thead><tbody>{data.byAccount.map(r=><tr key={r.account.id} className="border-b border-line/70"><td className="p-2 font-medium">{r.account.name}<div className="text-[10px] text-muted2">{r.account.institution}</div></td><td className="p-2">{r.account.currency}</td><td className="p-2 text-right">{r.importCount}</td><td className="p-2 text-right">{r.statementTransactions}</td><td className="p-2 text-right text-emerald-700">{r.matched}</td><td className="p-2 text-right text-amber-700">{r.unmatched}</td></tr>)}</tbody></table></div></CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5"/>Rapprochements confirmés</CardTitle></CardHeader><CardContent>{data.matches.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Finance</th><th className="p-2">Banque</th><th className="p-2">Méthode</th><th className="p-2 text-right">Écart</th><th className="p-2">Date</th></tr></thead><tbody>{data.matches.slice(0,200).map(m=>{const f=data.financeEntries.find(e=>e.id===m.financeEntryId);const b=data.bankTransactions.find(e=>e.id===m.bankTransactionId);return <tr key={m.id} className="border-b border-line/70"><td className="p-2">{f?.reference||m.financeEntryId}</td><td className="p-2">{b?.description||b?.bankReference||m.bankTransactionId}</td><td className="p-2">{m.method}</td><td className="p-2 text-right">{f?formatMoney(m.amountDifference,f.currency):m.amountDifference}</td><td className="p-2 text-xs">{formatDateTime(m.matchedAt)}</td></tr>})}</tbody></table></div>:<Empty text="Aucun rapprochement confirmé pour le moment."/>}</CardContent></Card>
  </div>
}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-line bg-white p-3"><div className="text-[10px] uppercase tracking-wide text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl bg-surface p-4 text-sm text-muted2">{text}</div>}
