import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getTreasuryStore } from "@/lib/company-funds";
import { getFinancialReserveDashboard } from "@/lib/company-funds-reserves";
import { parseCompanyFundsFilters } from "@/lib/company-funds-filters";
import { formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Landmark, PiggyBank, ShieldCheck } from "lucide-react";
import { createFinancialReserveAction, setFinancialReserveActiveAction, updateFinancialReserveAmountAction } from "@/services/company-funds-reserves";

export const dynamic="force-dynamic";
const kindLabels:Record<string,string>={EMERGENCY:"Fonds d’urgence",TAX:"Réserve fiscale",CLIENT_REFUNDS:"Remboursements clients",OPERATING:"Réserve opérationnelle",INVESTMENT:"Capital investissement",COUNTRY_MINIMUM:"Minimum de trésorerie pays",OTHER:"Autre réserve"};
type SearchParams={country?:string;currency?:string;period?:string};

export default async function FinancialReservesPage({searchParams}:{searchParams?:SearchParams}){
  const user=await requireUser();if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
  const filters=parseCompanyFundsFilters(searchParams);
  const [dashboard,treasury]=await Promise.all([getFinancialReserveDashboard({country:filters.country,currency:filters.currency}),getTreasuryStore()]);
  const visibleAccounts=treasury.accounts.filter(a=>a.active&&(!filters.country||a.country===filters.country)&&(!filters.currency||a.currency===filters.currency));
  const scope=[filters.country,filters.currency].filter(Boolean).join(" · ");
  return <div className="space-y-5">
    <div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Super Admin · Protection de trésorerie</p><h1 className="mt-1 text-3xl font-semibold">Réserves financières</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Sépare l’argent réellement disponible de l’argent protégé pour les taxes, remboursements clients, urgences, opérations, investissements et minimums de trésorerie par pays.</p>{scope?<p className="mt-2 text-xs font-semibold text-electric">Périmètre courant : {scope}</p>:null}{filters.periodDays?<p className="mt-1 text-[11px] text-muted2">Le filtre de période ne modifie pas une position de réserve courante ; Pays et Devise sont appliqués aux montants affichés.</p>:null}</div>

    <div className="grid gap-3 md:grid-cols-4"><Metric icon={PiggyBank} label="Réserves actives" value={String(dashboard.totalActive)} hint="Enveloppes financières protégées dans le périmètre"/><Metric icon={Landmark} label="Devises suivies" value={String(dashboard.byCurrency.length)} hint="Sans conversion artificielle entre devises"/><Metric icon={ShieldCheck} label="Objectifs complets" value={String(dashboard.byCurrency.filter(r=>r.shortfall===0&&!r.overReserved).length)} hint="Réserves atteignant leur objectif"/><Metric icon={AlertTriangle} label="Alertes" value={String(dashboard.alerts.length)} hint="Manque ou sur-réservation à corriger"/></div>

    {dashboard.alerts.length?<Card><CardHeader><CardTitle>Alertes de réserve</CardTitle></CardHeader><CardContent className="space-y-2">{dashboard.alerts.map((a,i)=><div key={i} className={`rounded-lg border p-3 text-sm ${a.type==="CRITICAL"?"border-red-200 bg-red-50 text-red-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>{a.message}</div>)}</CardContent></Card>:null}

    <Card><CardHeader><CardTitle>Cash disponible vs argent réservé</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{dashboard.byCurrency.map(r=><div key={r.currency} className="rounded-xl border border-line p-4"><div className="text-xs font-semibold text-muted2">{r.currency}</div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><div>Cash total<div className="font-semibold text-ink">{formatMoney(r.cash,r.currency)}</div></div><div>Réservé<div className="font-semibold text-amber-700">{formatMoney(r.reserved,r.currency)}</div></div><div>Disponible<div className={`font-semibold ${r.available<0?"text-red-700":"text-emerald-700"}`}>{formatMoney(r.available,r.currency)}</div></div><div>Objectif<div className="font-semibold">{formatMoney(r.target,r.currency)}</div></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface"><div className="h-full bg-ink" style={{width:`${Math.min(100,Math.max(0,r.coveragePercent))}%`}}/></div><div className="mt-1 text-[10px] text-muted2">Couverture {r.coveragePercent}%{r.shortfall>0?` · manque ${formatMoney(r.shortfall,r.currency)}`:""}</div></div>)}</div>{!dashboard.byCurrency.length?<p className="text-sm text-muted2">Aucune position de réserve ne correspond aux filtres actuels.</p>:null}</CardContent></Card>

    <Card><CardHeader><CardTitle>Créer une réserve</CardTitle></CardHeader><CardContent><form action={createFinancialReserveAction} className="grid gap-3 md:grid-cols-4"><Input name="name" label="Nom de la réserve" required/><label className="text-xs">Type<select name="kind" className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm">{Object.entries(kindLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><Input name="country" label="Pays (optionnel)" defaultValue={filters.country||undefined}/><Input name="currency" label="Devise" defaultValue={filters.currency||"USD"} required/><label className="text-xs">Compte affecté<select name="accountId" className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"><option value="">Tous les comptes de cette devise</option>{visibleAccounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.country} · {a.currency}</option>)}</select></label><Input name="targetAmount" label="Objectif" type="number" required/><Input name="reservedAmount" label="Déjà réservé" type="number" defaultValue="0" required/><Input name="note" label="Note / politique"/><button className="rounded-lg bg-ink px-3 py-2 text-sm font-medium text-white">Créer la réserve</button></form></CardContent></Card>

    <Card><CardHeader><CardTitle>Réserves et politiques</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Réserve</th><th className="p-2">Pays / Compte</th><th className="p-2 text-right">Objectif</th><th className="p-2 text-right">Réservé</th><th className="p-2 text-right">Manque</th><th className="p-2">État</th><th className="p-2">Action</th></tr></thead><tbody>{dashboard.reserves.map(r=>{const account=treasury.accounts.find(a=>a.id===r.accountId);const shortage=Math.max(0,r.targetAmount-r.reservedAmount);return <tr key={r.id} className="border-b border-line/70"><td className="p-2 font-medium">{r.name}<div className="text-[10px] text-muted2">{kindLabels[r.kind]||r.kind} · {r.currency}</div></td><td className="p-2 text-xs">{r.country||"—"}<div className="text-[10px] text-muted2">{account?.name||"Non affectée à un compte unique"}</div></td><td className="p-2 text-right">{formatMoney(r.targetAmount,r.currency)}</td><td className="p-2 text-right font-semibold">{formatMoney(r.reservedAmount,r.currency)}</td><td className={`p-2 text-right ${shortage>0?"text-amber-700":"text-emerald-700"}`}>{formatMoney(shortage,r.currency)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${r.active?"bg-emerald-50 text-emerald-700":"bg-surface text-muted2"}`}>{r.active?"ACTIVE":"PAUSED"}</span></td><td className="p-2"><div className="flex flex-wrap gap-1"><form action={updateFinancialReserveAmountAction.bind(null,r.id)} className="flex gap-1"><input name="reservedAmount" type="number" step="0.01" defaultValue={r.reservedAmount} className="w-28 rounded border border-line px-2 py-1 text-xs"/><button className="rounded border border-line px-2 py-1 text-xs">Mettre à jour</button></form><form action={setFinancialReserveActiveAction.bind(null,r.id,!r.active)}><button className="rounded border border-line px-2 py-1 text-xs">{r.active?"Suspendre":"Réactiver"}</button></form></div></td></tr>})}</tbody></table></div>{!dashboard.reserves.length?<p className="py-5 text-center text-sm text-muted2">Aucune réserve ne correspond aux filtres actuels.</p>:null}</CardContent></Card>

    <Card><CardHeader><CardTitle>Disponibilité par compte</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{dashboard.accountUsage.map(a=><div key={a.accountId} className={`rounded-xl border p-4 ${a.overReserved?"border-red-200 bg-red-50":"border-line"}`}><div className="font-medium">{a.name}</div><div className="text-xs text-muted2">{a.country} · {a.currency}</div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div>Solde<div className="font-semibold">{formatMoney(a.balance,a.currency)}</div></div><div>Réservé<div className="font-semibold text-amber-700">{formatMoney(a.reserved,a.currency)}</div></div><div>Disponible<div className={`font-semibold ${a.available<0?"text-red-700":"text-emerald-700"}`}>{formatMoney(a.available,a.currency)}</div></div></div></div>)}</div>{!dashboard.accountUsage.length?<p className="text-sm text-muted2">Aucun compte ne correspond au périmètre sélectionné.</p>:null}</CardContent></Card>
  </div>
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof PiggyBank;label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
function Input({name,label,type="text",defaultValue,required=false}:{name:string;label:string;type?:string;defaultValue?:string;required?:boolean}){return <label className="text-xs">{label}<input name={name} type={type} step={type==="number"?"0.01":undefined} defaultValue={defaultValue} required={required} className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"/></label>}
