import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getCaseAdminOverview } from "@/lib/case-admin-overview";
import { caseAdminBulkAction } from "@/services/case-admin";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input, Select } from "@/components/ui/input";
import { formatDate, formatMoney } from "@/lib/utils";
import { AlertTriangle, BriefcaseBusiness, CircleDollarSign, Clock3, ListTodo, UserRoundX, UsersRound } from "lucide-react";

export const dynamic="force-dynamic";
const riskClass:Record<string,string>={LOW:"bg-emerald-100 text-emerald-800",MEDIUM:"bg-amber-100 text-amber-800",HIGH:"bg-orange-100 text-orange-800",CRITICAL:"bg-red-100 text-red-800"};
const STATUSES=["OPEN","IN_PROGRESS","WAITING_CLIENT","WAITING_INTERNAL","COMPLETED","CANCELLED","ARCHIVED"];
const PRIORITIES=["LOW","MEDIUM","HIGH","URGENT"];
const RISKS=["LOW","MEDIUM","HIGH","CRITICAL"];

export default async function CaseAdminDashboard({searchParams}:{searchParams:{q?:string;status?:string;owner?:string;priority?:string;risk?:string;overdue?:string}}){
 await requirePermission("CASE_ADMIN");
 const [overview,users]=await Promise.all([getCaseAdminOverview(),prisma.user.findMany({where:{status:"ACTIVE",role:{not:"CLIENT"}},orderBy:[{firstName:"asc"},{lastName:"asc"}],select:{id:true,firstName:true,lastName:true,role:true}})]);
 const q=(searchParams.q||"").trim().toLowerCase(),status=searchParams.status||"ALL",owner=searchParams.owner||"ALL",priority=searchParams.priority||"ALL",risk=searchParams.risk||"ALL",overdue=searchParams.overdue||"ALL";
 const rows=overview.rows.filter(r=>{
  if(q&&!`${r.caseNumber} ${r.title} ${r.client.firstName} ${r.client.lastName} ${r.client.internalId}`.toLowerCase().includes(q))return false;
  if(status!=="ALL"&&r.status!==status)return false;if(owner!=="ALL"&&(owner==="UNASSIGNED"?Boolean(r.owner):r.owner?.id!==owner))return false;if(priority!=="ALL"&&r.priority!==priority)return false;if(risk!=="ALL"&&r.riskLevel!==risk)return false;if(overdue==="YES"&&!r.caseOverdue)return false;if(overdue==="NO"&&r.caseOverdue)return false;return true;
 });
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/app/cases" className="text-sm text-muted2 hover:text-electric">← Cases</Link><h1 className="mt-2 text-2xl font-semibold">Case Admin Dashboard</h1><p className="mt-1 text-sm text-muted2">Global supervision of workload, deadlines, financial exposure, risk and ownership.</p></div><div className="flex gap-2"><Link href="/app/cases"><Button variant="outline">Case registry</Button></Link><Link href="/app/cases/new"><Button variant="primary">New case</Button></Link></div></div>

  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={BriefcaseBusiness} label="Active Cases" value={String(overview.totals.active)}/><Metric icon={Clock3} label="Overdue" value={String(overview.totals.overdue)} danger={overview.totals.overdue>0}/><Metric icon={AlertTriangle} label="High / critical risk" value={String(overview.totals.highRisk)} danger={overview.totals.highRisk>0}/><Metric icon={UserRoundX} label="Unassigned" value={String(overview.totals.unassigned)} danger={overview.totals.unassigned>0}/><Metric icon={ListTodo} label="Open tasks" value={String(overview.totals.openTasks)}/><Metric icon={UsersRound} label="Total Cases" value={String(overview.totals.total)}/></div>

  {overview.currencyTotals.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{overview.currencyTotals.map(f=><Card key={f.currency}><CardHeader><div className="flex items-center justify-between"><CardTitle>{f.currency} portfolio</CardTitle><CircleDollarSign className="h-4 w-4 text-electric"/></div></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><Money label="Billed" value={f.billed} currency={f.currency}/><Money label="Paid" value={f.invoicePaid} currency={f.currency}/><Money label="Receivable" value={f.receivable} currency={f.currency} danger={f.receivable>0}/><Money label="Refunds paid" value={-f.refundsPaid} currency={f.currency}/><Money label="Expenses paid" value={-f.expensePaid} currency={f.currency}/><Money label="Realized profit" value={f.realizedProfit} currency={f.currency} danger={f.realizedProfit<0}/></CardContent></Card>)}</div>:null}

  <Card><CardHeader><CardTitle>Manager filters</CardTitle></CardHeader><CardContent><form className="grid gap-2 md:grid-cols-3 xl:grid-cols-7"><Input name="q" defaultValue={searchParams.q} placeholder="Case, client, ID…"/><Select name="status" defaultValue={status}><option value="ALL">All statuses</option>{STATUSES.map(x=><option key={x}>{x}</option>)}</Select><Select name="owner" defaultValue={owner}><option value="ALL">All owners</option><option value="UNASSIGNED">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</Select><Select name="priority" defaultValue={priority}><option value="ALL">All priorities</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</Select><Select name="risk" defaultValue={risk}><option value="ALL">All risks</option>{RISKS.map(x=><option key={x}>{x}</option>)}</Select><Select name="overdue" defaultValue={overdue}><option value="ALL">Any deadline</option><option value="YES">Overdue only</option><option value="NO">Not overdue</option></Select><Button variant="outline">Apply filters</Button></form></CardContent></Card>

  <div className="grid gap-5 xl:grid-cols-[1fr_2fr]">
   <Card><CardHeader><CardTitle>Owner workload</CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y divide-line">{overview.workload.map(w=><div key={w.ownerId||"none"} className="px-5 py-4"><div className="flex items-center justify-between gap-3"><p className="font-medium">{w.ownerName}</p><span className="text-sm font-semibold">{w.activeCases} Cases</span></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs text-muted2"><span>{w.openTasks} open tasks</span><span className={w.overdueCases?"text-red-600":""}>{w.overdueCases} overdue</span><span className={w.highRisk?"text-orange-700":""}>{w.highRisk} high risk</span></div></div>)}</div></CardContent></Card>

   <Card><CardHeader><div><CardTitle>Supervision queue</CardTitle><p className="mt-1 text-xs text-muted2">{rows.length} Case(s) matching current filters. Select up to 100 for a manager action.</p></div></CardHeader><CardContent className="p-0"><form action={caseAdminBulkAction}><div className="flex flex-wrap gap-2 border-y border-line bg-surface/50 p-3"><Select name="ownerId" className="w-56"><option value="">Reassign selected…</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</Select><Button name="intent" value="assign" variant="outline">Assign owner</Button><Select name="priority" className="w-48"><option value="">Set priority…</option>{PRIORITIES.map(x=><option key={x}>{x}</option>)}</Select><Button name="intent" value="priority" variant="outline">Set priority</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead className="border-b border-line bg-surface/60 text-left text-xs uppercase tracking-wide text-muted2"><tr><th className="px-4 py-3">Select</th><th>Case</th><th>Client</th><th>Status</th><th>Priority</th><th>Risk</th><th>Owner</th><th>Work</th><th>Finance</th><th>Due</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-line align-top"><td className="px-4 py-4"><input type="checkbox" name="caseIds" value={r.id} className="h-4 w-4"/></td><td className="py-4 pr-4"><Link href={`/app/cases/${r.id}/dashboard`} className="registry-id hover:text-electric">{r.caseNumber}</Link><p className="mt-1 max-w-[220px] font-medium">{r.title}</p></td><td className="py-4 pr-4"><Link href={`/app/clients/${r.client.id}/dashboard`} className="hover:text-electric">{r.client.firstName} {r.client.lastName}</Link><p className="text-xs text-muted2">{r.client.internalId}</p></td><td className="py-4 pr-4"><StatusBadge status={r.status}/></td><td className="py-4 pr-4"><StatusBadge status={r.priority}/></td><td className="py-4 pr-4"><Badge className={riskClass[r.riskLevel]}>{r.riskLevel} · {r.riskScore}</Badge></td><td className="py-4 pr-4">{r.owner?`${r.owner.firstName} ${r.owner.lastName}`:<span className="text-red-600">Unassigned</span>}</td><td className="py-4 pr-4"><p>{r.openTasks} open</p><p className={r.overdueTasks?"text-xs text-red-600":"text-xs text-muted2"}>{r.overdueTasks} overdue</p></td><td className="py-4 pr-4">{r.finance.length?r.finance.map(f=><div key={f.currency} className="mb-1 text-xs"><strong>{f.currency}</strong> · due {formatMoney(f.receivable,f.currency)} · profit <span className={f.realizedProfit<0?"text-red-600":""}>{formatMoney(f.realizedProfit,f.currency)}</span></div>):<span className="text-xs text-muted2">No finance</span>}</td><td className={`py-4 pr-4 ${r.caseOverdue?"font-medium text-red-600":"text-muted2"}`}>{formatDate(r.dueDate)}{r.caseOverdue?<div className="text-xs">OVERDUE</div>:null}</td></tr>)}</tbody></table></div></form></CardContent></Card>
  </div>
 </div>;
}
function Metric({icon:Icon,label,value,danger=false}:{icon:any;label:string;value:string;danger?:boolean}){return <Card><CardContent className="p-4"><Icon className={`h-4 w-4 ${danger?"text-red-600":"text-electric"}`}/><p className="mt-3 text-xs text-muted2">{label}</p><p className={`mt-1 text-xl font-semibold ${danger?"text-red-600":""}`}>{value}</p></CardContent></Card>}
function Money({label,value,currency,danger=false}:{label:string;value:number;currency:string;danger?:boolean}){return <div><p className="text-xs text-muted2">{label}</p><p className={`mt-1 font-medium ${danger?"text-red-600":""}`}>{formatMoney(value,currency)}</p></div>}
