import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getTreasuryStore } from "@/lib/company-funds";
import { listFinancialAuthorizations } from "@/lib/company-funds-approvals";
import { listFinancialExecutionEvidence } from "@/lib/company-funds-execution-evidence";
import { recordFinancialExecutionEvidenceAction } from "@/services/company-funds-execution-evidence";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileCheck2, ShieldCheck, Clock3, CheckCircle2 } from "lucide-react";

export const dynamic="force-dynamic";
export default async function FinancialExecutionEvidencePage(){
  const user=await requireUser();if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
  const [authorizations,evidence,treasury,files]=await Promise.all([
    listFinancialAuthorizations(1000),listFinancialExecutionEvidence(1000),getTreasuryStore(),
    prisma.file.findMany({where:{archivedAt:null},orderBy:{createdAt:"desc"},take:200,select:{id:true,name:true,createdAt:true}}),
  ]);
  const evidenceByAuthorization=new Map(evidence.map(e=>[e.authorizationId,e]));
  const ready=authorizations.filter(a=>a.status==="APPROVED"&&!evidenceByAuthorization.has(a.id));
  return <div className="space-y-5">
    <div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Super Admin · Controle execution</p><h1 className="mt-1 text-3xl font-semibold">Preuves execution financiere</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Une autorisation approuvee ne suffit pas. JUN exige une reference de transaction, le compte utilise et un justificatif Drive avant de considerer une sortie comme executee.</p></div>
    <div className="grid gap-3 md:grid-cols-4"><Metric icon={Clock3} label="A documenter" value={String(ready.length)} hint="Autorisations approuvees sans preuve"/><Metric icon={CheckCircle2} label="Documentees" value={String(evidence.length)} hint="Executions avec justificatif"/><Metric icon={FileCheck2} label="Fichiers disponibles" value={String(files.length)} hint="200 fichiers Drive recents"/><Metric icon={ShieldCheck} label="Comptes actifs" value={String(treasury.accounts.filter(a=>a.active).length)} hint="Comptes utilisables pour execution"/></div>

    <Card><CardHeader><CardTitle>Operations approuvees a documenter</CardTitle></CardHeader><CardContent>{ready.length?<div className="space-y-3">{ready.map(a=><div key={a.id} className="rounded-xl border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{a.reference} · {a.type}</div><div className="mt-1 text-xs text-muted2">{a.description}</div><div className="mt-1 text-sm font-semibold">{formatMoney(a.amount,a.currency)}</div></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">APPROVED</span></div><form action={recordFinancialExecutionEvidenceAction.bind(null,a.id)} className="mt-4 grid gap-3 md:grid-cols-5"><label className="text-xs">Compte reel utilise<select name="treasuryAccountId" className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"><option value="">Non affecte</option>{treasury.accounts.filter(x=>x.active&&x.currency===a.currency).map(x=><option key={x.id} value={x.id}>{x.name} · {x.country} · {x.currency}</option>)}</select></label><label className="text-xs">Reference transaction<input name="transactionReference" required className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"/></label><label className="text-xs">Justificatif Drive<select name="proofFileId" required className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"><option value="">Selectionner</option>{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="text-xs">Date execution<input name="executedAt" type="datetime-local" className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"/></label><label className="text-xs">Note<input name="note" className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"/></label><div className="md:col-span-5"><button className="rounded-lg bg-ink px-3 py-2 text-sm font-medium text-white">Enregistrer preuve execution</button></div></form></div>)}</div>:<p className="text-sm text-muted2">Aucune autorisation approuvee en attente de preuve.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Historique des preuves</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Reference</th><th className="p-2">Type</th><th className="p-2">Transaction</th><th className="p-2">Compte</th><th className="p-2">Justificatif</th><th className="p-2">Execute le</th></tr></thead><tbody>{evidence.map(e=>{const account=treasury.accounts.find(a=>a.id===e.treasuryAccountId);const file=files.find(f=>f.id===e.proofFileId);return <tr key={e.id} className="border-b border-line/70"><td className="p-2 font-medium">{e.reference}</td><td className="p-2">{e.type}</td><td className="p-2 registry-id text-xs">{e.transactionReference}</td><td className="p-2">{account?.name||"Non affecte"}</td><td className="p-2">{file?<a className="text-electric hover:underline" href={`/api/files/${file.id}`} target="_blank" rel="noreferrer">{file.name}</a>:<span className="registry-id text-xs">{e.proofFileId}</span>}</td><td className="p-2 text-xs">{formatDateTime(e.executedAt)}</td></tr>})}</tbody></table></div>{!evidence.length?<p className="py-5 text-center text-sm text-muted2">Aucune preuve execution enregistree.</p>:null}</CardContent></Card>
  </div>
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof ShieldCheck;label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
