import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { getInvoice, invoiceFinancialState } from "@/lib/finance-invoices";
import { prisma } from "@/lib/prisma";
import { formatDate, formatMoney } from "@/lib/utils";

export const dynamic="force-dynamic";
export default async function InvoicePrintPage({params}:{params:{id:string}}){
  await requirePermission("INVOICE_READ");
  const invoice=await getInvoice(params.id);if(!invoice)notFound();
  const state=await invoiceFinancialState(invoice);
  const client=await prisma.client.findUnique({where:{id:invoice.clientId},select:{firstName:true,lastName:true,email:true,phone:true,address:true,country:true,internalId:true}});
  return <main className="mx-auto max-w-4xl bg-white p-10 text-sm text-slate-900 print:p-0">
    <div className="flex items-start justify-between border-b-2 border-slate-900 pb-6"><div><div className="text-2xl font-bold">JUN CREATIF AND TRAVEL LLC</div><div className="mt-1 text-slate-500">Professional Invoice</div></div><div className="text-right"><div className="text-3xl font-bold">INVOICE</div><div className="mt-2 font-mono">{invoice.invoiceNumber}</div></div></div>
    <div className="mt-8 grid grid-cols-2 gap-8"><section><div className="text-xs font-semibold uppercase tracking-wider text-slate-500">Bill to</div><div className="mt-2 text-lg font-semibold">{client?`${client.firstName} ${client.lastName}`:"Client"}</div><div>{client?.internalId}</div><div>{client?.address}</div><div>{client?.country}</div><div>{client?.email}</div><div>{client?.phone}</div></section><section className="text-right"><div><span className="text-slate-500">Issue date:</span> {formatDate(new Date(invoice.issueDate))}</div><div><span className="text-slate-500">Due date:</span> {formatDate(new Date(invoice.dueDate))}</div><div><span className="text-slate-500">Currency:</span> {invoice.currency}</div><div className="mt-3 text-lg font-semibold">{invoice.title}</div></section></div>
    <table className="mt-8 w-full border-collapse"><thead><tr className="border-y border-slate-300 bg-slate-50 text-left"><th className="p-3">Description</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Unit price</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{invoice.lines.map(l=><tr key={l.id} className="border-b border-slate-200"><td className="p-3">{l.description}</td><td className="p-3 text-right">{l.quantity}</td><td className="p-3 text-right">{formatMoney(l.unitPrice,invoice.currency)}</td><td className="p-3 text-right">{l.taxRate.toFixed(2)}%</td><td className="p-3 text-right font-medium">{formatMoney(l.lineTotal,invoice.currency)}</td></tr>)}</tbody></table>
    <div className="mt-6 ml-auto w-80 space-y-2"><div className="flex justify-between"><span>Subtotal</span><strong>{formatMoney(invoice.subtotal,invoice.currency)}</strong></div><div className="flex justify-between"><span>Tax</span><strong>{formatMoney(invoice.taxTotal,invoice.currency)}</strong></div><div className="flex justify-between border-t border-slate-900 pt-2 text-lg"><span>Total</span><strong>{formatMoney(invoice.total,invoice.currency)}</strong></div><div className="flex justify-between text-emerald-700"><span>Paid</span><strong>{formatMoney(state.paid,invoice.currency)}</strong></div><div className="flex justify-between text-xl"><span>Balance due</span><strong>{formatMoney(state.balance,invoice.currency)}</strong></div></div>
    <div className="mt-10 grid gap-4"><section><div className="font-semibold">Payment terms</div><p className="mt-1 whitespace-pre-wrap text-slate-600">{invoice.terms}</p></section>{invoice.notes?<section><div className="font-semibold">Notes</div><p className="mt-1 whitespace-pre-wrap text-slate-600">{invoice.notes}</p></section>:null}</div>
    <footer className="mt-12 border-t border-slate-300 pt-4 text-xs text-slate-500">This invoice is generated by JUN Business Hub. Confirm payments only through official JUN payment and receipt workflows.</footer>
  </main>;
}
