import Link from "next/link";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import {
  accountConcentration,
  cashBurnAndRunway,
  executiveTreasuryAlerts,
  getTreasuryStore,
  loanMaturitySchedule,
  monthlyTreasuryDashboard,
  profitabilityByCountry,
  projectPerformance,
} from "@/lib/company-funds";
import { getLiquidityProtectionAlerts, getProtectedCashForecast } from "@/lib/company-funds-liquidity-risk";
import { formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Banknote, Building2, CalendarClock, Gauge, Landmark, ShieldCheck, TrendingUp, Umbrella, WalletCards } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ExecutiveTreasuryPage(){
  const user=await requireUser(); if(user.role!=="SUPER_ADMIN") redirect("/app/forbidden");
  const store=await getTreasuryStore();
  const [protectedForecast,liquidityAlerts]=await Promise.all([getProtectedCashForecast(),getLiquidityProtectionAlerts()]);
  const monthly=monthlyTreasuryDashboard(store);
  const runway=cashBurnAndRunway(store);
  const countries=profitabilityByCountry(store);
  const concentration=accountConcentration(store);
  const loans=loanMaturitySchedule(store);
  const projects=projectPerformance(store).sort((a,b)=>b.profit-a.profit);
  const alerts=[...liquidityAlerts,...executiveTreasuryAlerts(store)];
  const critical=alerts.filter(a=>a.severity==="CRITICAL").length;
  const warning=alerts.filter(a=>a.severity==="WARNING").length;

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/app/company-funds" className="text-xs font-medium text-electric">← Fonds de l’entreprise</Link><p className="mt-3 text-xs uppercase tracking-[0.18em] text-muted2">Super Admin · Direction financière</p><h1 className="mt-1 text-3xl font-semibold">Control Center CFO</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Pilotage exécutif de la trésorerie, rentabilité, concentration bancaire, dette, réserves protégées, cash burn et risques financiers.</p></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><ShieldCheck className="mr-1 inline h-4 w-4"/>SUPER ADMIN ONLY</span></div>

    <div className="grid gap-3 md:grid-cols-4"><Metric icon={AlertTriangle} label="Alertes critiques" value={String(critical)} hint={`${warning} avertissement(s)`} tone={critical?"bad":warning?"watch":"good"}/><Metric icon={Landmark} label="Comptes suivis" value={String(store.accounts.filter(a=>a.active).length)} hint={`${concentration.filter(c=>c.risk!=="NORMAL").length} concentration(s) à surveiller`}/><Metric icon={TrendingUp} label="Projets rentables" value={String(projects.filter(p=>p.profit>0).length)} hint={`${projects.filter(p=>p.profit<0).length} déficitaire(s)`}/><Metric icon={CalendarClock} label="Prêts actifs" value={String(loans.length)} hint={`${loans.filter(l=>["OVERDUE","DUE_SOON"].includes(l.severity)).length} urgent(s)`}/></div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Umbrella className="h-5 w-5"/>Cash protégé & prévision 30 / 60 / 90 jours</CardTitle></CardHeader><CardContent><div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-relaxed text-blue-800"><strong>Nouvelle logique de sécurité :</strong> JUN ne considère plus tout le solde bancaire comme dépensable. La prévision déduit les réserves financières protégées, les sorties planifiées, les prêts arrivant à échéance et les investissements prévus avant de calculer le cash réellement disponible.</div>{protectedForecast.length?<div className="space-y-4">{[...new Set(protectedForecast.map(r=>r.currency))].map(currency=><div key={currency} className="rounded-xl border border-line p-4"><div className="mb-3 flex items-center justify-between"><div className="font-semibold">{currency}</div><Link href="/app/company-funds/reserves" className="text-xs font-medium text-electric">Gérer les réserves →</Link></div><div className="grid gap-3 xl:grid-cols-3">{protectedForecast.filter(r=>r.currency===currency).map(r=><div key={`${currency}-${r.horizon}`} className={`rounded-xl border p-3 ${r.status==="CRITICAL"?"border-red-200 bg-red-50":r.status==="WATCH"?"border-amber-200 bg-amber-50":"border-emerald-200 bg-emerald-50"}`}><div className="flex items-center justify-between"><span className="text-sm font-semibold">À {r.horizon} jours</span><span className="text-[10px] font-semibold">{r.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Kpi label="Cash projeté" value={formatMoney(r.projectedCash,currency)}/><Kpi label="Réserves protégées" value={formatMoney(r.reserved,currency)}/><Kpi label="Disponible protégé" value={formatMoney(r.protectedAvailable,currency)}/><Kpi label="Entrées prévues" value={formatMoney(r.plannedIn,currency)}/><Kpi label="Sorties prévues" value={formatMoney(r.plannedOut,currency)}/><Kpi label="Prêts à échéance" value={formatMoney(r.loanDue,currency)}/></div>{r.reserveDeficit>0?<div className="mt-2 rounded-lg bg-white/70 p-2 text-xs font-medium text-red-700">Déficit potentiel de sécurité : {formatMoney(r.reserveDeficit,currency)}</div>:null}</div>)}</div></div>)}</div>:<p className="text-sm text-muted2">Aucune donnée de prévision ou de réserve disponible.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5"/>Alertes de direction</CardTitle></CardHeader><CardContent>{alerts.length?<div className="grid gap-2 lg:grid-cols-2">{alerts.slice(0,24).map(a=><div key={a.id} className={`rounded-xl border p-3 ${a.severity==="CRITICAL"?"border-red-200 bg-red-50":a.severity==="WARNING"?"border-amber-200 bg-amber-50":"border-blue-200 bg-blue-50"}`}><div className="flex items-center justify-between gap-2"><div className="text-sm font-semibold">{a.title}</div><span className="text-[10px] font-semibold">{a.severity}</span></div><div className="mt-1 text-xs text-muted2">{a.detail}{a.currency?` · ${a.currency}`:""}</div></div>)}</div>:<p className="text-sm text-emerald-700">Aucune alerte financière importante.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Gauge className="h-5 w-5"/>Cash burn & runway</CardTitle></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-3">{runway.map(r=><div key={r.currency} className={`rounded-xl border p-4 ${r.status==="CRITICAL"?"border-red-200 bg-red-50":r.status==="WATCH"?"border-amber-200 bg-amber-50":"border-line bg-white"}`}><div className="flex items-center justify-between"><span className="font-semibold">{r.currency}</span><span className="text-[10px] font-semibold">{r.status==="NO_DATA"?"Pas assez de données":r.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Kpi label="Cash disponible" value={formatMoney(r.cash,r.currency)}/><Kpi label="Burn mensuel moyen" value={formatMoney(r.monthlyBurn,r.currency)}/><Kpi label="Sorties 90 jours" value={formatMoney(r.out90,r.currency)}/><Kpi label="Runway" value={r.runwayMonths===null?"—":`${r.runwayMonths} mois`}/></div></div>)}</div><p className="mt-3 text-[11px] text-muted2">Runway historique = cash actuel ÷ moyenne mensuelle des sorties projets des 90 derniers jours. La section Cash protégé ci-dessus applique en plus les réserves et engagements futurs.</p></CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5"/>Performance mensuelle</CardTitle></CardHeader><CardContent className="space-y-4">{monthly.map(group=><div key={group.currency} className="rounded-xl border border-line p-4"><div className="mb-3 font-semibold">{group.currency} · 12 derniers mois</div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr className="border-b text-left text-muted2"><th className="p-2">Mois</th><th className="p-2 text-right">Entrées</th><th className="p-2 text-right">Sorties</th><th className="p-2 text-right">Profit</th><th className="p-2 text-right">Marge</th><th className="p-2 text-right">Projets actifs</th></tr></thead><tbody>{group.months.map(m=><tr key={m.month} className="border-b border-line/60"><td className="p-2 font-medium">{m.month}</td><td className="p-2 text-right">{formatMoney(m.income,group.currency)}</td><td className="p-2 text-right">{formatMoney(m.expense,group.currency)}</td><td className={`p-2 text-right font-semibold ${m.profit>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(m.profit,group.currency)}</td><td className="p-2 text-right">{m.margin===null?"—":`${m.margin}%`}</td><td className="p-2 text-right">{m.activeProjects}</td></tr>)}</tbody></table></div></div>)}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-5 w-5"/>Rentabilité par pays</CardTitle></CardHeader><CardContent>{countries.length?<div className="space-y-2">{countries.map(c=><div key={`${c.country}-${c.currency}`} className="rounded-lg border border-line p-3"><div className="flex items-center justify-between"><div><div className="font-medium">{c.country}</div><div className="text-[10px] text-muted2">{c.projectCount} projet(s) · {c.currency}</div></div><div className={`text-right font-semibold ${c.profit>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(c.profit,c.currency)}<div className="text-[10px] font-normal text-muted2">marge {c.margin===null?"—":`${c.margin}%`}</div></div></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><Kpi label="Entrées" value={formatMoney(c.income,c.currency)}/><Kpi label="Sorties" value={formatMoney(c.expense,c.currency)}/></div></div>)}</div>:<p className="text-sm text-muted2">Aucune donnée projet par pays.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><WalletCards className="h-5 w-5"/>Top / Flop projets</CardTitle></CardHeader><CardContent>{projects.length?<div className="space-y-2">{projects.slice(0,12).map((p,index)=><div key={p.id} className="flex items-center justify-between gap-3 rounded-lg border border-line p-3"><div><div className="text-sm font-medium">#{index+1} · {p.name}</div><div className="text-[10px] text-muted2">{p.country} · {p.transactionCount} flux</div></div><div className={`text-right font-semibold ${p.profit>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(p.profit,p.currency)}<div className="text-[10px] font-normal text-muted2">{p.margin===null?"—":`${p.margin}% marge`}</div></div></div>)}</div>:<p className="text-sm text-muted2">Aucun projet synchronisé.</p>}</CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5"/>Concentration des fonds par compte</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Compte</th><th className="p-2">Institution</th><th className="p-2">Pays</th><th className="p-2 text-right">Solde</th><th className="p-2 text-right">Part des liquidités</th><th className="p-2">Risque</th></tr></thead><tbody>{concentration.map(c=><tr key={c.accountId} className="border-b border-line/60"><td className="p-2 font-medium">{c.name}</td><td className="p-2">{c.institution}</td><td className="p-2">{c.country}</td><td className="p-2 text-right">{formatMoney(c.balance,c.currency)}</td><td className="p-2 text-right font-semibold">{c.sharePercent}%</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${c.risk==="HIGH"?"bg-red-50 text-red-700":c.risk==="WATCH"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{c.risk}</span></td></tr>)}</tbody></table></div></CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Banknote className="h-5 w-5"/>Échéancier des prêts</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Prêteur</th><th className="p-2">Objet</th><th className="p-2 text-right">Solde</th><th className="p-2 text-right">Taux</th><th className="p-2 text-right">Intérêt annuel estimé</th><th className="p-2">Échéance</th><th className="p-2 text-right">Jours</th><th className="p-2">État</th></tr></thead><tbody>{loans.map(l=><tr key={l.id} className="border-b border-line/60"><td className="p-2 font-medium">{l.lender}</td><td className="p-2 text-xs">{l.purpose||"—"}</td><td className="p-2 text-right font-semibold">{formatMoney(l.outstandingBalance,l.currency)}</td><td className="p-2 text-right">{l.interestRate}%</td><td className="p-2 text-right">{formatMoney(l.annualInterest,l.currency)}</td><td className="p-2 text-xs">{l.dueDate||"—"}</td><td className="p-2 text-right">{l.daysUntilDue===null?"—":l.daysUntilDue}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${l.severity==="OVERDUE"?"bg-red-50 text-red-700":l.severity==="DUE_SOON"?"bg-amber-50 text-amber-700":"bg-surface"}`}>{l.severity}</span></td></tr>)}</tbody></table></div></CardContent></Card>
  </div>;
}

function Metric({icon:Icon,label,value,hint,tone="neutral"}:{icon:typeof Landmark;label:string;value:string;hint:string;tone?:"neutral"|"good"|"watch"|"bad"}){const cls=tone==="good"?"border-emerald-200 bg-emerald-50":tone==="watch"?"border-amber-200 bg-amber-50":tone==="bad"?"border-red-200 bg-red-50":"border-line bg-white";return <div className={`rounded-xl border p-4 ${cls}`}><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-surface p-2.5"><div className="text-[10px] uppercase tracking-wide text-muted2">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}
