import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission, can } from "@/lib/auth";
import { getInvoice, invoiceFinancialState } from "@/lib/finance-invoices";
import { prisma } from "@/lib/prisma";
import { markInvoiceSent, cancelInvoice, linkPaymentToInvoice, recordInvoiceReminder, createInvoiceOnlinePayment } from "@/services/finance-invoices";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { formatDate, formatMoney } from "@/lib/utils";
import { AlertTriangle, CheckCircle2, Clock3, CreditCard, Printer, Send, Undo2 } from "lucide-react";

export const dynamic="force-dynamic";
export default async function InvoiceDetailPage({params,searchParams}:{params:{id:string};searchParams:{toast?:string;toast_error?:string}}){
  const user=await requirePermission("INVOICE_READ");
  const invoice=await getInvoice(params.id); if(!invoice) notFound();
  const state=await invoiceFinancialState(invoice);
  const [client,linkedCase,payments]=await Promise.all([
    prisma.client.findUnique({where:{id:invoice.clientId},select:{firstName:true,lastName:true,email:true,phone:true,address:true,country:true,internalId:true}}),
    invoice.caseId?prisma.case.findUnique({where:{id:invoice.caseId},select:{caseNumber:true,title:true}}):Promise.resolve(null),
    prisma.payment.findMany({where:{clientId:invoice.clientId,currency:invoice.currency},orderBy:{createdAt:"desc"},take:100,select:{id:true,reference:true,amount:true,status:true,paidAt:true,provider:true}}),
  ]);
  const linkedIds=new Set(invoice.payments.map(p=>p.paymentId));
  const availablePayments=payments.filter(p=>!linkedIds.has(p.id));
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-muted2">Accounts Receivable</p><h1 className="mt-1 text-3xl font-semibold">{invoice.invoiceNumber}</h1><p className="mt-1 text-sm text-muted2">{invoice.title} · {client?`${client.firstName} ${client.lastName}`:"Unknown client"}</p></div><div className="flex flex-wrap gap-2"><Link href="/app/finance/invoices" className="rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium">Back</Link><Link href={`/app/finance/invoices/${invoice.id}/print`} target="_blank" className="inline-flex items-center gap-2 rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium"><Printer className="h-4 w-4"/>Print invoice</Link></div></div>
    {searchParams.toast?<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{searchParams.toast}</div>:null}{searchParams.toast_error?<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{searchParams.toast_error}</div>:null}
    <div className="grid gap-3 sm:grid-cols-4"><Metric label="Invoice total" value={formatMoney(invoice.total,invoice.currency)} icon={CreditCard}/><Metric label="Confirmed paid" value={formatMoney(state.paid,invoice.currency)} icon={CheckCircle2}/><Metric label="Balance due" value={formatMoney(state.balance,invoice.currency)} icon={Clock3}/><Metric label="Status" value={state.effectiveStatus.replaceAll("_"," ")} icon={state.overdue?AlertTriangle:Send}/></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]">
      <div className="space-y-5">
        <Card><CardHeader><CardTitle>Invoice</CardTitle></CardHeader><CardContent><div className="grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-4"><Value label="Client" value={client?`${client.firstName} ${client.lastName}`:"—"}/><Value label="Client ID" value={client?.internalId||"—"}/><Value label="Case" value={linkedCase?`${linkedCase.caseNumber} · ${linkedCase.title}`:"—"}/><Value label="Currency" value={invoice.currency}/><Value label="Issue date" value={formatDate(new Date(invoice.issueDate))}/><Value label="Due date" value={formatDate(new Date(invoice.dueDate))}/><Value label="Email" value={client?.email||"—"}/><Value label="Phone" value={client?.phone||"—"}/></div><div className="mt-5 overflow-x-auto rounded-lg border border-line"><table className="w-full text-sm"><thead className="bg-surface text-left text-xs text-muted2"><tr><th className="p-3">Description</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Unit</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{invoice.lines.map(l=><tr key={l.id} className="border-t border-line"><td className="p-3">{l.description}</td><td className="p-3 text-right">{l.quantity}</td><td className="p-3 text-right">{formatMoney(l.unitPrice,invoice.currency)}</td><td className="p-3 text-right">{l.taxRate.toFixed(2)}%</td><td className="p-3 text-right font-medium">{formatMoney(l.lineTotal,invoice.currency)}</td></tr>)}</tbody></table></div><div className="mt-4 ml-auto max-w-xs space-y-1 text-sm"><div className="flex justify-between"><span className="text-muted2">Subtotal</span><strong>{formatMoney(invoice.subtotal,invoice.currency)}</strong></div><div className="flex justify-between"><span className="text-muted2">Tax</span><strong>{formatMoney(invoice.taxTotal,invoice.currency)}</strong></div><div className="flex justify-between border-t border-line pt-2 text-lg"><span>Total</span><strong>{formatMoney(invoice.total,invoice.currency)}</strong></div></div>{invoice.notes?<div className="mt-4 rounded-lg bg-surface p-3 text-sm"><strong>Notes:</strong> {invoice.notes}</div>:null}<div className="mt-3 text-xs text-muted2">Terms: {invoice.terms}</div></CardContent></Card>
        <Card><CardHeader><CardTitle>Payments applied</CardTitle></CardHeader><CardContent>{state.confirmedPayments.length?<div className="space-y-2">{state.confirmedPayments.map(p=><Link key={p.id} href={`/app/finance/payments/${p.id}`} className="flex items-center justify-between rounded-lg border border-line p-3 text-sm hover:bg-surface"><span><span className="registry-id">{p.reference}</span><span className="ml-2 text-xs text-muted2">{p.paidAt?formatDate(p.paidAt):"Pending date"}</span></span><strong>{formatMoney(p.amount,p.currency)}</strong></Link>)}</div>:<p className="text-sm text-muted2">No confirmed payments have been applied yet.</p>}{invoice.payments.length>state.confirmedPayments.length?<p className="mt-3 text-xs text-amber-700">Some linked payments are still pending confirmation and do not reduce the official balance yet.</p>:null}</CardContent></Card>
        <Card><CardHeader><CardTitle>Reminder history</CardTitle></CardHeader><CardContent>{invoice.reminders.length?<div className="space-y-2">{[...invoice.reminders].reverse().map((r,i)=><div key={`${r.sentAt}-${i}`} className="rounded-lg border border-line p-3 text-sm"><div className="font-medium">{r.channel} · {formatDate(new Date(r.sentAt))}</div><div className="mt-1 text-muted2">{r.note}</div></div>)}</div>:<p className="text-sm text-muted2">No reminders recorded.</p>}</CardContent></Card>
      </div>
      <div className="space-y-4">
        {invoice.status==="DRAFT"&&can(user,"INVOICE_APPROVE")?<Card><CardHeader><CardTitle>Issue invoice</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted2">Mark the draft as sent before collecting payment.</p><form action={markInvoiceSent.bind(null,invoice.id)}><Button variant="primary"><Send className="h-4 w-4"/>Mark as sent</Button></form></CardContent></Card>:null}
        {invoice.status!=="DRAFT"&&invoice.status!=="CANCELLED"&&state.balance>0&&can(user,"PAYMENT_CREATE")?<Card><CardHeader><CardTitle>Create online payment link</CardTitle></CardHeader><CardContent><form action={createInvoiceOnlinePayment.bind(null,invoice.id)} className="space-y-3"><Field label="Provider"><Select name="provider" defaultValue="STRIPE"><option value="STRIPE">Stripe</option><option value="PAYPAL">PayPal</option><option value="MERCADO_PAGO">Mercado Pago</option></Select></Field><Field label="Amount"><Input name="amount" type="number" step="0.01" min="0.01" max={state.balance} defaultValue={state.balance}/></Field><Button variant="primary">Create secure payment link</Button></form></CardContent></Card>:null}
        {invoice.status!=="CANCELLED"&&state.balance>0&&can(user,"INVOICE_CREATE")?<Card><CardHeader><CardTitle>Link existing payment</CardTitle></CardHeader><CardContent>{availablePayments.length?<form action={linkPaymentToInvoice.bind(null,invoice.id)} className="space-y-3"><Field label="Payment"><Select name="paymentId" required><option value="">Select payment…</option>{availablePayments.map(p=><option key={p.id} value={p.id}>{p.reference} · {formatMoney(Number(p.amount),invoice.currency)} · {p.status}</option>)}</Select></Field><Button variant="outline">Link payment</Button></form>:<p className="text-sm text-muted2">No unlinked payments in the same client/currency.</p>}</CardContent></Card>:null}
        {invoice.status!=="CANCELLED"&&state.balance>0&&can(user,"INVOICE_CREATE")?<Card><CardHeader><CardTitle>Payment reminder</CardTitle></CardHeader><CardContent><form action={recordInvoiceReminder.bind(null,invoice.id)} className="space-y-3"><Field label="Channel"><Select name="channel"><option value="EMAIL">Email</option><option value="WHATSAPP">WhatsApp</option><option value="MANUAL">Manual</option></Select></Field><Field label="Note"><Textarea name="note" rows={3} defaultValue={`Reminder for ${invoice.invoiceNumber}: balance ${formatMoney(state.balance,invoice.currency)} due ${formatDate(new Date(invoice.dueDate))}.`}/></Field><Button variant="outline">Record reminder</Button></form></CardContent></Card>:null}
        {invoice.status!=="CANCELLED"&&state.paid<=0&&can(user,"INVOICE_APPROVE")?<Card><CardHeader><CardTitle>Cancel invoice</CardTitle></CardHeader><CardContent><form action={cancelInvoice.bind(null,invoice.id)} className="space-y-3"><Field label="Reason"><Textarea name="reason" rows={3} required/></Field><Button variant="outline"><Undo2 className="h-4 w-4"/>Cancel invoice</Button></form></CardContent></Card>:null}
      </div>
    </div>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof CreditCard}){return <Card><CardContent className="p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-xl font-semibold">{value}</div></CardContent></Card>}
function Value({label,value}:{label:string;value:string}){return <div><div className="text-[10px] uppercase tracking-wide text-muted2">{label}</div><div className="mt-1 font-medium">{value}</div></div>}
