import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { getFinanceControlCenter } from "@/lib/finance-control-center";
import { expenseRemaining } from "@/lib/finance-expenses";
import { formatDate, formatDateTime, formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Banknote, CircleDollarSign, Clock3, Download, Landmark, ReceiptText, RefreshCw, Target, WalletCards } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function FinanceControlCenterPage() {
  await requirePermission("PAYMENT_READ");
  const data = await getFinanceControlCenter();
  const alertTotal = Object.values(data.alerts.counts).reduce((sum, value) => sum + value, 0);
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Finance operations</p><h1 className="mt-1 text-3xl font-semibold">Finance Control Center</h1><p className="mt-1 text-sm text-muted2">Cash position, collections, refunds, expenses, accounts payable, budgets and operational exceptions in one view.</p></div><div className="flex flex-wrap gap-2"><a href="/api/finance/export.csv"><span className="inline-flex items-center gap-2 rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium"><Download className="h-4 w-4" />Export CSV</span></a><Link href="/app/finance/reports" className="inline-flex items-center gap-2 rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium"><RefreshCw className="h-4 w-4" />Reports</Link></div></div>

    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6">
      <Metric icon={CircleDollarSign} label="Currencies tracked" value={String(data.currencies.length)} hint={`${data.ytdPaymentCount} confirmed payments YTD`} />
      <Metric icon={Landmark} label="Receiving accounts" value={`${data.accounts.active}/${data.accounts.total}`} hint="Active / configured" />
      <Metric icon={WalletCards} label="Online payments" value={String(data.online.paid)} hint={`${data.online.pending} pending · ${data.online.attention} attention`} />
      <Metric icon={CircleDollarSign} label="Accounts payable" value={String(data.expenses.open)} hint={`${data.expenses.overdue} overdue`} />
      <Metric icon={Target} label="Budget alerts" value={String(data.budgets.varianceAlerts)} hint={`${data.budgets.active} active budget${data.budgets.active===1?"":"s"}`} />
      <Metric icon={AlertTriangle} label="Operational alerts" value={String(alertTotal)} hint="Items requiring finance attention" />
    </div>

    <Card><CardHeader><CardTitle>Cash position by currency</CardTitle></CardHeader><CardContent>{data.currencies.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.currencies.map((row) => <div key={row.currency} className="rounded-xl border border-line bg-surface p-4"><div className="flex items-center justify-between"><span className="registry-id text-sm">{row.currency}</span><span className={`text-xs font-semibold ${row.netCash >= 0 ? "text-emerald-700" : "text-red-700"}`}>{row.netCash >= 0 ? "POSITIVE" : "NEGATIVE"}</span></div><div className="mt-3 text-2xl font-semibold">{formatMoney(row.netCash, row.currency)}</div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Mini label="Collected" value={formatMoney(row.collected, row.currency)} /><Mini label="Fees" value={formatMoney(row.fees, row.currency)} /><Mini label="Refunded" value={formatMoney(row.refundsPaid, row.currency)} /><Mini label="Expenses" value={formatMoney(row.expensesPaid, row.currency)} /></div></div>)}</div> : <p className="text-sm text-muted2">No confirmed financial movement yet.</p>}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>This month cash flow</CardTitle></CardHeader><CardContent className="space-y-2">{data.monthCurrencies.length ? data.monthCurrencies.map((row) => <div key={row.currency} className="flex items-center justify-between rounded-lg border border-line px-3 py-3"><div><div className="registry-id">{row.currency}</div><div className="mt-1 text-xs text-muted2">Net collections after fees, refunds and operating expenses</div></div><div className="text-right"><div className={`font-semibold ${row.net >= 0 ? "text-emerald-700" : "text-red-700"}`}>{formatMoney(row.net, row.currency)}</div><div className="text-[11px] text-muted2">{formatMoney(row.collected,row.currency)} in · {formatMoney(row.refunds+row.expenses,row.currency)} out</div></div></div>) : <p className="text-sm text-muted2">No cash movement this month.</p>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Accounts payable by currency</CardTitle></CardHeader><CardContent className="space-y-2">{data.expenses.apByCurrency.length ? data.expenses.apByCurrency.map((row) => <Link key={row.currency} href="/app/finance/expenses" className="flex items-center justify-between rounded-lg border border-line px-3 py-3 hover:bg-surface"><div><div className="registry-id">{row.currency}</div><div className="text-xs text-muted2">{row.count} open vendor bill{row.count===1?"":"s"}</div></div><div className="text-right"><div className="font-semibold">{formatMoney(row.outstanding,row.currency)}</div><div className={`text-[11px] ${row.overdue>0?"text-red-700":"text-muted2"}`}>{formatMoney(row.overdue,row.currency)} overdue</div></div></Link>) : <p className="text-sm text-muted2">No open vendor bills.</p>}</CardContent></Card>
    </div>

    <div className="grid gap-4 xl:grid-cols-3">
      <AlertCard title="Budget variance" count={data.alerts.counts.budgetVariance} icon={Target} href="/app/finance/budgeting">{data.alerts.budgetVariance.map(({plan,alert}) => <AlertRow key={`${plan.id}-${alert.category}`} href={`/app/finance/budgeting/${plan.id}`} primary={`${plan.currency} · ${alert.label}`} secondary={alert.status.replaceAll("_"," ")} trailing={formatMoney(alert.favorableVariance,plan.currency)} />)}</AlertCard>
      <AlertCard title="Payments pending confirmation" count={data.alerts.counts.pendingPayments} icon={Clock3} href="/app/finance/payments">{data.alerts.pendingPayments.map((p) => <AlertRow key={p.id} href={`/app/finance/payments/${p.id}`} primary={p.reference} secondary={`${p.client.firstName} ${p.client.lastName}`} trailing={formatMoney(Number(p.amount),p.currency)} />)}</AlertCard>
      <AlertCard title="Confirmed without proof" count={data.alerts.counts.missingPaymentProof} icon={ReceiptText} href="/app/finance/payments">{data.alerts.missingPaymentProof.map((p) => <AlertRow key={p.id} href={`/app/finance/payments/${p.id}`} primary={p.reference} secondary={`${p.client.firstName} ${p.client.lastName}`} trailing="Attach proof" />)}</AlertCard>
      <AlertCard title="Vendor bills overdue" count={data.alerts.counts.expenseOverdue} icon={CircleDollarSign} href="/app/finance/expenses">{data.alerts.expenseOverdue.map((e) => <AlertRow key={e.id} href={`/app/finance/expenses/${e.id}`} primary={e.expenseNumber} secondary={`${e.vendorName} · due ${e.dueDate?formatDate(new Date(e.dueDate)):"—"}`} trailing={formatMoney(expenseRemaining(e),e.currency)} />)}</AlertCard>
      <AlertCard title="Refunds needing review" count={data.alerts.counts.refundsToReview} icon={RefreshCw} href="/app/finance/refunds">{data.alerts.refundsToReview.map((r) => <AlertRow key={r.id} href={`/app/finance/refunds/${r.id}`} primary={r.refundNumber} secondary={`${r.client.firstName} ${r.client.lastName}`} trailing={r.status.replaceAll("_"," ")} />)}</AlertCard>
      <AlertCard title="Overdue refund installments" count={data.alerts.counts.overdueInstallments} icon={AlertTriangle} href="/app/finance/refunds">{data.alerts.overdueInstallments.map(({refund,installment}) => <AlertRow key={installment.id} href={`/app/finance/refunds/${refund.id}`} primary={`${refund.refundNumber} · #${installment.number}`} secondary={`Due ${formatDate(installment.dueDate)}`} trailing={formatMoney(Number(installment.amount),refund.currency)} />)}</AlertCard>
      <AlertCard title="Online payment exceptions" count={data.alerts.counts.onlineAttention} icon={WalletCards} href="/app/finance/online-payments">{data.alerts.onlineAttention.map((s) => <AlertRow key={s.id} href={`/app/finance/online-payments/${s.id}`} primary={s.provider.replaceAll("_"," ")} secondary={s.clientName} trailing={s.status} />)}</AlertCard>
      <AlertCard title="Open manual transfer orders" count={data.alerts.counts.manualOpen} icon={Banknote} href="/app/finance/manual-transfers">{data.alerts.manualOpen.map((o) => <AlertRow key={o.id} href={`/app/finance/manual-transfers/${o.id}`} primary={o.orderNumber} secondary={`${o.originCountry} → ${o.destinationCountry}`} trailing={o.status} />)}</AlertCard>
    </div>

    <Card><CardHeader><CardTitle>Upcoming refund installments</CardTitle></CardHeader><CardContent>{data.upcomingInstallments.length ? <div className="divide-y divide-line rounded-lg border border-line">{data.upcomingInstallments.map(({refund,installment}) => <Link key={installment.id} href={`/app/finance/refunds/${refund.id}`} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 hover:bg-surface"><div><div className="registry-id text-sm">{refund.refundNumber} · installment {installment.number}</div><div className="text-xs text-muted2">{refund.client.firstName} {refund.client.lastName} · due {formatDate(installment.dueDate)}</div></div><div className="font-medium">{formatMoney(Number(installment.amount),refund.currency)}</div></Link>)}</div> : <p className="text-sm text-muted2">No upcoming installments.</p>}</CardContent></Card>
    <p className="text-[11px] text-muted2">Generated {formatDateTime(data.generatedAt)}. Amounts are never combined across currencies.</p>
  </div>;
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof CircleDollarSign;label:string;value:string;hint:string}) { return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-3 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>; }
function Mini({label,value}:{label:string;value:string}) { return <div><div className="text-muted2">{label}</div><div className="mt-0.5 font-medium break-words">{value}</div></div>; }
function AlertCard({title,count,icon:Icon,href,children}:{title:string;count:number;icon:typeof AlertTriangle;href:string;children:React.ReactNode}) { return <Card><CardHeader><CardTitle><span className="flex items-center justify-between gap-2"><span className="flex items-center gap-2"><Icon className="h-4 w-4"/>{title}</span><span className="rounded-full bg-surface px-2 py-0.5 text-xs">{count}</span></span></CardTitle></CardHeader><CardContent className="space-y-2">{count ? children : <p className="text-xs text-muted2">No items.</p>}<Link href={href} className="inline-block pt-1 text-xs font-medium text-electric">Open module →</Link></CardContent></Card>; }
function AlertRow({href,primary,secondary,trailing}:{href:string;primary:string;secondary:string;trailing:string}) { return <Link href={href} className="flex items-center justify-between gap-3 rounded-lg border border-line px-3 py-2 hover:bg-surface"><div className="min-w-0"><div className="truncate text-xs font-medium">{primary}</div><div className="truncate text-[11px] text-muted2">{secondary}</div></div><div className="shrink-0 text-[11px] font-medium">{trailing}</div></Link>; }
