import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireUser, can } from "@/lib/auth";
import { getCaseFinanceOverview } from "@/lib/case-finance-overview";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge, Badge } from "@/components/ui/badge";
import { formatDate, formatMoney } from "@/lib/utils";
import { AlertTriangle, Banknote, CircleDollarSign, HandCoins, ReceiptText, TrendingUp, WalletCards } from "lucide-react";

export const dynamic="force-dynamic";

export default async function CaseFinancePage({params}:{params:Promise<{id:string}>|{id:string}}){
 const user=await requireUser();if(!can(user,"CASE_READ"))redirect("/app/forbidden");const {id}=await Promise.resolve(params);
 const finance=await getCaseFinanceOverview(id);if(!finance)notFound();const c=finance.case;
 const alertCount=finance.alerts.overallocatedPayments.length+finance.alerts.overdueInvoices.length+finance.alerts.pendingPayments.length+finance.alerts.pendingRefunds.length+finance.alerts.pendingExpenses.length;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/app/cases/${id}/dashboard`} className="text-sm text-muted2 hover:text-electric">← Case 360</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Case Finance</h1><StatusBadge status={c.status}/></div><p className="mt-1 text-sm text-muted2">{c.caseNumber} · {c.title} · {c.client.firstName} {c.client.lastName}</p></div><div className="flex flex-wrap gap-2"><Link href={`/app/cases/${id}/operations`}><Button variant="outline">Operations</Button></Link><Link href={`/app/clients/${c.clientId}/finance`}><Button variant="outline">Client Finance</Button></Link>{can(user,"PAYMENT_CREATE")?<Link href={`/app/finance/payments/new?caseId=${id}&clientId=${c.clientId}`}><Button variant="outline">Record payment</Button></Link>:null}<Link href={`/app/finance/invoices/new?caseId=${id}&clientId=${c.clientId}`}><Button variant="primary">New invoice</Button></Link></div></div>

  {alertCount?<div className="flex items-start gap-2 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><div><strong>Finance attention required.</strong> {finance.alerts.overdueInvoices.length?`${finance.alerts.overdueInvoices.length} overdue invoice(s). `:""}{finance.alerts.pendingPayments.length?`${finance.alerts.pendingPayments.length} pending payment(s). `:""}{finance.alerts.pendingRefunds.length?`${finance.alerts.pendingRefunds.length} refund(s) awaiting review. `:""}{finance.alerts.pendingExpenses.length?`${finance.alerts.pendingExpenses.length} expense(s) awaiting approval. `:""}{finance.alerts.overallocatedPayments.length?`${finance.alerts.overallocatedPayments.length} payment allocation anomaly(ies).`:""}</div></div>:null}

  {finance.summaries.length?finance.summaries.map(s=><Card key={s.currency}><CardHeader><div className="flex items-center gap-2"><CardTitle>{s.currency} Case financial position</CardTitle><Badge className="bg-surface text-ink">CASE BASIS</Badge></div></CardHeader><CardContent className="space-y-4">
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
    <Metric icon={WalletCards} label="Gross direct received" value={formatMoney(s.grossDirectReceived,s.currency)} sub="Payments assigned directly to this Case"/>
    <Metric icon={Banknote} label="Transfer fees" value={formatMoney(-s.transferFees,s.currency)} sub="Fees deducted from direct Case payments" negative={s.transferFees>0}/>
    <Metric icon={CircleDollarSign} label="Net direct received" value={formatMoney(s.netDirectReceived,s.currency)} sub="Gross minus transfer fees"/>
    <Metric icon={HandCoins} label="Applied to Case" value={formatMoney(s.appliedToCase,s.currency)} sub="Funds allocated to this Case's invoices"/>
    <Metric icon={ReceiptText} label="Billed" value={formatMoney(s.billed,s.currency)} sub={`Receivable ${formatMoney(s.receivable,s.currency)}`}/>
    <Metric icon={TrendingUp} label="Invoice paid" value={formatMoney(s.invoicePaid,s.currency)} sub="Recognized service cash revenue"/>
   </div>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">
    <Money label="Unapplied direct funds" value={s.unappliedDirectFunds} currency={s.currency}/><Money label="Refunds approved" value={-s.approvedRefunds} currency={s.currency}/><Money label="Refunds paid" value={-s.refundsPaid} currency={s.currency}/><Money label="Expenses paid" value={-s.expensePaid} currency={s.currency}/><Money label="Committed cost" value={-s.committedCost} currency={s.currency}/><Money label="Realized profit" value={s.realizedProfit} currency={s.currency} emphasize/><Money label="Forecast profit" value={s.forecastProfit} currency={s.currency} emphasize/>
   </div>
   <div className="flex flex-wrap gap-5 border-t border-line pt-3 text-xs text-muted2"><span>Realized margin: <strong className={s.realizedMarginPercent!=null&&s.realizedMarginPercent<0?"text-red-600":"text-ink"}>{s.realizedMarginPercent==null?"—":`${s.realizedMarginPercent.toFixed(2)}%`}</strong></span><span>Forecast margin: <strong className={s.forecastMarginPercent!=null&&s.forecastMarginPercent<0?"text-red-600":"text-ink"}>{s.forecastMarginPercent==null?"—":`${s.forecastMarginPercent.toFixed(2)}%`}</strong></span><span>Pending expense approval: <strong>{formatMoney(s.pendingApprovalCost,s.currency)}</strong></span></div>
  </CardContent></Card>):<Card><CardContent className="p-5 text-sm text-muted2">No financial activity is linked to this Case yet.</CardContent></Card>}

  <Card><CardHeader><div><CardTitle>Invoices</CardTitle><Link href={`/app/finance/invoices/new?caseId=${id}&clientId=${c.clientId}`} className="text-sm text-electric hover:underline">Create invoice</Link></div></CardHeader><CardContent className="overflow-x-auto p-0">{finance.invoices.length?<table className="w-full min-w-[850px] text-sm"><thead className="border-y border-line bg-surface/60 text-left text-xs uppercase tracking-wide text-muted2"><tr><th className="px-4 py-3">Invoice</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th>Due</th></tr></thead><tbody>{finance.invoices.map(({invoice,state})=><tr key={invoice.id} className="border-b border-line"><td className="px-4 py-3"><Link href={`/app/finance/invoices/${invoice.id}`} className="registry-id hover:text-electric">{invoice.invoiceNumber}</Link><div className="text-xs text-muted2">{invoice.title}</div></td><td>{formatMoney(invoice.total,invoice.currency)}</td><td className="text-emerald-700">{formatMoney(state.paid,invoice.currency)}</td><td className={state.balance>0?"font-medium":""}>{formatMoney(state.balance,invoice.currency)}</td><td><StatusBadge status={state.effectiveStatus}/></td><td>{formatDate(new Date(invoice.dueDate))}</td></tr>)}</tbody></table>:<p className="p-5 text-sm text-muted2">No invoice linked to this Case.</p>}</CardContent></Card>

  <Card><CardHeader><div><CardTitle>Payments & allocations</CardTitle>{can(user,"PAYMENT_CREATE")?<Link href={`/app/finance/payments/new?caseId=${id}&clientId=${c.clientId}`} className="text-sm text-electric hover:underline">Record payment</Link>:null}</div></CardHeader><CardContent className="overflow-x-auto p-0">{finance.payments.length?<table className="w-full min-w-[1100px] text-sm"><thead className="border-y border-line bg-surface/60 text-left text-xs uppercase tracking-wide text-muted2"><tr><th className="px-4 py-3">Reference</th><th>Gross</th><th>Fees</th><th>Net</th><th>Applied to Case</th><th>Allocated elsewhere</th><th>Unapplied</th><th>Source</th><th>Status</th></tr></thead><tbody>{finance.payments.map(p=><tr key={p.id} className="border-b border-line"><td className="px-4 py-3"><Link href={`/app/finance/payments/${p.id}`} className="registry-id hover:text-electric">{p.reference}</Link><div className="text-xs text-muted2">{formatDate(p.paidAt||p.createdAt)}</div></td><td>{formatMoney(p.gross,p.currency)}</td><td className={p.fee>0?"text-red-600":""}>{formatMoney(-p.fee,p.currency)}</td><td className="font-medium">{formatMoney(p.net,p.currency)}</td><td className="text-emerald-700">{formatMoney(p.appliedToCase,p.currency)}</td><td>{formatMoney(p.allocatedElsewhere,p.currency)}</td><td>{formatMoney(p.unapplied,p.currency)}</td><td>{p.directCasePayment?<Badge className="bg-blue-50 text-blue-700">DIRECT CASE</Badge>:<Badge className="bg-surface text-ink">INVOICE LINK</Badge>}</td><td><StatusBadge status={p.status}/>{p.overallocated>0?<div className="mt-1 text-xs text-red-600">Overallocated {formatMoney(p.overallocated,p.currency)}</div>:null}</td></tr>)}</tbody></table>:<p className="p-5 text-sm text-muted2">No payment or invoice allocation linked to this Case.</p>}</CardContent></Card>

  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader><div><CardTitle>Expenses</CardTitle><Link href={`/app/finance/expenses/new?caseId=${id}&clientId=${c.clientId}`} className="text-sm text-electric hover:underline">Record expense</Link></div></CardHeader><CardContent className="p-0">{finance.expenses.length?<ul className="divide-y divide-line">{finance.expenses.map(e=><li key={e.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><Link href={`/app/finance/expenses/${e.id}`} className="registry-id text-sm hover:text-electric">{e.expenseNumber}</Link><p className="text-sm font-medium">{e.vendorName}</p><p className="text-xs text-muted2">{e.category.replaceAll("_"," ")} · {e.description}</p></div><div className="text-right"><p className="font-medium">{formatMoney(e.amount,e.currency)}</p><p className="text-xs text-muted2">Paid {formatMoney(e.paidNumber,e.currency)} · remaining {formatMoney(e.remainingNumber,e.currency)}</p><StatusBadge status={e.effectiveStatus}/></div></li>)}</ul>:<p className="p-5 text-sm text-muted2">No expense linked to this Case.</p>}</CardContent></Card>
   <Card><CardHeader><div><CardTitle>Refunds</CardTitle><Link href={`/app/finance/refunds/new?clientId=${c.clientId}&caseId=${id}`} className="text-sm text-electric hover:underline">New refund</Link></div></CardHeader><CardContent className="p-0">{finance.refunds.length?<ul className="divide-y divide-line">{finance.refunds.map(r=><li key={r.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><Link href={`/app/finance/refunds/${r.id}`} className="registry-id text-sm hover:text-electric">{r.refundNumber}</Link><p className="text-xs text-muted2">{r.reason}</p></div><div className="text-right"><p className="font-medium">{formatMoney(r.amountNumber,r.currency)}</p><p className="text-xs text-muted2">Paid {formatMoney(r.paidNumber,r.currency)} · remaining {formatMoney(r.remainingNumber,r.currency)}</p><StatusBadge status={r.status}/></div></li>)}</ul>:<p className="p-5 text-sm text-muted2">No refund linked to this Case.</p>}</CardContent></Card>
  </div>

  <Card><CardHeader><CardTitle>Case finance rules</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm md:grid-cols-2"><Rule title="Net received">Gross payment minus transfer/payment fee. Fees are never treated as JUN revenue.</Rule><Rule title="Applied to Case">Only the portion allocated to invoices belonging to this Case. A shared client payment is not counted twice.</Rule><Rule title="Realized profit">Invoice cash actually paid for this Case minus refunds actually paid and expenses actually paid.</Rule><Rule title="Forecast profit">Case billed amount minus approved refunds and approved/committed costs.</Rule></CardContent></Card>
 </div>;
}
function Metric({icon:Icon,label,value,sub,negative=false}:{icon:any;label:string;value:string;sub:string;negative?:boolean}){return <div className="rounded-xl border border-line p-4"><Icon className="h-4 w-4 text-electric"/><p className="mt-3 text-xs text-muted2">{label}</p><p className={`mt-1 text-lg font-semibold ${negative?"text-red-600":""}`}>{value}</p><p className="mt-1 text-xs text-muted2">{sub}</p></div>}
function Money({label,value,currency,emphasize=false}:{label:string;value:number;currency:string;emphasize?:boolean}){return <div className={`rounded-lg border border-line p-3 ${emphasize?"bg-surface/40":""}`}><p className="text-xs uppercase tracking-wide text-muted2">{label}</p><p className={`mt-1 font-semibold ${value<0?"text-red-600":value>0&&emphasize?"text-emerald-700":""}`}>{formatMoney(value,currency)}</p></div>}
function Rule({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border border-line p-3"><p className="font-medium">{title}</p><p className="mt-1 text-xs text-muted2">{children}</p></div>}
