import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireUser, can } from "@/lib/auth";
import { getCaseAutomationPlan, listCaseAutomationRuns } from "@/lib/case-automation";
import { updateCaseAutomationSettings, runCaseSafeAutomation } from "@/services/case-automation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { formatDateTime } from "@/lib/utils";
import { Bot, CheckCircle2, Clock3, ShieldCheck, Siren, Workflow } from "lucide-react";

export const dynamic="force-dynamic";
const severityClass:Record<string,string>={LOW:"bg-emerald-100 text-emerald-800",MEDIUM:"bg-amber-100 text-amber-800",HIGH:"bg-orange-100 text-orange-800",CRITICAL:"bg-red-100 text-red-800"};

export default async function CaseAutomationPage({params}:{params:Promise<{id:string}>|{id:string}}){
 const user=await requireUser();if(!can(user,"CASE_READ"))redirect("/app/forbidden");const {id}=await Promise.resolve(params);
 const [plan,runs]=await Promise.all([getCaseAutomationPlan(id),listCaseAutomationRuns(id)]);if(!plan)notFound();
 const {intelligence,config,candidates,targetPriority}=plan;const c=intelligence.case;const creatable=candidates.filter(x=>!x.alreadyExists).length;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/app/cases/${id}/intelligence`} className="text-sm text-muted2 hover:text-electric">← Case Intelligence</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Case Automation & Escalation</h1><StatusBadge status={c.status}/><Badge className={severityClass[intelligence.riskLevel]}>{intelligence.riskLevel} RISK</Badge></div><p className="mt-1 text-sm text-muted2">{c.caseNumber} · safe, auditable automation with human control over financial and closure actions</p></div>{can(user,"CASE_UPDATE")?<form action={runCaseSafeAutomation.bind(null,id)}><Button variant="primary">Run safe automation</Button></form>:null}</div>

  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Bot} label="Automation" value={config.enabled?"ENABLED":"DISABLED"} sub="per Case configuration"/><Metric icon={Siren} label="Risk" value={`${intelligence.score}/100`} sub={intelligence.riskLevel}/><Metric icon={Workflow} label="New follow-ups" value={String(creatable)} sub={`${candidates.length-creatable} duplicate(s) skipped`}/><Metric icon={Clock3} label="Automation runs" value={String(runs.length)} sub="recent audit history"/><Metric icon={ShieldCheck} label="Target priority" value={targetPriority} sub={`current ${c.priority}`}/></div>

  <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
   <Card><CardHeader><div><CardTitle>Safe automation policy</CardTitle><p className="mt-1 text-xs text-muted2">Choose which reversible operational actions JUN may execute.</p></div></CardHeader><CardContent>{can(user,"CASE_UPDATE")?<form action={updateCaseAutomationSettings.bind(null,id)} className="space-y-4"><Toggle name="enabled" checked={config.enabled} title="Enable Case automation" text="Allows Safe Automation to run on this active Case."/><Toggle name="createFollowUpTasks" checked={config.createFollowUpTasks} title="Create follow-up tasks" text="Create deduplicated tasks from the highest-priority Intelligence actions."/><Toggle name="escalatePriority" checked={config.escalatePriority} title="Escalate Case priority" text="May raise LOW/MEDIUM/HIGH to the minimum priority required by the risk level. It never lowers priority."/><Toggle name="notifyOwner" checked={config.notifyOwner} title="Notify Case owner" text="Notify the owner when automation assigns a new follow-up task."/><Button variant="outline">Save automation settings</Button></form>:<p className="text-sm text-muted2">Read only.</p>}</CardContent></Card>

   <Card><CardHeader><div><CardTitle>Planned next actions</CardTitle><p className="mt-1 text-xs text-muted2">Preview before running. Existing active automation tasks are never duplicated.</p></div></CardHeader><CardContent className="p-0">{candidates.length?<div className="divide-y divide-line">{candidates.map(x=><div key={x.insight.id} className="grid gap-3 px-5 py-4 md:grid-cols-[110px_minmax(0,1fr)_130px]"><div><Badge className={severityClass[x.insight.severity]}>{x.insight.severity}</Badge></div><div><p className="font-medium">{x.insight.action}</p><p className="mt-1 text-xs text-muted2">{x.insight.area} · {x.insight.title}</p><p className="mt-2 text-sm text-muted2">{x.insight.detail}</p></div><div className="text-right"><Badge className={x.alreadyExists?"bg-gray-100 text-gray-700":"bg-emerald-100 text-emerald-800"}>{x.alreadyExists?"ALREADY ACTIVE":"WILL CREATE"}</Badge><p className="mt-2 text-xs text-muted2">{x.priority}<br/>{x.dueDate.toISOString().slice(0,10)}</p></div></div>)}</div>:<p className="p-5 text-sm text-muted2">No follow-up action is currently required.</p>}</CardContent></Card>
  </div>

  <Card><CardHeader><div><CardTitle>Protected actions</CardTitle><p className="mt-1 text-xs text-muted2">Safe Automation is intentionally prohibited from executing these actions.</p></div></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Protected>Confirm or alter payments</Protected><Protected>Approve or mark refunds paid</Protected><Protected>Approve/pay expenses or alter invoices</Protected><Protected>Finalize documents or close the Case</Protected></CardContent></Card>

  <Card><CardHeader><div><CardTitle>Automation history</CardTitle><p className="mt-1 text-xs text-muted2">Every run is retained with risk level, created tasks and priority escalation.</p></div></CardHeader><CardContent className="p-0">{runs.length?<div className="divide-y divide-line">{runs.map(run=><div key={run.id} className="grid gap-3 px-5 py-4 md:grid-cols-[170px_120px_180px_minmax(0,1fr)]"><div className="text-xs text-muted2">{formatDateTime(new Date(run.ranAt))}</div><div><Badge className={severityClass[run.riskLevel]}>{run.riskLevel} · {run.riskScore}</Badge></div><div className="text-sm"><strong>{run.tasksCreated}</strong> created · {run.tasksSkipped} skipped<br/><span className="text-xs text-muted2">Priority {run.priorityBefore} → {run.priorityAfter}</span></div><div className="text-xs text-muted2">{run.actions.length?run.actions.map((a,i)=><div key={i}>• {a}</div>):"No mutation was required."}</div></div>)}</div>:<p className="p-5 text-sm text-muted2">Safe Automation has not been run on this Case yet.</p>}</CardContent></Card>
 </div>;
}
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub:string}){return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-electric"/><p className="mt-3 text-xs text-muted2">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p><p className="mt-1 text-xs text-muted2">{sub}</p></CardContent></Card>}
function Toggle({name,checked,title,text}:{name:string;checked:boolean;title:string;text:string}){return <label className="flex items-start gap-3 rounded-xl border border-line p-3"><input type="checkbox" name={name} defaultChecked={checked} className="mt-1"/><span><span className="block text-sm font-medium">{title}</span><span className="mt-1 block text-xs text-muted2">{text}</span></span></label>}
function Protected({children}:{children:React.ReactNode}){return <div className="flex items-start gap-2 rounded-xl border border-line p-3 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/><span>{children}</span></div>}
