import Link from "next/link";
import { redirect } from "next/navigation";
import { requireUser, can } from "@/lib/auth";
import { getMailAnalytics, type MailAnalyticsPeriod } from "@/lib/mail-analytics";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/input";

export const dynamic="force-dynamic";
function Metric({label,value,sub}:{label:string;value:string|number;sub?:string}){return <div className="rounded-xl border border-line bg-white p-4"><p className="text-xs text-muted2">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p>{sub?<p className="mt-1 text-xs text-muted2">{sub}</p>:null}</div>}
function Bars({title,rows}:{title:string;rows:{name:string;count:number}[]}){const max=Math.max(1,...rows.map(r=>r.count));return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length?rows.map(r=><div key={r.name}><div className="mb-1 flex justify-between text-xs"><span>{r.name.replaceAll("_"," ")}</span><span>{r.count}</span></div><div className="h-2 overflow-hidden rounded bg-surface"><div className="h-full bg-electric" style={{width:`${Math.max(3,Math.round(r.count/max*100))}%`}}/></div></div>):<p className="text-sm text-muted2">No data in this period.</p>}</CardContent></Card>}
export default async function MailAnalyticsPage({searchParams}:{searchParams:{period?:string}}){
 const user=await requireUser();if(!can(user,"EMAIL_READ"))redirect("/app/forbidden");
 const raw=Number(searchParams.period);const period:MailAnalyticsPeriod=raw===7||raw===90||raw===365?raw:30;
 const a=await getMailAnalytics(period);
 const responseLabel=a.averageRecordedResponseMinutes===null?"—":a.averageRecordedResponseMinutes<60?`${a.averageRecordedResponseMinutes} min`:`${(a.averageRecordedResponseMinutes/60).toFixed(1)} h`;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Mail Analytics</h1><p className="mt-1 text-sm text-muted2">Operational reporting for JUN Mail. Period starts {new Date(a.since).toLocaleDateString()}.</p></div><div className="flex flex-wrap gap-2"><Link href="/app/mail/search"><Button variant="secondary">Advanced Search</Button></Link><Link href="/app/mail/operations"><Button variant="secondary">Operations & SLA</Button></Link><Link href="/app/mail"><Button variant="outline">Back to Mail</Button></Link></div></div>
  <form className="flex items-end gap-2"><div><p className="mb-1 text-xs text-muted2">Reporting period</p><Select name="period" defaultValue={String(period)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option></Select></div><Button variant="outline">Apply</Button></form>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Mail threads" value={a.totalThreads}/><Metric label="Needs reply" value={a.needsReply}/><Metric label="SLA overdue" value={a.overdue} sub={`${a.slaOverdueRate}% of reply workload`}/><Metric label="Due soon" value={a.dueSoon}/><Metric label="Assignment rate" value={`${a.assignmentRate}%`} sub={`${a.unassigned} unassigned`}/><Metric label="AI review" value={a.aiReview}/></div>
  <div className="grid gap-3 md:grid-cols-4"><Metric label="Recorded avg response" value={responseLabel} sub={`${a.measuredResponses} measurable thread(s)`}/><Metric label="Recorded send events" value={a.sendEvents}/><Metric label="AI draft events" value={a.aiDraftEvents} sub={`${a.aiAssistedSendRatio}% vs recorded sends`}/><Metric label="Safe automations" value={a.safeAutomations}/></div>
  <Card><CardHeader><CardTitle>AI Approval performance</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-5"><Metric label="Submitted" value={a.approvals.submitted}/><Metric label="Approved" value={a.approvals.approved}/><Metric label="Rejected" value={a.approvals.rejected}/><Metric label="Sent after approval" value={a.approvals.sent}/><Metric label="Approval rate" value={`${a.approvals.approvalRate}%`}/></div></CardContent></Card>
  <div className="grid gap-4 xl:grid-cols-3"><Bars title="Volume by category" rows={a.categories}/><Bars title="Volume by department" rows={a.departments}/><Bars title="Volume by priority" rows={a.priorities}/></div>
  <Card><CardHeader><CardTitle>Owner workload</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-muted2"><tr><th className="pb-2">Owner</th><th className="pb-2">Department</th><th className="pb-2">Threads</th><th className="pb-2">Needs reply</th><th className="pb-2">Overdue</th></tr></thead><tbody>{a.owners.map(o=><tr key={o.id} className="border-t border-line"><td className="py-3 font-medium">{o.name}</td><td>{o.department.replaceAll("_"," ")}</td><td>{o.threads}</td><td>{o.needsReply}</td><td className={o.overdue?"font-semibold text-red-700":""}>{o.overdue}</td></tr>)}{!a.owners.length?<tr><td colSpan={5} className="py-5 text-muted2">No assigned mail workload in this period.</td></tr>:null}</tbody></table></div></CardContent></Card>
  <Card><CardContent className="p-4 text-xs text-muted2"><strong className="text-ink">Metric note.</strong> “Recorded avg response” is calculated only when JUN has a persisted MailThread and a corresponding recorded email-send audit event. It is not presented as complete Gmail response-time history because individual Gmail messages are not yet persisted locally.</CardContent></Card>
 </div>;
}
