import Link from "next/link";
import { redirect } from "next/navigation";
import { requireUser, can } from "@/lib/auth";
import { GENERAL_DOCUMENT_TEMPLATE, getWhatsAppConfig } from "@/lib/whatsapp";
import { saveWhatsAppSettings } from "@/services/whatsapp";
import { PageHeader } from "@/components/app/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";

export const dynamic="force-dynamic";

export default async function WhatsAppSettingsPage(){
 const user=await requireUser();if(!can(user,"SETTINGS_MANAGE"))redirect("/app/forbidden");
 const cfg=await getWhatsAppConfig();
 return <div className="max-w-4xl">
  <PageHeader title="WhatsApp Business" subtitle="Connect JUN Business Hub to the official Meta WhatsApp Cloud API."/>
  <div className="mb-5"><Link href="/app/settings" className="text-sm text-electric hover:underline">← Back to Settings</Link></div>
  <form action={saveWhatsAppSettings} className="space-y-5">
   <Card><CardHeader><CardTitle>Meta connection</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2">
    <Field label="Phone Number ID"><Input name="phoneNumberId" defaultValue={cfg.phoneNumberId} placeholder="Meta Phone Number ID" required/></Field>
    <Field label="WhatsApp Business Account ID"><Input name="businessAccountId" defaultValue={cfg.businessAccountId} placeholder="WABA ID"/></Field>
    <Field label="Connected phone"><Input name="displayPhone" defaultValue={cfg.displayPhone} placeholder="+52..."/></Field>
    <Field label="Graph API version"><Input name="graphVersion" defaultValue={cfg.graphVersion||"v23.0"}/></Field>
    <div className="sm:col-span-2"><Field label={cfg.tokenConfigured?"Permanent Access Token — already configured (leave blank to keep it)":"Permanent Access Token"}><Input name="accessToken" type="password" placeholder={cfg.tokenConfigured?"••••••••••••":"Paste Meta permanent token"}/></Field><p className="mt-2 text-xs text-muted2">The token is encrypted before being stored. JUN never displays it again.</p></div>
   </CardContent></Card>
   <Card><CardHeader><CardTitle>Webhook</CardTitle></CardHeader><CardContent className="space-y-5">
    <Field label="Callback URL"><Input value="https://juncreatif.org/api/webhooks/whatsapp" readOnly/></Field>
    <Field label={cfg.webhookVerifyTokenConfigured?"Webhook Verify Token — already configured (leave blank to keep it)":"Webhook Verify Token"}><Input name="webhookVerifyToken" type="password" placeholder={cfg.webhookVerifyTokenConfigured?"••••••••••••":"Create a private verification token"}/></Field>
    <p className="text-xs text-muted2">In Meta Webhooks, use the Callback URL above and paste the exact same Verify Token that you enter here.</p>
   </CardContent></Card>
   <Card><CardHeader><CardTitle>General document template</CardTitle></CardHeader><CardContent className="space-y-5">
    <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950">
     <p className="font-semibold">Create this single template in Meta WhatsApp Manager</p>
     <div className="mt-3 grid gap-2 text-xs">
      <p><strong>Name:</strong> {GENERAL_DOCUMENT_TEMPLATE}</p>
      <p><strong>Category:</strong> Utility</p>
      <p><strong>Language:</strong> French (fr)</p>
      <p><strong>Header:</strong> Document · dynamic</p>
      <div><strong>Body:</strong><pre className="mt-1 whitespace-pre-wrap rounded-lg border border-emerald-200 bg-white p-3 text-xs">Bonjour {'{{1}}'},

Votre document {'{{2}}'} est maintenant disponible.

Référence : {'{{3}}'}

JUN CREATIF AND TRAVEL LLC</pre></div>
      <p><strong>Sample values:</strong> {{1: "Ruth Joseph", 2: "Official Payment Receipt", 3: "REC-2026-001"} ? "" : ""}</p>
     </div>
    </div>
    <div className="grid gap-5 sm:grid-cols-2">
     <Field label="Approved document template"><Input name="defaultTemplate" defaultValue={cfg.defaultTemplate} placeholder={GENERAL_DOCUMENT_TEMPLATE}/></Field>
     <Field label="Template language code"><Input name="languageCode" defaultValue={cfg.languageCode||"fr"} placeholder="fr"/></Field>
    </div>
    <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900">After Meta marks the template as <strong>Approved</strong>, enter its exact name above. JUN will automatically fill variable 1 with the client name, variable 2 with the document title/type, variable 3 with the document reference, and attach the generated PDF as the template's Document header.</div>
    <p className="text-xs text-muted2">The same template can therefore be reused for receipts, invoices, statements, contracts and official PDF documents generated by JUN.</p>
   </CardContent></Card>
   <div className="flex items-center gap-3"><Button type="submit" variant="primary">Save WhatsApp connection</Button><span className={`text-sm ${cfg.tokenConfigured&&cfg.phoneNumberId?"text-emerald-600":"text-amber-600"}`}>{cfg.tokenConfigured&&cfg.phoneNumberId?"Configuration saved":"Configuration incomplete"}</span></div>
  </form>
 </div>;
}
