"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { assertPermission } from "@/lib/auth";
import { assertMailboxAccess } from "@/lib/mail-security";
import { audit } from "@/lib/audit";
import { computeMailDraftHash, getMailApproval, saveMailApproval } from "@/lib/mail-approval";
function back(threadId:string,msg:string,error=false):never{redirect(`/app/mail?folder=DRAFTS&thread=${threadId}&${error?"toast_error":"toast"}=${encodeURIComponent(msg)}`)}
export async function submitMailForApproval(threadId:string){const user=await assertPermission("EMAIL_DRAFT"),thread=await prisma.mailThread.findUnique({where:{id:threadId},select:{id:true,aiDraft:true,aiLevel:true,mailAccountId:true}});if(!thread?.aiDraft)back(threadId,"Draft not found",true);try{await assertMailboxAccess(user,thread.mailAccountId)}catch{back(threadId,"Mailbox access denied",true)}const draftHash=await computeMailDraftHash(threadId),record={threadId,status:"PENDING" as const,submittedAt:new Date().toISOString(),submittedById:user.id,draftHash};await saveMailApproval(record);await prisma.mailThread.update({where:{id:threadId},data:{requiresAttention:true}});await audit({userId:user.id,action:"EMAIL_APPROVAL_SUBMITTED",resourceType:"MailThread",resourceId:threadId,after:{aiLevel:thread.aiLevel,draftHash}});revalidatePath("/app/mail");revalidatePath("/app/mail/approvals");back(threadId,"Email submitted for approval")}
export async function decideMailApproval(threadId:string,decision:"APPROVE"|"REJECT",formData:FormData){const user=await assertPermission("AI_APPROVE"),thread=await prisma.mailThread.findUnique({where:{id:threadId},select:{id:true,aiDraft:true,aiLevel:true,mailAccountId:true}});if(!thread?.aiDraft)redirect("/app/mail/approvals?toast_error=Draft not found");try{await assertMailboxAccess(user,thread.mailAccountId)}catch{redirect("/app/mail/approvals?toast_error=Mailbox access denied")}const current=await getMailApproval(threadId);if(!current||current.status!=="PENDING")redirect("/app/mail/approvals?toast_error=Approval request is no longer pending");const hash=await computeMailDraftHash(threadId);if(current.draftHash!==hash)redirect("/app/mail/approvals?toast_error=Draft changed after submission — submit it again");const note=String(formData.get("note")||"").trim().slice(0,2000),now=new Date().toISOString(),next=decision==="APPROVE"?{...current,status:"APPROVED" as const,approvedAt:now,approvedById:user.id,decisionNote:note}:{...current,status:"REJECTED" as const,rejectedAt:now,rejectedById:user.id,decisionNote:note};await saveMailApproval(next);await prisma.mailThread.update({where:{id:threadId},data:{requiresAttention:decision!=="APPROVE"}});await audit({userId:user.id,action:decision==="APPROVE"?"EMAIL_APPROVAL_APPROVED":"EMAIL_APPROVAL_REJECTED",resourceType:"MailThread",resourceId:threadId,after:{aiLevel:thread.aiLevel,draftHash:hash,note}});revalidatePath("/app/mail");revalidatePath("/app/mail/approvals");redirect(`/app/mail/approvals?toast=${encodeURIComponent(decision==="APPROVE"?"Email approved":"Email rejected")}`)}
