"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { assertPermission, type CurrentUser } from "@/lib/auth";
import { audit } from "@/lib/audit";
import { classifyEmailAILevel } from "@/services/ai";
import { emptyToNull } from "@/lib/validation";
import { getMailComposeMeta, parseEmailList, saveMailComposeMeta, type MailComposeMode } from "@/lib/mail-compose-meta";
import { assertMailboxAccess } from "@/lib/mail-security";

const MODES:MailComposeMode[]=["NEW","REPLY","REPLY_ALL","FORWARD"];
function bad(message:string,mailbox="ALL",draftId?:string):never{const p=new URLSearchParams({mailbox,toast_error:message});if(draftId)p.set("draft",draftId);redirect(`/app/mail/compose?${p.toString()}`);}
function values(formData:FormData){const mailAccountId=String(formData.get("mailAccountId")||"").trim(),subject=String(formData.get("subject")||"").trim().slice(0,200),body=String(formData.get("body")||"").trim().slice(0,30000),to=parseEmailList(String(formData.get("to")||"")),cc=parseEmailList(String(formData.get("cc")||"")),bcc=parseEmailList(String(formData.get("bcc")||"")),clientId=String(formData.get("clientId")||"").trim(),sourceThreadId=String(formData.get("sourceThreadId")||"").trim()||null,sourceGmailMessageId=String(formData.get("sourceGmailMessageId")||"").trim()||null,modeRaw=String(formData.get("mode")||"NEW").toUpperCase() as MailComposeMode,mode=MODES.includes(modeRaw)?modeRaw:"NEW",signatureId=String(formData.get("signatureId")||"").trim()||null,templateId=String(formData.get("templateId")||"").trim()||null,attachmentFileIds=[...new Set(formData.getAll("attachmentFileIds").map(v=>String(v)).filter(Boolean))].slice(0,10);return{mailAccountId,subject,body,to,cc,bcc,clientId,sourceThreadId,sourceGmailMessageId,mode,signatureId,templateId,attachmentFileIds};}
async function validate(user:CurrentUser,d:ReturnType<typeof values>,draftId?:string){if(!d.mailAccountId)bad("Select a mailbox","ALL",draftId);try{await assertMailboxAccess(user,d.mailAccountId);}catch{bad("You do not have access to this mailbox",d.mailAccountId,draftId);}if(!d.to.length)bad("Enter at least one valid recipient",d.mailAccountId,draftId);if(!d.subject||!d.body)bad("Subject and message are required",d.mailAccountId,draftId);const account=await prisma.mailAccount.findFirst({where:{id:d.mailAccountId,OR:[{accessTokenEnc:{not:null}},{refreshTokenEnc:{not:null}}]},select:{id:true,email:true}});if(!account)bad("Selected mailbox is not connected",d.mailAccountId,draftId);if(d.attachmentFileIds.length){await assertPermission("FILE_READ");const allowed=await prisma.file.count({where:{id:{in:d.attachmentFileIds},isVault:false,archivedAt:null}});if(allowed!==d.attachmentFileIds.length)bad("One or more selected attachments are unavailable",d.mailAccountId,draftId);}let source=null as null|{id:string;mailAccountId:string;clientId:string|null;gmailThreadId:string};if(d.sourceThreadId){source=await prisma.mailThread.findFirst({where:{id:d.sourceThreadId,mailAccountId:d.mailAccountId},select:{id:true,mailAccountId:true,clientId:true,gmailThreadId:true}});if(!source)bad("Source conversation not found in this mailbox",d.mailAccountId,draftId);}return{account,source};}

export async function saveProfessionalMailDraft(formData:FormData){
 const user=await assertPermission("EMAIL_DRAFT"),d=values(formData),{account,source}=await validate(user,d),aiLevel=await classifyEmailAILevel(d.subject,d.body);
 const thread=await prisma.mailThread.create({data:{gmailThreadId:`local-draft-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,mailAccountId:d.mailAccountId,clientId:emptyToNull(d.clientId)||source?.clientId||null,subject:d.subject,snippet:d.body.slice(0,500),fromEmail:account.email,toEmails:d.to,aiLevel,aiSummary:aiLevel==="BLOCKED"?"Sensitive topic — manual handling required":aiLevel==="AUTO"?"Routine message":"Needs human approval",aiDraft:d.body,requiresAttention:aiLevel!=="AUTO"}});
 await saveMailComposeMeta({threadId:thread.id,mode:d.mode,to:d.to,cc:d.cc,bcc:d.bcc,attachmentFileIds:d.attachmentFileIds,sourceThreadId:source?.id??null,sourceGmailMessageId:d.sourceGmailMessageId,signatureId:d.signatureId,templateId:d.templateId,updatedAt:new Date().toISOString()});
 await audit({userId:user.id,action:"EMAIL_PROFESSIONAL_DRAFT_CREATE",resourceType:"MailThread",resourceId:thread.id,after:{mailAccountId:d.mailAccountId,mailbox:account.email,mode:d.mode,toCount:d.to.length,ccCount:d.cc.length,bccCount:d.bcc.length,attachments:d.attachmentFileIds.length,sourceThreadId:source?.id??null,aiLevel}});
 revalidatePath("/app/mail");redirect(`/app/mail/compose?mailbox=${encodeURIComponent(d.mailAccountId)}&draft=${thread.id}&toast=${encodeURIComponent("Professional draft saved")}`);
}

export async function updateProfessionalMailDraft(threadId:string,formData:FormData){
 const user=await assertPermission("EMAIL_DRAFT"),existing=await prisma.mailThread.findUnique({where:{id:threadId},select:{id:true,mailAccountId:true,aiDraft:true}});if(!existing?.aiDraft)bad("Draft not found");try{await assertMailboxAccess(user,existing.mailAccountId);}catch{bad("You do not have access to this mailbox",existing.mailAccountId,threadId);}const meta=await getMailComposeMeta(threadId);if(!meta)bad("Professional draft metadata not found",existing.mailAccountId,threadId);
 const d=values(formData);if(d.mailAccountId!==existing.mailAccountId)bad("A saved draft cannot be moved to another mailbox",existing.mailAccountId,threadId);const{source}=await validate(user,d,threadId),aiLevel=await classifyEmailAILevel(d.subject,d.body);
 await prisma.mailThread.update({where:{id:threadId},data:{clientId:emptyToNull(d.clientId)||source?.clientId||null,subject:d.subject,snippet:d.body.slice(0,500),toEmails:d.to,aiDraft:d.body,aiLevel,requiresAttention:aiLevel!=="AUTO",aiSummary:aiLevel==="BLOCKED"?"Sensitive topic — manual handling required":aiLevel==="AUTO"?"Routine message":"Needs human approval"}});
 await saveMailComposeMeta({threadId,mode:d.mode,to:d.to,cc:d.cc,bcc:d.bcc,attachmentFileIds:d.attachmentFileIds,sourceThreadId:source?.id??null,sourceGmailMessageId:d.sourceGmailMessageId,signatureId:d.signatureId,templateId:d.templateId,updatedAt:new Date().toISOString()});
 await audit({userId:user.id,action:"EMAIL_PROFESSIONAL_DRAFT_EDIT",resourceType:"MailThread",resourceId:threadId,after:{mode:d.mode,toCount:d.to.length,ccCount:d.cc.length,bccCount:d.bcc.length,attachments:d.attachmentFileIds.length,aiLevel}});revalidatePath("/app/mail");redirect(`/app/mail/compose?mailbox=${encodeURIComponent(existing.mailAccountId)}&draft=${threadId}&toast=${encodeURIComponent("Draft updated")}`);
}
