"use server";
import { randomUUID } from "crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { assertPermission } from "@/lib/auth";
import { audit } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { deleteMailSignature, deleteMailTemplate, listMailSignatures, saveMailSignature, saveMailTemplate } from "@/lib/mail-compose-meta";

const path=(msg:string,error=false)=>`/app/settings/email/composer?${error?"toast_error":"toast"}=${encodeURIComponent(msg)}`;
export async function createMailSignature(formData:FormData){const user=await assertPermission("SETTINGS_MANAGE"),mailAccountId=String(formData.get("mailAccountId")||""),name=String(formData.get("name")||"").trim().slice(0,80),body=String(formData.get("body")||"").trim().slice(0,5000),isDefault=formData.get("isDefault")==="on";if(!mailAccountId||!name||!body)redirect(path("Mailbox, name and signature are required",true));const account=await prisma.mailAccount.findUnique({where:{id:mailAccountId},select:{id:true,email:true}});if(!account)redirect(path("Mailbox not found",true));if(isDefault){for(const s of await listMailSignatures(mailAccountId))if(s.isDefault)await saveMailSignature({...s,isDefault:false,updatedAt:new Date().toISOString()});}const sig={id:randomUUID(),mailAccountId,name,body,isDefault,updatedAt:new Date().toISOString()};await saveMailSignature(sig);await audit({userId:user.id,action:"MAIL_SIGNATURE_CREATE",resourceType:"MailAccount",resourceId:mailAccountId,after:{signatureId:sig.id,name,isDefault}});revalidatePath("/app/settings/email/composer");redirect(path("Signature saved"));}
export async function removeMailSignature(id:string){const user=await assertPermission("SETTINGS_MANAGE");await deleteMailSignature(id);await audit({userId:user.id,action:"MAIL_SIGNATURE_DELETE",resourceType:"MailSignature",resourceId:id});revalidatePath("/app/settings/email/composer");redirect(path("Signature deleted"));}
export async function createMailTemplate(formData:FormData){const user=await assertPermission("SETTINGS_MANAGE"),name=String(formData.get("name")||"").trim().slice(0,100),subject=String(formData.get("subject")||"").trim().slice(0,200),body=String(formData.get("body")||"").trim().slice(0,10000),category=String(formData.get("category")||"GENERAL").trim().slice(0,60)||"GENERAL";if(!name||!body)redirect(path("Template name and body are required",true));const t={id:randomUUID(),name,subject,body,category,updatedAt:new Date().toISOString()};await saveMailTemplate(t);await audit({userId:user.id,action:"MAIL_TEMPLATE_CREATE",resourceType:"MailTemplate",resourceId:t.id,after:{name,category}});revalidatePath("/app/settings/email/composer");redirect(path("Template saved"));}
export async function removeMailTemplate(id:string){const user=await assertPermission("SETTINGS_MANAGE");await deleteMailTemplate(id);await audit({userId:user.id,action:"MAIL_TEMPLATE_DELETE",resourceType:"MailTemplate",resourceId:id});revalidatePath("/app/settings/email/composer");redirect(path("Template deleted"));}
