import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getCompanyFinanceConsolidation, syncCompanyFinanceState } from "@/lib/company-funds-finance-sync";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { mapFinanceAccountToTreasuryAction, setOutgoingTreasuryAccountAction, syncCompanyFinanceNowAction } from "@/services/company-funds-finance-sync";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowDownToLine, ArrowUpFromLine, CircleDollarSign, Link2, RefreshCw, ShieldCheck, WalletCards } from "lucide-react";

export const dynamic="force-dynamic";
export default async function ConsolidationPage(){
  const user=await requireUser();if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
  await syncCompanyFinanceState().catch(()=>null);
  const data=await getCompanyFinanceConsolidation();
  const currencies=[...new Set([...data.byCurrency.map(x=>x.currency),...data.treasuryAccounts.map(a=>a.currency)])].sort();
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-muted2">Super Admin · Consolidation centrale</p><h1 className="mt-1 text-3xl font-semibold">Finance JUN ↔ Fonds de l’entreprise</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Une seule source de vérité : paiements confirmés, remboursements payés, dépenses payées et frais de paiement sont consolidés automatiquement dans la trésorerie stratégique.</p></div><form action={syncCompanyFinanceNowAction}><button className="rounded-lg bg-ink px-4 py-2 text-sm font-medium text-white"><RefreshCw className="mr-2 inline h-4 w-4"/>Synchroniser maintenant</button></form></div>

    <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><ShieldCheck className="mr-2 inline h-5 w-5"/><strong>Synchronisation automatique active.</strong> Cette page recalcule la consolidation à partir des données Finance JUN. Dernière synchronisation enregistrée : {data.state.lastSyncedAt?formatDateTime(data.state.lastSyncedAt):"jamais"}. {data.unmappedEntries>0?<span className="ml-2 font-semibold text-amber-700">{data.unmappedEntries} flux ne sont pas encore affectés à un compte de trésorerie.</span>:<span className="ml-2 font-semibold">Tous les flux sont affectés.</span>}</div>

    <div className="grid gap-3 md:grid-cols-4"><Metric icon={CircleDollarSign} label="Flux consolidés" value={String(data.entries.length)} hint="Finance JUN réel"/><Metric icon={ArrowDownToLine} label="Comptes Finance non mappés" value={String(data.unmappedFinanceAccounts.length)} hint="Encaissements à associer"/><Metric icon={ArrowUpFromLine} label="Flux sans compte" value={String(data.unmappedEntries)} hint="À compléter"/><Metric icon={WalletCards} label="Comptes Trésorerie" value={String(data.treasuryAccounts.filter(a=>a.active).length)} hint="Fonds de l’entreprise"/></div>

    <Card><CardHeader><CardTitle>Résultat consolidé par devise</CardTitle></CardHeader><CardContent>{data.byCurrency.length?<div className="grid gap-3 lg:grid-cols-2">{data.byCurrency.map(r=><div key={r.currency} className="rounded-xl border border-line p-4"><div className="mb-3 flex items-center justify-between"><span className="text-lg font-semibold">{r.currency}</span><span className={`rounded-full px-2 py-1 text-xs font-semibold ${r.net>=0?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>Net {formatMoney(r.net,r.currency)}</span></div><div className="grid grid-cols-2 gap-3"><Kpi label="Paiements reçus" value={formatMoney(r.received,r.currency)}/><Kpi label="Remboursements payés" value={formatMoney(r.refunds,r.currency)}/><Kpi label="Dépenses payées" value={formatMoney(r.expenses,r.currency)}/><Kpi label="Frais de paiement" value={formatMoney(r.fees,r.currency)}/></div><p className="mt-3 text-xs text-muted2">{r.entryCount} écritures consolidées.</p></div>)}</div>:<p className="text-sm text-muted2">Aucun flux financier confirmé pour le moment.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Link2 className="h-5 w-5"/>Association comptes Finance → Trésorerie</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-muted2">Associez chaque compte de réception utilisé dans Finance JUN au vrai compte de l’entreprise. Les paiements confirmés seront alors attribués au bon compte de trésorerie pour le contrôle et la réconciliation.</p>{data.financeAccounts.length?<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Compte Finance</th><th className="p-2">Méthode</th><th className="p-2">Devise</th><th className="p-2">Compte Fonds de l’entreprise</th></tr></thead><tbody>{data.financeAccounts.map(f=>{const current=data.settings.mappings.find(m=>m.financeAccountId===f.id)?.treasuryAccountId||"";return <tr key={f.id} className="border-b border-line/70"><td className="p-2 font-medium">{f.label}<div className="text-[10px] text-muted2">{f.accountDescriptor||f.receiverName}</div></td><td className="p-2">{f.method.replaceAll("_"," ")}</td><td className="p-2">{f.currency}</td><td className="p-2"><form action={mapFinanceAccountToTreasuryAction.bind(null,f.id)} className="flex gap-2"><select name="treasuryAccountId" defaultValue={current} className="min-w-64 rounded-lg border border-line px-3 py-2 text-xs"><option value="">— Non associé —</option>{data.treasuryAccounts.filter(a=>a.active&&a.currency===f.currency).map(a=><option key={a.id} value={a.id}>{a.name} · {a.institution}</option>)}</select><button className="rounded-lg border border-line px-3 py-2 text-xs">Enregistrer</button></form></td></tr>})}</tbody></table></div>:<p className="text-sm text-muted2">Aucun compte de paiement Finance configuré.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Comptes de sortie par devise</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-muted2">Choisissez le compte de trésorerie utilisé par défaut pour les remboursements et dépenses. Ceci permet à JUN de savoir d’où sort réellement l’argent.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{currencies.map(currency=><form key={currency} action={setOutgoingTreasuryAccountAction.bind(null,currency)} className="rounded-xl border border-line p-3"><div className="mb-2 text-sm font-semibold">Sorties {currency}</div><select name="treasuryAccountId" defaultValue={data.settings.outgoingAccountByCurrency[currency]||""} className="w-full rounded-lg border border-line px-3 py-2 text-xs"><option value="">— Aucun compte par défaut —</option>{data.treasuryAccounts.filter(a=>a.active&&a.currency===currency).map(a=><option key={a.id} value={a.id}>{a.name} · {a.institution}</option>)}</select><button className="mt-2 w-full rounded-lg border border-line px-3 py-2 text-xs">Enregistrer</button></form>)}</div></CardContent></Card>

    <Card><CardHeader><CardTitle>Profit réel par projet lié</CardTitle></CardHeader><CardContent>{data.projects.length?<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Projet</th><th className="p-2 text-right">Entrées Finance</th><th className="p-2 text-right">Sorties Finance</th><th className="p-2 text-right">Profit Finance</th><th className="p-2 text-right">Flux</th></tr></thead><tbody>{data.projects.map(p=><tr key={p.id} className="border-b border-line/70"><td className="p-2 font-medium">{p.name}<div className="text-[10px] text-muted2">{p.code}{p.caseId?" · dossier lié":" · aucun dossier lié"}</div></td><td className="p-2 text-right">{formatMoney(p.income,p.currency)}</td><td className="p-2 text-right">{formatMoney(p.out,p.currency)}</td><td className={`p-2 text-right font-semibold ${p.profit>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(p.profit,p.currency)}</td><td className="p-2 text-right">{p.entryCount}</td></tr>)}</tbody></table></div>:<p className="text-sm text-muted2">Aucun projet connecté.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle>100 derniers flux consolidés</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Date</th><th className="p-2">Source</th><th className="p-2">Référence</th><th className="p-2">Catégorie</th><th className="p-2 text-right">Montant</th><th className="p-2">Compte Trésorerie</th></tr></thead><tbody>{data.entries.slice(0,100).map(e=>{const a=data.treasuryAccounts.find(x=>x.id===e.treasuryAccountId);return <tr key={e.id} className="border-b border-line/70"><td className="p-2 text-xs">{formatDateTime(e.occurredAt)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] ${e.direction==="IN"?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{e.sourceType}</span></td><td className="p-2 font-medium">{e.reference}</td><td className="p-2 text-xs">{e.category}</td><td className={`p-2 text-right font-semibold ${e.direction==="IN"?"text-emerald-700":"text-red-700"}`}>{e.direction==="IN"?"+":"-"}{formatMoney(e.amount,e.currency)}</td><td className="p-2 text-xs">{a?`${a.name} · ${a.institution}`:<span className="text-amber-700">Non affecté</span>}</td></tr>})}</tbody></table></div></CardContent></Card>
  </div>
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof CircleDollarSign;label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-surface p-3"><div className="text-[10px] uppercase tracking-wide text-muted2">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}
