"use client";
import { useState } from "react";
import { correctInvoice } from "@/services/finance-corrections";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { Plus, Trash2 } from "lucide-react";
type Row={id:string;description:string;quantity:string;unitPrice:string;taxRate:string};
export function InvoiceEditForm({invoiceId,clients,cases,value}:{invoiceId:string;clients:Array<{id:string;firstName:string;lastName:string;internalId:string}>;cases:Array<{id:string;caseNumber:string;title:string;clientId:string}>;value:{clientId:string;caseId:string;currency:string;dueDate:string;title:string;notes:string;terms:string;lines:Array<{id:string;description:string;quantity:number;unitPrice:number;taxRate:number}>;wasSent:boolean}}){
 const [clientId,setClientId]=useState(value.clientId);const [rows,setRows]=useState<Row[]>(value.lines.map(l=>({id:l.id,description:l.description,quantity:String(l.quantity),unitPrice:String(l.unitPrice),taxRate:String(l.taxRate)})));const visibleCases=cases.filter(c=>!clientId||c.clientId===clientId);const add=()=>setRows(v=>[...v,{id:crypto.randomUUID(),description:"",quantity:"1",unitPrice:"",taxRate:"0"}]);const remove=(id:string)=>setRows(v=>v.length>1?v.filter(r=>r.id!==id):v);const patch=(id:string,key:keyof Row,val:string)=>setRows(v=>v.map(r=>r.id===id?{...r,[key]:val}:r));
 return <form action={correctInvoice.bind(null,invoiceId)} className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Client"><Select name="clientId" value={clientId} onChange={e=>setClientId(e.target.value)} required>{clients.map(c=><option key={c.id} value={c.id}>{c.lastName}, {c.firstName} · {c.internalId}</option>)}</Select></Field><Field label="Case"><Select name="caseId" defaultValue={value.caseId}><option value="">No case</option>{visibleCases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} · {c.title}</option>)}</Select></Field><Field label="Currency"><Input name="currency" defaultValue={value.currency} maxLength={3} required/></Field><Field label="Due date"><Input name="dueDate" type="date" defaultValue={value.dueDate} required/></Field></div><Field label="Invoice title / service"><Input name="title" defaultValue={value.title} required/></Field>
 <div className="rounded-xl border border-line bg-white"><div className="flex items-center justify-between border-b border-line p-4"><div><div className="font-medium">Invoice lines</div><div className="text-xs text-muted2">Correct, add or remove lines before saving.</div></div><Button type="button" variant="outline" onClick={add}><Plus className="h-4 w-4"/>Add line</Button></div><div className="space-y-3 p-4">{rows.map((r,i)=><div key={r.id} className="grid gap-3 rounded-lg border border-line p-3 md:grid-cols-[minmax(0,1fr)_100px_140px_100px_44px]"><Field label={`Description ${i+1}`}><Input name="lineDescription" value={r.description} onChange={e=>patch(r.id,"description",e.target.value)} required/></Field><Field label="Qty"><Input name="lineQuantity" type="number" min="0.01" step="0.01" value={r.quantity} onChange={e=>patch(r.id,"quantity",e.target.value)} required/></Field><Field label="Unit price"><Input name="lineUnitPrice" type="number" min="0" step="0.01" value={r.unitPrice} onChange={e=>patch(r.id,"unitPrice",e.target.value)} required/></Field><Field label="Tax %"><Input name="lineTaxRate" type="number" min="0" step="0.01" value={r.taxRate} onChange={e=>patch(r.id,"taxRate",e.target.value)}/></Field><div className="flex items-end"><button type="button" onClick={()=>remove(r.id)} className="flex h-10 w-10 items-center justify-center rounded-lg border border-line text-muted2 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></div>)}</div></div>
 <div className="grid gap-4 md:grid-cols-2"><Field label="Notes"><Textarea name="notes" rows={4} defaultValue={value.notes}/></Field><Field label="Payment terms"><Textarea name="terms" rows={4} defaultValue={value.terms}/></Field></div>{value.wasSent?<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">This invoice was already sent. A correction will return it to <strong>DRAFT</strong> so the corrected version must be sent again.</div>:null}<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><Field label="Correction reason" hint="Required and permanently audited."><Textarea name="correctionReason" rows={3} required/></Field></div><Button variant="primary">Save correction</Button></form>
}
