export const DOC_PREFIX: Record<string, string> = {
  CONTRACT: "JUN-CTR",
  AGREEMENT: "JUN-AGR",
  REFUND_AGREEMENT: "JUN-RAG",
  RECEIPT: "JUN-RCP",
  INVOICE: "JUN-INV",
  LETTER: "JUN-LTR",
  ATTESTATION: "JUN-ATT",
  AUTHORIZATION: "JUN-AUT",
  REPORT: "JUN-RPT",
  CUSTOM: "JUN-DOC",
};
