import Link from "next/link";
import { requireUser, can } from "@/lib/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { googleConfigured } from "@/lib/google/gmail";
import { PageHeader } from "@/components/app/page-header";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { disconnectMailbox } from "@/services/mailbox";
import { updateMailboxProfile } from "@/services/mailbox-profile";
import { formatDateTime } from "@/lib/utils";
import { AlertTriangle, Mail, Plug, RefreshCw } from "lucide-react";

export const dynamic = "force-dynamic";
export default async function EmailSettingsPage({searchParams}:{searchParams:{gmail_reconnect?:string;accountId?:string}}){
 const user=await requireUser();if(!can(user,"SETTINGS_MANAGE"))redirect("/app/forbidden");const accounts=await prisma.mailAccount.findMany({orderBy:{createdAt:"asc"}}),configured=googleConfigured();
 const reconnectRequired=searchParams.gmail_reconnect==="1";
 const reconnectAccount=searchParams.accountId?accounts.find(a=>a.id===searchParams.accountId):null;
 return <div><PageHeader title="Intégration Email" subtitle="Connectez et gérez les boîtes Gmail / Google Workspace utilisées par JUN Mail Center." actions={<div className="flex flex-wrap gap-2"><Link href="/app/settings/email/composer"><Button variant="outline">Signatures & modèles</Button></Link><Link href="/app/mail?mailbox=ALL"><Button variant="outline">Ouvrir Mail Center</Button></Link></div>}/>
 {reconnectRequired?<div className="mb-6 rounded-2xl border border-amber-400/25 bg-amber-500/10 p-4 text-sm text-amber-100"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-300"/><div className="min-w-0 flex-1"><p className="font-semibold">Reconnexion Gmail requise</p><p className="mt-1 text-amber-100/75">Google a expiré ou révoqué le jeton d’autorisation{reconnectAccount?` de ${reconnectAccount.email}`:" d’une boîte connectée"}. La synchronisation ne peut pas reprendre tant qu’un nouveau jeton OAuth n’a pas été accordé.</p>{configured?<a href="/api/google/oauth/start" className="mt-3 inline-block"><Button variant="primary"><RefreshCw className="h-4 w-4"/>Reconnecter Gmail</Button></a>:null}</div></div></div>:null}
 <Card className="mb-6"><CardHeader><CardTitle className="flex items-center gap-2"><Plug className="h-4 w-4"/>Connecter une boîte Gmail / Google Workspace</CardTitle></CardHeader><CardContent className="space-y-3">{configured?<><p className="text-sm text-muted2">Vous pouvez connecter plusieurs boîtes opérationnelles. Pour renouveler une autorisation expirée, utilisez également ce bouton puis choisissez le même compte Google.</p><a href="/api/google/oauth/start"><Button variant="primary">Connecter ou reconnecter Gmail</Button></a></>:<div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4 text-sm"><p className="font-medium text-amber-300">READY — CREDENTIALS REQUIRED</p><p className="mt-1 text-muted2">Set these environment variables to activate Google OAuth:</p><pre className="registry-id mt-2 text-xs text-white/70">GOOGLE_CLIENT_ID{"\n"}GOOGLE_CLIENT_SECRET{"\n"}GOOGLE_REDIRECT_URI = https://www.juncreatif.org/api/google/oauth/callback</pre></div>}</CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Mail className="h-4 w-4"/>Boîtes connectées</CardTitle></CardHeader><CardContent>{accounts.length===0?<p className="text-sm text-muted2">Aucune boîte connectée.</p>:<div className="space-y-4">{accounts.map(a=>{const hasTokens=Boolean(a.refreshTokenEnc||a.accessTokenEnc);const needsReconnect=reconnectRequired&&a.id===searchParams.accountId;return <div key={a.id} className={`rounded-xl border p-4 ${needsReconnect?"border-amber-400/30 bg-amber-500/[0.06]":"border-line"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{a.displayName||a.email}</p><Badge className={needsReconnect?"bg-amber-500/15 text-amber-300":hasTokens?"bg-emerald-500/15 text-emerald-300":"bg-red-500/15 text-red-300"}>{needsReconnect?"RECONNEXION REQUISE":hasTokens?"CONNECTÉE":"DÉCONNECTÉE"}</Badge></div><p className="mt-1 text-sm text-muted2">{a.email}</p><p className="mt-1 text-xs text-muted2">Ajoutée {formatDateTime(a.createdAt)}</p></div><div className="flex flex-wrap gap-2">{needsReconnect&&configured?<a href="/api/google/oauth/start"><Button variant="primary" size="sm"><RefreshCw className="h-4 w-4"/>Reconnecter</Button></a>:null}{hasTokens&&!needsReconnect?<Link href={`/app/mail?mailbox=${a.id}&folder=INBOX`}><Button variant="outline" size="sm">Ouvrir</Button></Link>:null}{hasTokens?<form action={disconnectMailbox.bind(null,a.id)}><Button variant="danger" size="sm">Déconnecter</Button></form>:null}</div></div><form action={updateMailboxProfile.bind(null,a.id)} className="mt-4 grid gap-3 border-t border-line pt-4 md:grid-cols-[1fr_auto_auto] md:items-end"><label className="text-sm"><span className="mb-1 block text-xs font-medium text-muted2">Nom d’affichage</span><Input name="displayName" defaultValue={a.displayName??""} placeholder="Finance, Travel, Support…" maxLength={80}/></label><label className="flex h-10 items-center gap-2 rounded-md border border-line px-3 text-sm"><input type="checkbox" name="aiEnabled" defaultChecked={a.aiEnabled}/><span>JUN AI activé</span></label><Button variant="secondary">Enregistrer</Button></form></div>})}</div>}</CardContent></Card></div>;
}
