import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getPaymentCoreMeta } from "@/lib/finance-payment-core";
import { paymentEditMode, editPolicyMessage } from "@/lib/edit-policy";
import { correctPayment } from "@/services/finance-corrections";
import { correctPaymentFee } from "@/services/finance-payment-fee-correction";
import { PageHeader } from "@/components/app/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
export const dynamic="force-dynamic";
export default async function EditPaymentPage({params,searchParams}:{params:{id:string};searchParams:{toast_error?:string}}){
 await requirePermission("PAYMENT_READ");const [p,meta,clients,cases]=await Promise.all([prisma.payment.findUnique({where:{id:params.id}}),getPaymentCoreMeta(params.id),prisma.client.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{lastName:"asc"},select:{id:true,firstName:true,lastName:true,internalId:true}}),prisma.case.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{createdAt:"desc"},take:500,select:{id:true,clientId:true,caseNumber:true,title:true}})]);if(!p)notFound();const mode=paymentEditMode(p.status);const direct=mode==="DIRECT";
 const gross=Number(p.amount),fee=meta.feeAmount??0,net=Math.max(0,Math.round((gross-fee)*100)/100);
 return <div><PageHeader title={`Correct ${p.reference}`} subtitle={editPolicyMessage(mode)}><Link href={`/app/finance/payments/${p.id}`}><Button variant="outline">Cancel</Button></Link></PageHeader>{searchParams.toast_error?<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{searchParams.toast_error}</div>:null}<Card><CardContent className="p-5">{mode==="LOCKED"?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">This payment cannot be overwritten. Use a reversal/replacement record to preserve financial history.</div>:<form action={correctPayment.bind(null,p.id)} className="grid max-w-4xl gap-5 sm:grid-cols-2">
  {direct?<><div className="sm:col-span-2"><Field label="Client"><Select name="clientId" defaultValue={p.clientId}>{clients.map(c=><option key={c.id} value={c.id}>{c.lastName}, {c.firstName} — {c.internalId}</option>)}</Select></Field></div><Field label="Case"><Select name="caseId" defaultValue={p.caseId||""}><option value="">No case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} — {c.title}</option>)}</Select></Field><Field label="Amount"><Input name="amount" type="number" step="0.01" min="0.01" defaultValue={Number(p.amount)} required/></Field><Field label="Currency"><Input name="currency" defaultValue={p.currency} maxLength={3} required/></Field><Field label="Method"><Select name="method" defaultValue={p.method}>{["ZELLE","STRIPE","PAYPAL","MERCADO_PAGO","BANK_TRANSFER","CASH","MONCASH","OTHER"].map(m=><option key={m} value={m}>{m.replaceAll("_"," ")}</option>)}</Select></Field><Field label="Expected amount"><Input name="expectedAmount" type="number" step="0.01" defaultValue={meta.expectedAmount??""}/></Field><Field label="Payment date"><Input name="paidAt" type="date" defaultValue={p.paidAt?p.paidAt.toISOString().slice(0,10):""}/></Field></>:<div className="sm:col-span-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">Payment is {p.status.replaceAll("_"," ")}. Amount, currency, method, client, case and payment date are locked. Reference, purpose, notes and transfer/processing fee can still be corrected with an audit trail.</div>}
  <Field label="Provider / bank reference"><Input name="providerRef" defaultValue={p.providerRef||meta.providerRef||""}/></Field><Field label="Service / purpose"><Input name="serviceLabel" defaultValue={meta.serviceLabel||""}/></Field><div className="sm:col-span-2"><Field label="Notes"><Textarea name="notes" rows={4} defaultValue={p.notes||""}/></Field></div><div className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4"><Field label="Correction reason" hint="Required and permanently audited."><Textarea name="correctionReason" rows={3} required placeholder="What was wrong? What should the correct information be?"/></Field></div><div className="sm:col-span-2"><Button variant="primary" type="submit">Save correction</Button></div>
 </form>}</CardContent></Card>
 <Card className="mt-5"><CardHeader><CardTitle>Transfer / processing fee</CardTitle></CardHeader><CardContent><div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-line bg-surface p-3"><div className="text-xs text-muted2">Gross paid / received</div><div className="mt-1 font-semibold">{p.currency} {gross.toFixed(2)}</div></div><div className="rounded-lg border border-line bg-surface p-3"><div className="text-xs text-muted2">Transfer fee</div><div className="mt-1 font-semibold">{p.currency} {fee.toFixed(2)}</div></div><div className="rounded-lg border border-line bg-surface p-3"><div className="text-xs text-muted2">Net received by JUN</div><div className="mt-1 font-semibold">{p.currency} {net.toFixed(2)}</div></div></div><p className="mb-4 text-sm text-muted2">Use this when the sender paid a gross amount but the transfer provider deducted a fee before JUN received the money. Example: sender pays $450, transfer fee $40, JUN receives $410.</p><form action={correctPaymentFee.bind(null,p.id)} className="grid max-w-2xl gap-4 sm:grid-cols-2"><Field label="Transfer / processing fee"><Input name="feeAmount" type="number" step="0.01" min="0" max={gross} defaultValue={fee}/></Field><div className="sm:col-span-2"><Field label="Reason" hint="Required and recorded in the audit history."><Textarea name="feeCorrectionReason" rows={3} required placeholder="Example: Ria/Western Union deducted $40 from the $450 sender payment; JUN received $410."/></Field></div><div className="sm:col-span-2"><Button variant="primary" type="submit">Save fee correction</Button></div></form></CardContent></Card></div>
}
