import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireUser, can } from "@/lib/auth";
import { getCaseReport } from "@/lib/case-report";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge, StatusBadge } from "@/components/ui/badge";
import { PrintButton } from "@/components/app/print-button";
import { formatMoney } from "@/lib/utils";
import { FileText, Gauge, Landmark, ListChecks, ShieldCheck } from "lucide-react";

export const dynamic="force-dynamic";
const riskClass:Record<string,string>={LOW:"bg-emerald-100 text-emerald-800",MEDIUM:"bg-amber-100 text-amber-800",HIGH:"bg-orange-100 text-orange-800",CRITICAL:"bg-red-100 text-red-800"};

export default async function CaseReportsPage({params}:{params:Promise<{id:string}>|{id:string}}){
 const user=await requireUser();if(!can(user,"CASE_READ"))redirect("/app/forbidden");const {id}=await Promise.resolve(params);
 const report=await getCaseReport(id);if(!report)notFound();const c=report.case;
 return <div className="space-y-5 print:space-y-3">
  <div className="flex flex-wrap items-start justify-between gap-4 print:block"><div><Link href={`/app/cases/${id}/dashboard`} className="text-sm text-muted2 hover:text-electric print:hidden">← Case 360</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Case Reporting & Export</h1><StatusBadge status={c.status}/><Badge className={riskClass[report.intelligence.riskLevel]}>{report.intelligence.riskLevel} RISK</Badge></div><p className="mt-1 text-sm text-muted2">{c.caseNumber} · {c.title} · {report.reportReference}</p></div><div className="flex flex-wrap gap-2 print:hidden"><PrintButton/><a href={`/api/cases/${id}/report.pdf`} target="_blank" rel="noreferrer"><Button variant="primary">Official PDF</Button></a></div></div>

  <Card><CardHeader><CardTitle>Executive summary</CardTitle></CardHeader><CardContent><p className="text-sm leading-6">{report.executiveSummary}</p></CardContent></Card>

  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Gauge} label="Risk score" value={`${report.intelligence.score}/100`} sub={report.intelligence.riskLevel}/><Metric icon={ListChecks} label="Operations" value={`${report.operations.facts.progress}%`} sub="task + milestone progress"/><Metric icon={ShieldCheck} label="Closure" value={report.intelligence.readiness.ready?"READY":"BLOCKED"} sub="hard-blocker status"/><Metric icon={FileText} label="Records" value={String(c.documents.length+c.files.length)} sub="official + Drive"/><Metric icon={Landmark} label="Currencies" value={String(report.finance.summaries.length)} sub="financial positions"/></div>

  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader><CardTitle>Case profile</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Line label="Client" value={`${c.client.firstName} ${c.client.lastName} · ${c.client.internalId}`}/><Line label="Type" value={c.type.replaceAll("_"," ")}/><Line label="Status" value={c.status.replaceAll("_"," ")}/><Line label="Priority" value={c.priority}/><Line label="Owner" value={c.owner?`${c.owner.firstName} ${c.owner.lastName}`:"Unassigned"}/><Line label="Due date" value={c.dueDate?c.dueDate.toISOString().slice(0,10):"—"}/></CardContent></Card>
   <Card><CardHeader><CardTitle>Operational position</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Line label="Tasks completed" value={`${c.tasks.filter(t=>t.status==="DONE").length}/${c.tasks.filter(t=>t.status!=="CANCELLED").length}`}/><Line label="Milestones completed" value={`${report.operations.facts.milestoneDone}/${report.operations.milestones.filter(m=>m.status!=="CANCELLED").length}`}/><Line label="Blocked milestones" value={String(report.operations.facts.blockedMilestones.length)}/><Line label="Overdue tasks" value={String(report.operations.facts.overdueTasks.length)}/><Line label="Overdue milestones" value={String(report.operations.facts.overdueMilestones.length)}/></CardContent></Card>
  </div>

  <Card><CardHeader><CardTitle>Financial position</CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto">{report.finance.summaries.length?<table className="w-full min-w-[850px] text-sm"><thead className="border-y border-line bg-surface/60 text-left text-xs uppercase tracking-wide text-muted2"><tr><th className="px-4 py-3">Currency</th><th>Billed</th><th>Paid</th><th>Receivable</th><th>Refunds paid</th><th>Expenses paid</th><th>Realized profit</th><th>Forecast profit</th></tr></thead><tbody>{report.finance.summaries.map(s=><tr key={s.currency} className="border-b border-line"><td className="px-4 py-3 font-semibold">{s.currency}</td><td>{formatMoney(s.billed,s.currency)}</td><td>{formatMoney(s.invoicePaid,s.currency)}</td><td>{formatMoney(s.receivable,s.currency)}</td><td>{formatMoney(s.refundsPaid,s.currency)}</td><td>{formatMoney(s.expensePaid,s.currency)}</td><td className={s.realizedProfit<0?"font-semibold text-red-600":"font-semibold text-emerald-700"}>{formatMoney(s.realizedProfit,s.currency)}</td><td>{formatMoney(s.forecastProfit,s.currency)}</td></tr>)}</tbody></table>:<p className="p-5 text-sm text-muted2">No financial activity linked to this Case.</p>}</CardContent></Card>

  <div className="grid gap-5 xl:grid-cols-2">
   <Card><CardHeader><CardTitle>Risk register</CardTitle></CardHeader><CardContent className="space-y-3">{report.intelligence.insights.length?report.intelligence.insights.slice(0,12).map(x=><div key={x.id} className="rounded-lg border border-line p-3"><div className="flex items-center gap-2"><Badge className={riskClass[x.severity]}>{x.severity}</Badge><span className="text-xs font-medium text-muted2">{x.area}</span></div><p className="mt-2 font-medium">{x.title}</p><p className="mt-1 text-sm text-muted2">{x.detail}</p><p className="mt-2 text-sm"><strong>Action:</strong> {x.action}</p></div>):<p className="text-sm text-muted2">No active deterministic risk.</p>}</CardContent></Card>
   <Card><CardHeader><CardTitle>Documents & communications</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Line label="Official documents" value={String(c.documents.length)}/><Line label="Drive files" value={String(c.files.length)}/><Line label="FINAL / SIGNED" value={String(report.intelligence.health.finalDocuments)}/><Line label="Communications" value={String(report.communications.length)}/><Line label="Critical communications" value={String(report.intelligence.health.criticalCommunications)}/><Line label="Safe Automation runs" value={String(report.automation.runs.length)}/><Line label="Closure snapshot" value={report.closure?"PRESERVED":"NOT CLOSED"}/></CardContent></Card>
  </div>

  <Card><CardHeader><CardTitle>Official exports</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-line p-4"><p className="font-medium">Official Case PDF</p><p className="mt-1 text-xs text-muted2">A4 report with JUN verification QR and stable report reference.</p><a href={`/api/cases/${id}/report.pdf`} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm text-electric hover:underline">Open PDF →</a></div><div className="rounded-xl border border-line p-4"><p className="font-medium">Printable web report</p><p className="mt-1 text-xs text-muted2">Use the browser print dialog to print or save this report locally as PDF.</p><div className="mt-3 print:hidden"><PrintButton label="Print report"/></div></div><div className="rounded-xl border border-line p-4"><p className="font-medium">Verification reference</p><p className="registry-id mt-2 text-sm">{report.reportReference}</p><p className="mt-1 text-xs text-muted2">The official PDF registers this reference in JUN document verification.</p></div></CardContent></Card>
 </div>;
}
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub:string}){return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-electric"/><p className="mt-3 text-xs text-muted2">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted2">{sub}</p></CardContent></Card>}
function Line({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-4 border-b border-line pb-2 last:border-0"><span className="text-muted2">{label}</span><span className="text-right font-medium">{value}</span></div>}
