import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { refundEditMode, editPolicyMessage } from "@/lib/edit-policy";
import { correctRefund } from "@/services/finance-corrections";
import { PageHeader } from "@/components/app/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
export const dynamic="force-dynamic";
export default async function EditRefundPage({params}:{params:{id:string}}){
 await requirePermission("REFUND_READ");const [r,clients,cases,payments]=await Promise.all([prisma.refund.findUnique({where:{id:params.id},include:{installments:true}}),prisma.client.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{lastName:"asc"},select:{id:true,firstName:true,lastName:true,internalId:true}}),prisma.case.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{createdAt:"desc"},take:500,select:{id:true,caseNumber:true,title:true,clientId:true}}),prisma.payment.findMany({where:{status:{in:["CONFIRMED","PARTIALLY_REFUNDED"]}},orderBy:{createdAt:"desc"},take:500,select:{id:true,reference:true,clientId:true,amount:true,currency:true}})]);if(!r)notFound();const mode=refundEditMode(r.status,r.installments.filter(i=>i.status==="PAID").length);
 return <div><PageHeader title={`Correct ${r.refundNumber}`} subtitle={editPolicyMessage(mode)}><Link href={`/app/finance/refunds/${r.id}`}><Button variant="outline">Cancel</Button></Link></PageHeader><Card><CardContent className="p-5">{mode==="LOCKED"?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">This refund can no longer be overwritten because a payout was made or the request is final. Create a new corrective record instead.</div>:<form action={correctRefund.bind(null,r.id)} className="grid max-w-4xl gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Client"><Select name="clientId" defaultValue={r.clientId}>{clients.map(c=><option key={c.id} value={c.id}>{c.lastName}, {c.firstName} — {c.internalId}</option>)}</Select></Field></div><Field label="Case"><Select name="caseId" defaultValue={r.caseId||""}><option value="">No case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} — {c.title}</option>)}</Select></Field><Field label="Original payment"><Select name="paymentId" defaultValue={r.paymentId||""}><option value="">Unlinked refund</option>{payments.map(p=><option key={p.id} value={p.id}>{p.reference} — {p.currency} {Number(p.amount).toFixed(2)}</option>)}</Select></Field><Field label="Amount"><Input name="amount" type="number" step="0.01" min="0.01" defaultValue={Number(r.amount)} required/></Field><Field label="Currency"><Input name="currency" defaultValue={r.currency} maxLength={3} required/></Field><div className="sm:col-span-2"><Field label="Reason"><Textarea name="reason" rows={4} defaultValue={r.reason} required/></Field></div>{r.status==="APPROVED"?<div className="sm:col-span-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">Because this refund is already approved, any correction will automatically return it to <strong>UNDER REVIEW</strong> and require approval again.</div>:null}<div className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4"><Field label="Correction reason" hint="Required and permanently audited."><Textarea name="correctionReason" rows={3} required/></Field></div><div className="sm:col-span-2"><Button variant="primary" type="submit">Save correction</Button></div></form>}</CardContent></Card></div>
}
