import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser, can } from "@/lib/auth";
import { listMailboxAccessRules, listMailReliabilityEvents, mailboxHealthFromAccount } from "@/lib/mail-security";
import { clearUserMailboxRestriction, probeMailboxHealth, updateUserMailboxAccess } from "@/services/mail-security";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export const dynamic="force-dynamic";
const HEALTH_CLASS:Record<string,string>={HEALTHY:"bg-emerald-100 text-emerald-800",REFRESHABLE:"bg-blue-100 text-blue-800",DISCONNECTED:"bg-slate-100 text-slate-700",ERROR:"bg-red-100 text-red-700"};
const EVENT_CLASS:Record<string,string>={SEND_ERROR:"bg-red-100 text-red-700",TOKEN_ERROR:"bg-red-100 text-red-700",SYNC_ERROR:"bg-amber-100 text-amber-800",DOUBLE_SEND_BLOCKED:"bg-violet-100 text-violet-800",ACCESS_DENIED:"bg-violet-100 text-violet-800",HEALTH_CHECK:"bg-emerald-100 text-emerald-800",RETRY_SUCCESS:"bg-blue-100 text-blue-800"};

export default async function MailSecurityPage(){
 const user=await requireUser();if(!can(user,"EMAIL_MANAGE"))redirect("/app/forbidden");
 const [accounts,staff,rules,events]=await Promise.all([
  prisma.mailAccount.findMany({orderBy:{createdAt:"asc"},select:{id:true,email:true,displayName:true,accessTokenEnc:true,refreshTokenEnc:true,tokenExpiry:true,updatedAt:true}}),
  prisma.user.findMany({where:{status:"ACTIVE",role:{not:"CLIENT"}},orderBy:[{firstName:"asc"},{lastName:"asc"}],select:{id:true,firstName:true,lastName:true,email:true,role:true}}),
  listMailboxAccessRules(),listMailReliabilityEvents(100),
 ]);
 const ruleMap=new Map(rules.map(r=>[r.userId,r]));const accountEmail=new Map(accounts.map(a=>[a.id,a.email]));
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Mail Security & Reliability</h1><p className="mt-1 text-sm text-muted2">Mailbox access control, Gmail credential health, send protection and production incidents.</p></div><div className="flex gap-2"><Link href="/app/settings/email"><Button variant="secondary">Email settings</Button></Link><Link href="/app/mail"><Button variant="outline">Back to Mail</Button></Link></div></div>
  <Card><CardHeader><CardTitle>Gmail credential health</CardTitle></CardHeader><CardContent><div className="space-y-3">{accounts.map(a=>{const h=mailboxHealthFromAccount(a);return <div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-line p-4"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{a.displayName||a.email}</p><Badge className={HEALTH_CLASS[h.status]??""}>{h.status}</Badge></div><p className="mt-1 text-xs text-muted2">{a.email} · {h.message}</p><p className="mt-1 text-xs text-muted2">Access token: {h.hasAccessToken?"available":"missing"} · Refresh token: {h.hasRefreshToken?"available":"missing"} · Expiry: {h.tokenExpiry?new Date(h.tokenExpiry).toLocaleString():"—"}</p></div><form action={probeMailboxHealth.bind(null,a.id)}><Button variant="outline">Run health check</Button></form></div>})}{!accounts.length?<p className="text-sm text-muted2">No mailbox account exists yet.</p>:null}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Mailbox access control</CardTitle></CardHeader><CardContent><p className="mb-4 text-xs text-muted2">No explicit restriction means legacy full mailbox access according to the user’s normal EMAIL permissions. Saving a restriction changes that user to only the checked mailboxes. Administrators with EMAIL_MANAGE always retain full administrative access.</p><div className="space-y-4">{staff.map(s=>{const rule=ruleMap.get(s.id),selected=new Set(rule?.accountIds??[]);return <div key={s.id} className="rounded-xl border border-line p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{s.firstName} {s.lastName}</p><p className="text-xs text-muted2">{s.email} · {s.role.replaceAll("_"," ")} · {rule?`${rule.accountIds.length} restricted mailbox(es)`:"No explicit restriction"}</p></div>{rule?<form action={clearUserMailboxRestriction.bind(null,s.id)}><Button variant="ghost">Clear restriction</Button></form>:null}</div><form action={updateUserMailboxAccess.bind(null,s.id)} className="mt-3"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{accounts.map(a=><label key={a.id} className="flex items-start gap-2 rounded-lg border border-line p-3 text-sm"><input className="mt-1" type="checkbox" name="accountIds" value={a.id} defaultChecked={selected.has(a.id)}/><span><span className="font-medium">{a.displayName||a.email}</span><span className="block text-xs text-muted2">{a.email}</span></span></label>)}</div><div className="mt-3 flex items-center gap-2"><Button variant="secondary">Save restriction</Button><span className="text-xs text-muted2">Saving with no mailbox checked means explicit access to zero mailboxes.</span></div></form></div>})}</div></CardContent></Card>
  <Card><CardHeader><CardTitle>Reliability events</CardTitle></CardHeader><CardContent><div className="space-y-2">{events.map(e=><div key={e.id} className="rounded-lg border border-line p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-2"><Badge className={EVENT_CLASS[e.type]??""}>{e.type.replaceAll("_"," ")}</Badge><span className="text-xs text-muted2">{e.accountId?accountEmail.get(e.accountId)||e.accountId:"All mailboxes"}{e.threadId?` · Thread ${e.threadId}`:""}</span></div><span className="text-xs text-muted2">{new Date(e.createdAt).toLocaleString()}</span></div><p className="mt-2 text-sm">{e.message}</p></div>)}{!events.length?<p className="text-sm text-muted2">No reliability event has been recorded yet.</p>:null}</div></CardContent></Card>
  <Card><CardContent className="p-4 text-xs text-muted2"><strong className="text-ink">Security note.</strong> Encrypted Gmail tokens are never rendered on this page. Health checks only expose availability, expiry and success/failure state. Exact-draft send locks prevent concurrent sends and block a repeated send after Gmail has confirmed delivery.</CardContent></Card>
 </div>;
}
