import { requirePermission, can } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PageHeader } from "@/components/app/page-header";
import { StatusBadge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { Select } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { formatDate, cn } from "@/lib/utils";
import { setTaskStatus } from "@/services/tasks";
import { CheckSquare, Pencil, Clock3, UsersRound } from "lucide-react";
import Link from "next/link";
import type { Prisma } from "@prisma/client";

export const dynamic = "force-dynamic";
export default async function TasksPage({searchParams}:{searchParams:{view?:string;status?:string;assignee?:string;focus?:string}}){
 const user=await requirePermission("TASK_READ"); const canEdit=can(user,"TASK_UPDATE"); const status=searchParams.status; const assignee=searchParams.assignee; const now=new Date();
 const where:Prisma.TaskWhereInput={...(status==="OVERDUE"?{status:{in:["TODO","IN_PROGRESS","WAITING"]},dueDate:{lt:now}}:status&&status!=="ALL"?{status:status as never}:{}),...(assignee&&assignee!=="ALL"?{assigneeId:assignee}:{})};
 const [tasks,users]=await Promise.all([prisma.task.findMany({where,orderBy:[{status:"asc"},{dueDate:"asc"}],take:200,include:{assignee:true,client:true,case:true}}),prisma.user.findMany({where:{status:"ACTIVE",role:{not:"CLIENT"}},orderBy:{firstName:"asc"}})]);
 const byAssignee=new Map<string,typeof tasks>(); for(const t of tasks){const key=t.assignee?`${t.assignee.firstName} ${t.assignee.lastName}`:"Non assignée";byAssignee.set(key,[...(byAssignee.get(key)??[]),t]);} const grouped=searchParams.view==="assignee";
 const overdueCount=tasks.filter(t=>t.dueDate&&new Date(t.dueDate)<now&&!["DONE","CANCELLED"].includes(t.status)).length;
 const activeCount=tasks.filter(t=>["TODO","IN_PROGRESS","WAITING"].includes(t.status)).length;
 return <div><PageHeader title="Tâches" subtitle="Ce qui doit être fait, par qui et avant quelle date." actionHref="/app/tasks/new" actionLabel="Nouvelle tâche"><Link href={`/app/tasks?view=${grouped?"list":"assignee"}`}><Button variant="outline">{grouped?"Vue liste":"Par responsable"}</Button></Link></PageHeader>
 <div className="mb-5 grid gap-3 sm:grid-cols-3"><TaskMetric icon={CheckSquare} label="Résultats affichés" value={tasks.length}/><TaskMetric icon={Clock3} label="Actives" value={activeCount}/><TaskMetric icon={UsersRound} label="En retard" value={overdueCount} alert={overdueCount>0}/></div>
 <form className="mb-5 flex flex-wrap gap-2 rounded-2xl border border-white/[0.07] bg-[#0e1624] p-3 shadow-sm"><input type="hidden" name="view" value={searchParams.view??"list"}/><Select name="status" defaultValue={status??"ALL"} className="w-44"><option value="ALL">Tous les statuts</option><option value="OVERDUE">En retard</option>{["TODO","IN_PROGRESS","WAITING","DONE","CANCELLED"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select><Select name="assignee" defaultValue={assignee??"ALL"} className="w-52"><option value="ALL">Tous les responsables</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</Select><Button variant="outline">Filtrer</Button></form>
 {tasks.length===0?<EmptyState icon={CheckSquare} title="Aucune tâche" description="Créez une tâche pour rendre la prochaine étape explicite." actionHref="/app/tasks/new" actionLabel="Créer une tâche"/>:grouped?<div className="space-y-6">{[...byAssignee.entries()].map(([name,list])=><div key={name}><h2 className="mb-2 text-sm font-semibold text-slate-200">{name} <span className="text-muted2">({list.length})</span></h2><TaskList tasks={list} focus={searchParams.focus} canEdit={canEdit}/></div>)}</div>:<TaskList tasks={tasks} focus={searchParams.focus} canEdit={canEdit}/>}</div>
}
function TaskMetric({icon:Icon,label,value,alert=false}:{icon:typeof CheckSquare;label:string;value:number;alert?:boolean}){return <div className={`rounded-2xl border p-4 ${alert?"border-rose-400/20 bg-rose-500/[0.035]":"border-white/[0.07] bg-[#101827]"}`}><div className="flex items-center justify-between"><span className="text-xs text-muted2">{label}</span><Icon className={`h-4 w-4 ${alert?"text-rose-400":"text-blue-400"}`}/></div><div className="mt-2 text-2xl font-semibold text-white">{value}</div></div>}
function TaskList({tasks,focus,canEdit}:{tasks:any[];focus?:string;canEdit:boolean}){const now=new Date();return <ul className="divide-y divide-white/[0.05] overflow-hidden rounded-2xl border border-white/[0.07] bg-[#0e1624] shadow-sm">{tasks.map(t=>{const overdue=t.dueDate&&new Date(t.dueDate)<now&&!["DONE","CANCELLED"].includes(t.status);return <li key={t.id} className={cn("flex flex-wrap items-center gap-3 px-5 py-3.5 transition hover:bg-white/[0.025]",focus===t.id&&"bg-blue-500/[0.07]")}><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-200">{t.title}</p><p className="mt-1 text-xs text-muted2">{t.case?<Link className="registry-id hover:text-electric" href={`/app/cases/${t.case.id}`}>{t.case.caseNumber}</Link>:null}{t.client?<> · <Link className="hover:text-electric" href={`/app/clients/${t.client.id}`}>{t.client.firstName} {t.client.lastName}</Link></>:null}{t.dueDate?<span className={overdue?" font-medium text-rose-400":""}> · échéance {formatDate(t.dueDate)}{overdue?" (en retard)":""}</span>:null}</p></div><StatusBadge status={t.priority}/>{canEdit?<Link href={`/app/tasks/${t.id}/edit`}><Button size="sm" variant="outline"><Pencil className="mr-1 h-3.5 w-3.5"/>Modifier</Button></Link>:null}<form action={setTaskStatus.bind(null,t.id)} className="flex items-center gap-1.5"><Select name="status" defaultValue={t.status} className="h-8 w-36 text-xs">{["TODO","IN_PROGRESS","WAITING","DONE","CANCELLED"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select><Button size="sm" variant="ghost">OK</Button></form></li>})}</ul>}
