import { requirePermission } from "@/lib/auth";
import { getAccountingStatements, getBalanceSheet } from "@/lib/finance-accounting";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatMoney } from "@/lib/utils";

export const dynamic="force-dynamic";

function parseRange(from?:string,to?:string){const now=new Date();const first=new Date(now.getFullYear(),now.getMonth(),1);const last=new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999);const f=from&&/^\d{4}-\d{2}-\d{2}$/.test(from)?new Date(`${from}T00:00:00`):first;const t=to&&/^\d{4}-\d{2}-\d{2}$/.test(to)?new Date(`${to}T23:59:59.999`):last;return{from:f,to:t};}
function ymd(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}

export default async function AccountingStatementsPage({searchParams}:{searchParams:{from?:string;to?:string}}){
  await requirePermission("ACCOUNTING_READ");
  const range=parseRange(searchParams.from,searchParams.to);
  const [data,balance]=await Promise.all([getAccountingStatements(range.from,range.to),getBalanceSheet(range.to)]);
  return <div className="space-y-5">
    <div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Accounting</p><h1 className="mt-1 text-3xl font-semibold">Financial Statements</h1><p className="mt-1 text-sm text-muted2">P&L, simplified balance sheet and trial balance. Currencies are never combined.</p></div>
    <form className="flex flex-wrap items-end gap-3 rounded-xl border border-line bg-white p-4"><label className="text-xs text-muted2">From<input name="from" type="date" defaultValue={ymd(range.from)} className="mt-1 block rounded-lg border border-line px-3 py-2 text-sm text-ink"/></label><label className="text-xs text-muted2">To<input name="to" type="date" defaultValue={ymd(range.to)} className="mt-1 block rounded-lg border border-line px-3 py-2 text-sm text-ink"/></label><button className="rounded-lg bg-ink px-4 py-2 text-sm font-medium text-white">Apply</button><a href={`/api/finance/accounting/export.csv?from=${ymd(range.from)}&to=${ymd(range.to)}`} className="rounded-lg border border-line bg-white px-4 py-2 text-sm font-medium">Export CSV</a></form>
    <Card><CardHeader><CardTitle>Profit & Loss</CardTitle></CardHeader><CardContent>{data.profitLoss.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.profitLoss.map(r=><div key={r.currency} className="rounded-xl border border-line p-4"><div className="registry-id text-sm">{r.currency}</div><div className="mt-3 space-y-2 text-sm"><Row label="Revenue" value={formatMoney(r.revenue,r.currency)}/><Row label="Refunds / returns" value={`(${formatMoney(r.refunds,r.currency)})`}/><Row label="Operating expenses" value={`(${formatMoney(r.expenses,r.currency)})`}/><div className="border-t border-line pt-2"><Row label="Net income" value={formatMoney(r.netIncome,r.currency)} strong/></div><Row label="Cash movement" value={formatMoney(r.cashMovement,r.currency)}/></div></div>)}</div>:<p className="text-sm text-muted2">No posted accounting activity in this period.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Simplified Balance Sheet as of {ymd(range.to)}</CardTitle></CardHeader><CardContent>{balance.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{balance.map(r=><div key={r.currency} className="rounded-xl border border-line p-4"><div className="registry-id text-sm">{r.currency}</div><div className="mt-3 space-y-2 text-sm"><Row label="Cash & payment accounts" value={formatMoney(r.cash,r.currency)}/><Row label="Accounts payable" value={formatMoney(r.accountsPayable,r.currency)}/><Row label="Retained earnings / current result" value={formatMoney(r.retainedEarnings,r.currency)}/><div className="border-t border-line pt-2"><Row label="Assets" value={formatMoney(r.totalAssets,r.currency)} strong/><Row label="Liabilities + equity" value={formatMoney(r.totalLiabilitiesAndEquity,r.currency)} strong/></div></div></div>)}</div>:<p className="text-sm text-muted2">No balance sheet activity yet.</p>}<p className="mt-3 text-[11px] text-muted2">This simplified statement is activity-based and does not include opening balances, fixed assets, loans, tax liabilities or bank balances entered outside JUN.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Trial Balance</CardTitle></CardHeader><CardContent className="space-y-4">{data.trialBalance.map(group=><div key={group.currency}><div className="mb-2 registry-id text-sm">{group.currency}</div><div className="overflow-x-auto rounded-lg border border-line"><table className="w-full text-sm"><thead className="bg-surface text-xs text-muted2"><tr><th className="px-3 py-2 text-left">Account</th><th className="px-3 py-2 text-right">Debit</th><th className="px-3 py-2 text-right">Credit</th><th className="px-3 py-2 text-right">Balance</th></tr></thead><tbody>{group.accounts.map(a=><tr key={a.code} className="border-t border-line"><td className="px-3 py-2">{a.code} · {a.name}</td><td className="px-3 py-2 text-right">{formatMoney(a.debit,group.currency)}</td><td className="px-3 py-2 text-right">{formatMoney(a.credit,group.currency)}</td><td className="px-3 py-2 text-right">{formatMoney(a.balance,group.currency)}</td></tr>)}</tbody></table></div></div>)}</CardContent></Card>
  </div>;
}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex items-center justify-between gap-4 ${strong?"font-semibold":""}`}><span>{label}</span><span>{value}</span></div>}
