import Link from "next/link";
import { notFound } from "next/navigation";
import { can, requirePermission } from "@/lib/auth";
import { getStatementImport, listBankTransactions, listReconciliationMatches } from "@/lib/finance-bank-reconciliation";
import { listJournalEntries } from "@/lib/finance-accounting";
import { formatDate, formatMoney } from "@/lib/utils";
import { confirmBankMatchAction, ignoreBankTransactionAction, refreshBankSuggestionsAction } from "@/services/finance-bank-reconciliation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const dynamic="force-dynamic";
function cashMovement(lines:{accountCode:string;debit:number;credit:number}[]){return Math.round(lines.filter(l=>l.accountCode==="1000").reduce((s,l)=>s+l.debit-l.credit,0)*100)/100;}

export default async function ReconciliationImportPage({params,searchParams}:{params:{id:string};searchParams:{success?:string;error?:string;status?:string}}){
  const user=await requirePermission("BANK_RECON_READ");const record=await getStatementImport(params.id);if(!record)notFound();
  const [transactions,matches,entries]=await Promise.all([listBankTransactions(record.id),listReconciliationMatches(),listJournalEntries(5000)]);const canApprove=can(user,"BANK_RECON_APPROVE");
  const matchByTx=new Map(matches.map(m=>[m.transactionId,m]));const matched=transactions.filter(t=>t.status==="MATCHED").length;const unresolved=transactions.filter(t=>["UNMATCHED","SUGGESTED"].includes(t.status)).length;
  const filters = [{value:"PENDING",label:"À traiter"},{value:"SUGGESTED",label:"Suggérées"},{value:"MATCHED",label:"Réconciliées"},{value:"IGNORED",label:"Ignorées"},{value:"ALL",label:"Toutes"}];
  const active = filters.some(f=>f.value===searchParams.status) ? searchParams.status! : "PENDING";
  const visible = transactions.filter(tx=>active==="ALL"||(active==="PENDING"?["UNMATCHED","SUGGESTED"].includes(tx.status):tx.status===active));
  const usedEntries = new Set(matches.map(m=>m.journalEntryId));
  const entryById = new Map(entries.map(entry=>[entry.id,entry]));
  const amounts = new Map(entries.map(entry=>[entry.id,cashMovement(entry.lines)]));
  return <div className="min-w-0 space-y-5 pb-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/app/finance/reconciliation" className="text-xs font-medium text-electric">← Rapprochement bancaire</Link><h1 className="mt-2 break-words text-2xl font-semibold sm:text-3xl">{record.bankName} · {record.accountLabel}</h1><p className="mt-1 break-all text-sm text-muted2">{record.fileName} · {record.currency} · {transactions.length} transaction(s) importée(s) · {record.duplicateCount} doublon(s) ignoré(s)</p></div>{canApprove&&<form action={refreshBankSuggestionsAction.bind(null,record.id)}><button className="min-h-11 w-full rounded-xl border border-line bg-white/[0.03] px-3 py-2 text-sm font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric">Actualiser les suggestions</button></form>}</div>
    {searchParams.success&&<div className="rounded-lg border border-emerald-400/20 bg-emerald-500/10 p-3 text-sm text-emerald-200">{searchParams.success}</div>}{searchParams.error&&<div className="rounded-lg border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{searchParams.error}</div>}
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Transactions" value={String(transactions.length)}/><Metric label="Réconciliées" value={String(matched)}/><Metric label="À traiter" value={String(unresolved)}/><Metric label="Résolution" value={`${transactions.length?Math.round(((transactions.length-unresolved)/transactions.length)*100):0}%`}/></div>
    <nav aria-label="Filtrer les transactions" className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">{filters.map(f=><Link key={f.value} href={`?status=${f.value}`} aria-current={active===f.value?"page":undefined} className={`inline-flex min-h-11 items-center justify-center rounded-xl border px-3 py-2 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric ${active===f.value?"border-electric bg-electric text-white":"border-line bg-white/[0.03]"}`}>{f.label}</Link>)}</nav>
    <Card><CardHeader><CardTitle>Transactions bancaires</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted2">{visible.length} transaction(s) affichée(s)</p>{visible.length===0&&<p role="status" className="rounded-xl border border-line p-4 text-sm text-muted2">Aucune transaction dans cette catégorie.</p>}<div className="min-w-0 space-y-3">{visible.slice().sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime()).map(tx=>{
      const confirmed=matchByTx.get(tx.id);
      const suggested=tx.suggestedEntryId&&!usedEntries.has(tx.suggestedEntryId)?entryById.get(tx.suggestedEntryId):null;
      const compatible=canApprove&&!["MATCHED","IGNORED"].includes(tx.status)?entries.filter(e=>!usedEntries.has(e.id)&&e.currency===tx.currency&&Math.abs(amounts.get(e.id)!-tx.amount)<=0.01).sort((a,b)=>{
        if(a.id===tx.suggestedEntryId)return -1;
        if(b.id===tx.suggestedEntryId)return 1;
        return Math.abs(new Date(a.date).getTime()-new Date(tx.date).getTime())-Math.abs(new Date(b.date).getTime()-new Date(tx.date).getTime());
      }).slice(0,12):[];
      return <div key={tx.id} className="min-w-0 break-words rounded-2xl border border-line bg-white/[0.025] p-3 sm:p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{formatMoney(tx.amount,tx.currency)}</span><Status status={tx.status}/>{tx.suggestedScore!==null&&tx.status==="SUGGESTED"&&<span className="text-[11px] text-muted2">score {tx.suggestedScore}%</span>}</div><div className="mt-1 text-sm">{tx.description||"Transaction bancaire"}</div><div className="mt-1 break-all text-xs text-muted2">{formatDate(new Date(tx.date))} · ref {tx.bankReference||"—"}</div></div>{confirmed&&<div className="text-right text-xs"><div className="font-medium text-emerald-200">Réconciliée</div><div className="text-muted2">{confirmed.method==="AUTO_SUGGESTED"?"Suggestion validée":"Rapprochement manuel"} · Δ {confirmed.amountDifference.toFixed(2)}</div></div>}</div>
        {tx.status==="SUGGESTED"&&suggested&&<div className="mt-3 rounded-lg border border-blue-400/20 bg-blue-500/10 p-3 text-xs"><div className="font-medium">Correspondance suggérée</div><div className="mt-1">{suggested.entryNumber} · {suggested.description} · {formatMoney(cashMovement(suggested.lines),suggested.currency)} · {formatDate(new Date(suggested.date))}</div><div className="mt-2 flex flex-wrap gap-3 text-blue-200"><span>Score : {tx.suggestedScore}%</span><span>Écart montant : {formatMoney(tx.amount-cashMovement(suggested.lines),tx.currency)}</span><span>Écart date : {Math.abs(Math.round((new Date(tx.date).getTime()-new Date(suggested.date).getTime())/86400000))} jour(s)</span></div></div>}
        {canApprove&&!["MATCHED","IGNORED"].includes(tx.status)&&<div className="mt-4 grid min-w-0 gap-3">
          <form action={confirmBankMatchAction} className="grid min-w-0 gap-3"><input type="hidden" name="transactionId" value={tx.id}/><label className="min-w-0 w-full text-sm">Écriture comptable<select name="journalEntryId" required defaultValue={compatible.some(e=>e.id===tx.suggestedEntryId)?tx.suggestedEntryId!:""} className="mt-1 min-h-11 w-full min-w-0 max-w-full rounded-xl border border-line bg-surface px-3 py-2 text-base focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric"><option value="">Choisir une écriture compatible</option>{compatible.map(e=><option key={e.id} value={e.id}>{e.entryNumber} · {e.description} · {formatMoney(cashMovement(e.lines),e.currency)} · {formatDate(new Date(e.date))}</option>)}</select></label><label className="min-w-0 w-full text-sm">Note de vérification<input name="note" className="mt-1 min-h-11 w-full min-w-0 max-w-full rounded-xl border border-line bg-surface px-3 py-2 text-base focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric" placeholder="Note facultative"/></label><button className="min-h-11 w-full rounded-xl bg-electric px-3 py-2 text-sm font-medium text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric">Confirmer le rapprochement</button></form>
          <form action={ignoreBankTransactionAction}><input type="hidden" name="transactionId" value={tx.id}/><button className="min-h-11 w-full rounded-xl border border-line bg-white/[0.03] px-3 py-2 text-sm font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-electric">Ignorer</button></form>
        </div>}
      </div>})}</div></CardContent></Card>
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-line bg-white/[0.025] p-3 sm:p-4"><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>}
function Status({status}:{status:"MATCHED"|"SUGGESTED"|"IGNORED"|"UNMATCHED"}){const cls=status==="MATCHED"?"bg-emerald-500/10 text-emerald-200":status==="SUGGESTED"?"bg-blue-500/10 text-blue-200":status==="IGNORED"?"bg-slate-500/10 text-slate-200":"bg-amber-500/10 text-amber-200";return <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${cls}`}>{{MATCHED:"Réconciliée",SUGGESTED:"Suggérée",IGNORED:"Ignorée",UNMATCHED:"À traiter"}[status]||status}</span>}
