import Link from "next/link";
import { notFound } from "next/navigation";
import { can, requirePermission } from "@/lib/auth";
import { budgetAnnualTotal, budgetPlanAnnualTotals, getBudgetAlerts, getBudgetPlan, getBudgetScenarios, getBudgetVariance } from "@/lib/finance-budgeting";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { approveBudgetPlanAction, cloneBudgetPlanAction, setBudgetPlanStatusAction, updateBudgetPlanAction } from "@/services/finance-budgeting";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle, Copy, LockKeyhole, Save, ShieldCheck } from "lucide-react";

export const dynamic = "force-dynamic";
const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

export default async function BudgetDetailPage({ params, searchParams }: { params: { id: string }; searchParams: { success?: string; error?: string } }) {
  const user = await requirePermission("BUDGET_READ");
  const plan = await getBudgetPlan(params.id); if (!plan) notFound();
  const now = new Date(); const throughMonth = now.getUTCFullYear() === plan.year ? now.getUTCMonth() : now.getUTCFullYear() > plan.year ? 11 : -1;
  const [variance, scenarios, alerts] = await Promise.all([getBudgetVariance(plan, throughMonth), getBudgetScenarios(plan, now), getBudgetAlerts(plan, throughMonth)]);
  const annual = budgetPlanAnnualTotals(plan); const editable = plan.status === "DRAFT" && can(user,"BUDGET_CREATE"); const approver = can(user,"BUDGET_APPROVE");
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link href="/app/finance/budgeting" className="text-xs font-medium text-electric">← Budgeting</Link><h1 className="mt-2 text-3xl font-semibold">{plan.name}</h1><p className="mt-1 text-sm text-muted2">{plan.year} · {plan.currency} · {plan.status} · updated {formatDateTime(new Date(plan.updatedAt))}</p></div><div className="flex flex-wrap gap-2"><a href={`/api/finance/budgeting/${plan.id}/export.csv`} className="rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium">Export CSV</a>{can(user,"BUDGET_CREATE")&&<form action={cloneBudgetPlanAction.bind(null,plan.id)}><button className="inline-flex items-center gap-2 rounded-lg border border-line bg-white px-3 py-2 text-xs font-medium"><Copy className="h-4 w-4"/>Create revision</button></form>}</div></div>
    {searchParams.success&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{searchParams.success}</div>}{searchParams.error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{searchParams.error}</div>}
    <div className="grid gap-3 md:grid-cols-4"><Metric label="Annual revenue" value={formatMoney(annual.revenue,plan.currency)} hint="Approved target total"/><Metric label="Annual costs" value={formatMoney(annual.costs,plan.currency)} hint="Refunds + operating expenses"/><Metric label="Budget net" value={formatMoney(annual.net,plan.currency)} hint="Revenue minus planned costs"/><Metric label="Variance alerts" value={String(alerts.length)} hint={throughMonth<0?"Budget has not started":"YTD categories needing attention"}/></div>

    <Card><CardHeader><CardTitle>Budget vs Actual {throughMonth>=0?`through ${MONTHS[throughMonth]} ${plan.year}`:`— starts ${plan.year}`}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b border-line text-left text-xs text-muted2"><th className="px-2 py-2">Category</th><th className="px-2 py-2 text-right">Budget</th><th className="px-2 py-2 text-right">Actual</th><th className="px-2 py-2 text-right">Variance</th><th className="px-2 py-2 text-right">Use</th><th className="px-2 py-2">Status</th></tr></thead><tbody>{variance.rows.map(row=><tr key={row.category} className="border-b border-line/70"><td className="px-2 py-2 font-medium">{row.label}</td><td className="px-2 py-2 text-right">{formatMoney(row.budget,plan.currency)}</td><td className="px-2 py-2 text-right">{formatMoney(row.actual,plan.currency)}</td><td className={`px-2 py-2 text-right font-medium ${row.favorableVariance>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(row.favorableVariance,plan.currency)}</td><td className="px-2 py-2 text-right">{row.utilizationPercent===null?"n/a":`${row.utilizationPercent}%`}</td><td className="px-2 py-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${row.status==="ON_TRACK"?"bg-emerald-50 text-emerald-700":row.status==="WATCH"?"bg-amber-50 text-amber-700":"bg-red-50 text-red-700"}`}>{row.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>Best / Base / Worst Case</CardTitle></CardHeader><CardContent className="space-y-2">{scenarios.map(s=><div key={s.scenario} className="grid grid-cols-4 items-center gap-2 rounded-lg border border-line px-3 py-3 text-sm"><div className="font-semibold">{s.scenario}</div><div className="text-right"><div className="text-[11px] text-muted2">Revenue</div>{formatMoney(s.revenue,plan.currency)}</div><div className="text-right"><div className="text-[11px] text-muted2">Costs</div>{formatMoney(s.costs,plan.currency)}</div><div className={`text-right font-semibold ${s.net>=0?"text-emerald-700":"text-red-700"}`}><div className="text-[11px] text-muted2">Net</div>{formatMoney(s.net,plan.currency)}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Budget alerts</CardTitle></CardHeader><CardContent>{alerts.length?<div className="space-y-2">{alerts.slice(0,10).map(a=><div key={a.category} className="flex items-center justify-between gap-3 rounded-lg border border-line p-3"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-600"/><div><div className="text-sm font-medium">{a.label}</div><div className="text-xs text-muted2">{a.status.replaceAll("_"," ")}</div></div></div><div className={a.favorableVariance>=0?"text-sm font-semibold text-emerald-700":"text-sm font-semibold text-red-700"}>{formatMoney(a.favorableVariance,plan.currency)}</div></div>)}</div>:<p className="text-sm text-muted2">No budget variance alert for this period.</p>}</CardContent></Card></div>

    <form action={updateBudgetPlanAction.bind(null,plan.id)} className="space-y-4">
      <Card><CardHeader><CardTitle>Monthly budget allocations</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Budget name<input name="name" defaultValue={plan.name} disabled={!editable} className="mt-1 w-full rounded-lg border border-line px-3 py-2 disabled:bg-surface"/></label><label className="text-sm">Planning note<input name="note" defaultValue={plan.note} disabled={!editable} className="mt-1 w-full rounded-lg border border-line px-3 py-2 disabled:bg-surface"/></label></div><div className="overflow-x-auto"><table className="min-w-[1500px] w-full text-xs"><thead><tr className="border-b border-line"><th className="sticky left-0 bg-white px-2 py-2 text-left">Category</th>{MONTHS.map(m=><th key={m} className="px-2 py-2 text-right">{m}</th>)}<th className="px-2 py-2 text-right">Annual</th></tr></thead><tbody>{plan.lines.map(line=><tr key={line.category} className="border-b border-line/70"><td className="sticky left-0 bg-white px-2 py-2 font-medium">{line.label}</td>{line.monthly.map((value,month)=><td key={month} className="px-1 py-1"><input name={`budget_${line.category}_${month}`} type="number" min="0" step="0.01" defaultValue={value} disabled={!editable} className="w-24 rounded border border-line px-2 py-1 text-right disabled:bg-surface"/></td>)}<td className="px-2 py-2 text-right font-semibold">{formatMoney(budgetAnnualTotal(line),plan.currency)}</td></tr>)}</tbody></table></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Scenario assumptions</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Scenario label="Best revenue multiplier" name="bestRevenueMultiplier" value={plan.assumptions.bestRevenueMultiplier} disabled={!editable}/><Scenario label="Best cost multiplier" name="bestCostMultiplier" value={plan.assumptions.bestCostMultiplier} disabled={!editable}/><Scenario label="Worst revenue multiplier" name="worstRevenueMultiplier" value={plan.assumptions.worstRevenueMultiplier} disabled={!editable}/><Scenario label="Worst cost multiplier" name="worstCostMultiplier" value={plan.assumptions.worstCostMultiplier} disabled={!editable}/></div>{editable&&<button className="mt-4 inline-flex items-center gap-2 rounded-lg bg-ink px-4 py-2 text-sm font-medium text-white"><Save className="h-4 w-4"/>Save budget</button>}</CardContent></Card>
    </form>

    {(approver||plan.status!=="DRAFT")&&<Card><CardHeader><CardTitle>Governance</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{approver&&plan.status==="DRAFT"&&<form action={approveBudgetPlanAction.bind(null,plan.id)}><button className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white"><ShieldCheck className="h-4 w-4"/>Approve budget</button></form>}{approver&&plan.status==="APPROVED"&&<form action={setBudgetPlanStatusAction.bind(null,plan.id)}><input type="hidden" name="status" value="LOCKED"/><button className="inline-flex items-center gap-2 rounded-lg bg-ink px-4 py-2 text-sm font-medium text-white"><LockKeyhole className="h-4 w-4"/>Lock budget</button></form>}{approver&&["DRAFT","APPROVED","LOCKED"].includes(plan.status)&&<form action={setBudgetPlanStatusAction.bind(null,plan.id)}><input type="hidden" name="status" value="ARCHIVED"/><button className="rounded-lg border border-line bg-white px-4 py-2 text-sm font-medium">Archive</button></form>}<div className="self-center text-xs text-muted2">Approved budgets are immutable. Revisions are cloned into a new DRAFT plan.</div></CardContent></Card>}
  </div>;
}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
function Scenario({label,name,value,disabled}:{label:string;name:string;value:number;disabled:boolean}){return <label className="text-xs">{label}<input name={name} type="number" step="0.01" min="0.01" max="5" defaultValue={value} disabled={disabled} className="mt-1 w-full rounded-lg border border-line px-3 py-2 disabled:bg-surface"/></label>}
