import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getTreasuryStore, projectPerformance, treasuryByCurrency, treasuryReconciliationSummary } from "@/lib/company-funds";
import { formatDateTime, formatMoney } from "@/lib/utils";
import {
  configureTreasuryAccountConnectionAction, createProjectIntegrationAction, createTreasuryAccountAction, createTreasuryInvestmentAction,
  createTreasuryLoanAction, createTreasuryPartnerAction, createTreasurySourceAction, resolveTreasuryReconciliationAction,
  updateTreasuryAccountBalanceAction,
} from "@/services/company-funds";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Landmark, Link2, PiggyBank, BriefcaseBusiness, HandCoins, UsersRound, RefreshCw, ShieldCheck, Scale, KeyRound } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function CompanyFundsPage(){
  const user=await requireUser(); if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
  const [store,cases]=await Promise.all([getTreasuryStore(),prisma.case.findMany({orderBy:{updatedAt:"desc"},take:300,select:{id:true,caseNumber:true,title:true}})]);
  const currencies=treasuryByCurrency(store); const projects=projectPerformance(store); const reconciliation=treasuryReconciliationSummary(store);
  const staleAccounts=store.accounts.filter(a=>a.active&&a.dailyUpdateRequired&&(!a.lastSyncAt||Date.now()-new Date(a.lastSyncAt).getTime()>36*60*60*1000));
  const accountMap=new Map(store.accounts.map(a=>[a.id,a]));
  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Super Admin · Trésorerie stratégique</p><h1 className="mt-1 text-3xl font-semibold">Fonds de l’entreprise</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Vue confidentielle de tous les comptes, sources de financement, projets, investissements, partenaires, prêts et flux financiers de JUN dans tous les pays.</p></div><div className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><ShieldCheck className="mr-1 inline h-4 w-4"/>SUPER ADMIN ONLY</div></div>

    <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="flex gap-3"><RefreshCw className="h-5 w-5 text-blue-700"/><div><div className="font-semibold text-blue-900">Synchronisation centrale</div><p className="mt-1 text-xs leading-relaxed text-blue-800">Les comptes connectés utilisent <code>/api/company-funds/account-sync</code>. Les projets utilisent <code>/api/company-funds/project-sync</code>. Chaque synchro de compte crée un snapshot et une réconciliation entre le solde attendu du Hub et le solde réellement reporté par la banque, wallet ou processeur.</p>{staleAccounts.length?<p className="mt-2 text-xs font-semibold text-amber-700">⚠ {staleAccounts.length} compte(s) nécessitent une mise à jour.</p>:<p className="mt-2 text-xs font-semibold text-emerald-700">✓ Tous les comptes à mise à jour quotidienne sont à jour.</p>}</div></div></div>

    <div className="grid gap-3 md:grid-cols-5"><Metric icon={Landmark} label="Comptes actifs" value={String(store.accounts.filter(a=>a.active).length)} hint={`${store.accounts.filter(a=>a.connectionMode==="CONNECTED").length} connecté(s)`}/><Metric icon={BriefcaseBusiness} label="Projets connectés" value={String(store.integrations.filter(i=>i.enabled).length)} hint={`${store.projectCashflows.length} flux synchronisés`}/><Metric icon={Scale} label="À réconcilier" value={String(reconciliation.reviewCount)} hint={`${reconciliation.matchedCount} rapproché(s)`}/><Metric icon={UsersRound} label="Partenaires" value={String(store.partners.filter(p=>p.status==="ACTIVE").length)} hint="Capital & partage de profit"/><Metric icon={HandCoins} label="Prêts actifs" value={String(store.loans.filter(l=>l.status==="ACTIVE").length)} hint="Détails complets suivis"/></div>

    <Card><CardHeader><CardTitle>Position financière par devise</CardTitle></CardHeader><CardContent>{currencies.length?<div className="grid gap-3 lg:grid-cols-2">{currencies.map(c=><div key={c.currency} className="rounded-xl border border-line p-4"><div className="mb-3 flex items-center justify-between"><span className="text-lg font-semibold">{c.currency}</span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${c.projectProfit>=0?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>Profit projets {formatMoney(c.projectProfit,c.currency)}</span></div><div className="grid grid-cols-2 gap-3 text-sm"><Kpi label="Liquidités comptes" value={formatMoney(c.cash,c.currency)}/><Kpi label="Entrées projets" value={formatMoney(c.projectIn,c.currency)}/><Kpi label="Sorties projets" value={formatMoney(c.projectOut,c.currency)}/><Kpi label="Prêts restant dus" value={formatMoney(c.loanOutstanding,c.currency)}/><Kpi label="Investissements" value={formatMoney(c.invested,c.currency)}/><Kpi label="Profit projets" value={formatMoney(c.projectProfit,c.currency)}/></div></div>)}</div>:<p className="text-sm text-muted2">Aucune donnée financière enregistrée.</p>}</CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5"/>Comptes de l’entreprise</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-xl bg-surface p-3 text-xs leading-relaxed text-muted2"><strong>Compte manuel :</strong> le Super Admin confirme le solde chaque jour. <strong>Compte connecté :</strong> le fournisseur envoie automatiquement le solde au Hub avec une clé secrète dédiée. Les clés sont stockées uniquement sous forme SHA-256.</div><form action={createTreasuryAccountAction} className="grid gap-3 rounded-xl border border-line p-4 md:grid-cols-4"><Input name="name" label="Nom du compte" required/><Input name="country" label="Pays" required/><Input name="institution" label="Banque / institution" required/><label className="text-xs">Type<select name="type" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option>BANK</option><option>WALLET</option><option>CASH</option><option>PROCESSOR</option><option>OTHER</option></select></label><Input name="currency" label="Devise" defaultValue="USD" required/><Input name="balance" label="Solde actuel" type="number" defaultValue="0"/><label className="text-xs">Mode<select name="connectionMode" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="MANUAL">Manuel</option><option value="CONNECTED">Connecté</option></select></label><Input name="provider" label="Fournisseur/API"/><Input name="externalRef" label="Référence externe"/><Input name="connectionKey" label="Clé connexion (20+ car.)"/><label className="flex items-center gap-2 text-xs"><input name="dailyUpdateRequired" type="checkbox" defaultChecked/>Mise à jour quotidienne requise</label><Input name="note" label="Note"/><button className="rounded-lg bg-ink px-3 py-2 text-sm font-medium text-white">Ajouter le compte</button></form>
      <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Compte</th><th className="p-2">Pays</th><th className="p-2">Institution</th><th className="p-2">Mode</th><th className="p-2 text-right">Solde</th><th className="p-2">Dernière synchro</th><th className="p-2">Solde manuel</th><th className="p-2">Connexion API</th></tr></thead><tbody>{store.accounts.map(a=><tr key={a.id} className="border-b border-line/70 align-top"><td className="p-2 font-medium">{a.name}<div className="text-[10px] text-muted2">ID API: {a.id}</div></td><td className="p-2">{a.country}</td><td className="p-2">{a.institution}<div className="text-[10px] text-muted2">{a.provider||"—"}</div></td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] ${a.connectionMode==="CONNECTED"?"bg-blue-50 text-blue-700":"bg-surface"}`}>{a.connectionMode}</span></td><td className="p-2 text-right font-semibold">{formatMoney(a.balance,a.currency)}</td><td className="p-2 text-xs">{a.lastSyncAt?formatDateTime(a.lastSyncAt):"Jamais"}</td><td className="p-2"><form action={updateTreasuryAccountBalanceAction.bind(null,a.id)} className="flex gap-1"><input name="balance" type="number" step="0.01" defaultValue={a.balance} className="w-28 rounded border border-line px-2 py-1 text-xs"/><button className="rounded border border-line px-2 py-1 text-xs">Valider</button></form></td><td className="p-2"><form action={configureTreasuryAccountConnectionAction.bind(null,a.id)} className="flex gap-1"><input name="connectionKey" type="password" placeholder={a.connectionKeyHash?"Clé configurée · remplacer":"Nouvelle clé 20+"} className="w-40 rounded border border-line px-2 py-1 text-xs"/><button className="rounded border border-line px-2 py-1 text-xs"><KeyRound className="h-3.5 w-3.5"/></button></form></td></tr>)}</tbody></table></div>
    </CardContent></Card>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Scale className="h-5 w-5"/>Réconciliation des comptes</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Kpi label="À vérifier" value={String(reconciliation.reviewCount)}/><Kpi label="Rapprochements exacts" value={String(reconciliation.matchedCount)}/><Kpi label="Résolus" value={String(reconciliation.resolvedCount)}/></div><div className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">À chaque synchronisation bancaire, JUN compare le <strong>solde attendu dans le Hub</strong> avec le <strong>solde reporté par le fournisseur</strong>. Toute différence est conservée pour contrôle et audit.</div>{reconciliation.recent.length?<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Compte</th><th className="p-2 text-right">Attendu</th><th className="p-2 text-right">Reporté</th><th className="p-2 text-right">Différence</th><th className="p-2">Statut</th><th className="p-2">Date</th><th className="p-2">Contrôle</th></tr></thead><tbody>{reconciliation.recent.map(r=>{const a=accountMap.get(r.accountId);return <tr key={r.id} className="border-b border-line/70"><td className="p-2 font-medium">{a?.name||"Compte supprimé"}</td><td className="p-2 text-right">{formatMoney(r.expectedBalance,a?.currency||"USD")}</td><td className="p-2 text-right">{formatMoney(r.reportedBalance,a?.currency||"USD")}</td><td className={`p-2 text-right font-semibold ${Math.abs(r.difference)<.01?"text-emerald-700":"text-red-700"}`}>{formatMoney(r.difference,a?.currency||"USD")}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${r.status==="MATCHED"?"bg-emerald-50 text-emerald-700":r.status==="REVIEW"?"bg-red-50 text-red-700":"bg-blue-50 text-blue-700"}`}>{r.status}</span></td><td className="p-2 text-xs">{formatDateTime(r.periodEnd)}</td><td className="p-2">{r.status==="REVIEW"?<form action={resolveTreasuryReconciliationAction.bind(null,r.id)} className="flex gap-1"><input name="note" placeholder="Explication" className="w-36 rounded border border-line px-2 py-1 text-xs"/><button className="rounded border border-line px-2 py-1 text-xs">Résoudre</button></form>:<span className="text-xs text-muted2">{r.note||"—"}</span>}</td></tr>})}</tbody></table></div>:<p className="text-sm text-muted2">Aucune réconciliation enregistrée pour le moment.</p>}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Sources financières</CardTitle></CardHeader><CardContent className="space-y-3"><form action={createTreasurySourceAction} className="grid gap-2 md:grid-cols-2"><Input name="name" label="Source" required/><label className="text-xs">Type<select name="kind" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option>REVENUE</option><option>OWNER_CAPITAL</option><option>PARTNER_CAPITAL</option><option>INVESTMENT</option><option>LOAN</option><option>OTHER</option></select></label><Input name="country" label="Pays"/><Input name="currency" label="Devise" defaultValue="USD" required/><Input name="amount" label="Montant" type="number" required/><Input name="receivedAt" label="Date reçue" type="date"/><label className="text-xs">Compte<select name="accountId" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="">—</option>{store.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label><Input name="note" label="Note"/><button className="rounded-lg bg-ink px-3 py-2 text-sm text-white">Ajouter</button></form>{store.sources.slice(0,8).map(s=><Row key={s.id} title={s.name} sub={`${s.kind} · ${s.country}`} value={formatMoney(s.amount,s.currency)}/>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Partenaires</CardTitle></CardHeader><CardContent className="space-y-3"><form action={createTreasuryPartnerAction} className="grid gap-2 md:grid-cols-2"><Input name="name" label="Nom / société" required/><label className="text-xs">Type<select name="type" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option>INDIVIDUAL</option><option>COMPANY</option></select></label><Input name="country" label="Pays"/><Input name="email" label="Email"/><Input name="phone" label="Téléphone"/><Input name="currency" label="Devise" defaultValue="USD"/><Input name="capitalContributed" label="Capital apporté" type="number" defaultValue="0"/><Input name="ownershipPercent" label="% propriété" type="number" defaultValue="0"/><Input name="profitSharePercent" label="% partage profit" type="number" defaultValue="0"/><Input name="note" label="Conditions / notes"/><button className="rounded-lg bg-ink px-3 py-2 text-sm text-white">Ajouter</button></form>{store.partners.map(p=><Row key={p.id} title={p.name} sub={`${p.country} · propriété ${p.ownershipPercent}% · profit ${p.profitSharePercent}%`} value={formatMoney(p.capitalContributed,p.currency)}/>)}</CardContent></Card>
    </div>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Prêts</CardTitle></CardHeader><CardContent className="space-y-3"><form action={createTreasuryLoanAction} className="grid gap-2 md:grid-cols-2"><Input name="lender" label="Prêteur" required/><Input name="borrower" label="Emprunteur" defaultValue="JUN CREATIF AND TRAVEL LLC" required/><Input name="country" label="Pays / juridiction"/><Input name="currency" label="Devise" defaultValue="USD"/><Input name="principal" label="Principal" type="number" required/><Input name="outstandingBalance" label="Solde restant" type="number"/><Input name="interestRate" label="Taux intérêt %" type="number" defaultValue="0"/><Input name="paymentFrequency" label="Fréquence paiement"/><Input name="startDate" label="Date début" type="date"/><Input name="dueDate" label="Échéance" type="date"/><Input name="collateral" label="Garantie / collateral"/><Input name="guarantor" label="Garant"/><Input name="purpose" label="Objet du prêt"/><Input name="note" label="Conditions complètes"/><button className="rounded-lg bg-ink px-3 py-2 text-sm text-white">Ajouter le prêt</button></form>{store.loans.map(l=><Row key={l.id} title={`${l.lender} → ${l.borrower}`} sub={`${l.interestRate}% · échéance ${l.dueDate||"—"} · ${l.status}`} value={`${formatMoney(l.outstandingBalance,l.currency)} restant`}/>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Investissements</CardTitle></CardHeader><CardContent className="space-y-3"><form action={createTreasuryInvestmentAction} className="grid gap-2 md:grid-cols-2"><Input name="name" label="Investissement" required/><Input name="counterparty" label="Contrepartie"/><Input name="country" label="Pays"/><Input name="currency" label="Devise" defaultValue="USD"/><Input name="amount" label="Montant investi" type="number" required/><Input name="investedAt" label="Date" type="date"/><Input name="expectedReturnPercent" label="Rendement attendu %" type="number" defaultValue="0"/><label className="text-xs">Projet associé<select name="projectIntegrationId" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="">—</option>{store.integrations.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><Input name="note" label="Stratégie / conditions"/><button className="rounded-lg bg-ink px-3 py-2 text-sm text-white">Ajouter</button></form>{store.investments.map(i=><Row key={i.id} title={i.name} sub={`${i.country} · rendement cible ${i.expectedReturnPercent}% · ${i.status}`} value={formatMoney(i.amount,i.currency)}/>)}</CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Link2 className="h-5 w-5"/>API projets & profit synchronisé</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-xl bg-surface p-3 text-xs leading-relaxed text-muted2"><strong>Projet :</strong> POST <code>/api/company-funds/project-sync</code> avec <code>x-jun-project-code</code> + <code>x-jun-project-key</code>. <strong>Compte :</strong> POST <code>/api/company-funds/account-sync</code> avec <code>x-jun-account-id</code> + <code>x-jun-account-key</code>. Les appels sont idempotents via <code>externalId</code>.</div>
      <form action={createProjectIntegrationAction} className="grid gap-3 rounded-xl border border-line p-4 md:grid-cols-4"><Input name="code" label="Code projet unique" required/><Input name="name" label="Nom projet" required/><Input name="country" label="Pays"/><Input name="currency" label="Devise" defaultValue="USD" required/><label className="text-xs md:col-span-2">Dossier JUN lié<select name="caseId" className="mt-1 w-full rounded-lg border border-line px-3 py-2"><option value="">— Aucun —</option>{cases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} · {c.title}</option>)}</select></label><Input name="apiKey" label="Clé API secrète (20+ caractères)" required/><button className="rounded-lg bg-ink px-3 py-2 text-sm font-medium text-white">Connecter le projet</button></form>
      <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Projet</th><th className="p-2">Pays</th><th className="p-2 text-right">Entrées</th><th className="p-2 text-right">Sorties</th><th className="p-2 text-right">Profit</th><th className="p-2 text-right">Marge</th><th className="p-2">Dernière synchro</th></tr></thead><tbody>{projects.map(p=><tr key={p.id} className="border-b border-line/70"><td className="p-2"><div className="font-medium">{p.name}</div><div className="text-[10px] text-muted2">{p.code} · {p.transactionCount} flux</div></td><td className="p-2">{p.country}</td><td className="p-2 text-right">{formatMoney(p.income,p.currency)}</td><td className="p-2 text-right">{formatMoney(p.expense,p.currency)}</td><td className={`p-2 text-right font-semibold ${p.profit>=0?"text-emerald-700":"text-red-700"}`}>{formatMoney(p.profit,p.currency)}</td><td className="p-2 text-right">{p.margin===null?"—":`${p.margin}%`}</td><td className="p-2 text-xs">{p.lastSyncAt?formatDateTime(p.lastSyncAt):"Jamais"}</td></tr>)}</tbody></table></div>
    </CardContent></Card>
  </div>;
}

function Metric({icon:Icon,label,value,hint}:{icon:typeof PiggyBank;label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-surface p-3"><div className="text-[10px] uppercase tracking-wide text-muted2">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}
function Row({title,sub,value}:{title:string;sub:string;value:string}){return <div className="flex items-center justify-between gap-3 rounded-lg border border-line px-3 py-2"><div><div className="text-sm font-medium">{title}</div><div className="text-[11px] text-muted2">{sub}</div></div><div className="text-sm font-semibold">{value}</div></div>}
function Input({name,label,type="text",defaultValue,required=false}:{name:string;label:string;type?:string;defaultValue?:string;required?:boolean}){return <label className="text-xs">{label}<input name={name} type={type} step={type==="number"?"0.01":undefined} defaultValue={defaultValue} required={required} className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm"/></label>}
