import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser, can } from "@/lib/auth";
import { getCaseOperations, caseOperationFacts } from "@/lib/case-operations";
import { addCaseMilestone, updateCaseMilestone, deleteCaseMilestone } from "@/services/case-operations";
import { updateCaseStatus } from "@/services/cases";
import { setTaskStatus } from "@/services/tasks";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge, Badge } from "@/components/ui/badge";
import { Input, Select, Textarea } from "@/components/ui/input";
import { formatDate, formatDateTime } from "@/lib/utils";
import { AlertTriangle, CheckCircle2, Clock3, ListChecks, Milestone, UserRound } from "lucide-react";

export const dynamic="force-dynamic";
const CASE_STATUSES=["OPEN","IN_PROGRESS","WAITING_CLIENT","WAITING_INTERNAL","COMPLETED","CANCELLED","ARCHIVED"];
const STEP_STATUSES=["TODO","IN_PROGRESS","WAITING","DONE","CANCELLED"];

export default async function CaseOperationsPage({params}:{params:Promise<{id:string}>|{id:string}}){
 const user=await requireUser();if(!can(user,"CASE_READ"))redirect("/app/forbidden");const {id}=await Promise.resolve(params);
 const [c,state,users]=await Promise.all([
  prisma.case.findUnique({where:{id},include:{client:true,owner:true,tasks:{include:{assignee:true},orderBy:[{dueDate:"asc"},{createdAt:"asc"}]},activities:{include:{user:true},orderBy:{createdAt:"desc"},take:10}}}),
  getCaseOperations(id),
  prisma.user.findMany({where:{status:"ACTIVE"},orderBy:[{firstName:"asc"},{lastName:"asc"}],select:{id:true,firstName:true,lastName:true,role:true}})
 ]);if(!c)notFound();
 const facts=caseOperationFacts(state.milestones,c.tasks);const ownerMap=new Map(users.map(u=>[u.id,`${u.firstName} ${u.lastName}`]));
 const blocked=facts.blockedMilestones.length;const overdue=facts.overdueMilestones.length+facts.overdueTasks.length;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/app/cases/${id}/dashboard`} className="text-sm text-muted2 hover:text-electric">← Case 360</Link><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">Operations</h1><StatusBadge status={c.status}/><StatusBadge status={c.priority}/></div><p className="mt-1 text-sm text-muted2">{c.caseNumber} · {c.title} · {c.client.firstName} {c.client.lastName}</p></div><div className="flex flex-wrap gap-2"><Link href={`/app/cases/${id}`}><Button variant="outline">Full record</Button></Link>{can(user,"TASK_CREATE")?<Link href={`/app/tasks/new?caseId=${id}&clientId=${c.clientId}`}><Button variant="primary">New task</Button></Link>:null}</div></div>

  {(blocked||overdue)?<div className="flex items-start gap-2 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><div><strong>Operational attention required.</strong> {blocked?`${blocked} blocked milestone(s). `:""}{overdue?`${overdue} overdue task/milestone(s).`:""}</div></div>:null}

  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={ListChecks} label="Overall progress" value={`${facts.progress}%`} sub={`${facts.taskDone} task(s) + ${facts.milestoneDone} milestone(s) done`}/><Metric icon={Milestone} label="Active milestones" value={String(facts.milestoneActive.length)} sub={`${state.milestones.length} total`}/><Metric icon={Clock3} label="Open tasks" value={String(facts.taskActive.length)} sub={`${facts.overdueTasks.length} overdue`}/><Metric icon={AlertTriangle} label="Blocked" value={String(blocked)} sub={`${overdue} overdue item(s)`}/><Metric icon={UserRound} label="Case owner" value={c.owner?`${c.owner.firstName} ${c.owner.lastName}`:"Unassigned"} sub={`Due ${formatDate(c.dueDate)}`}/></div>

  <Card><CardHeader><div><CardTitle>Case status & control</CardTitle><p className="mt-1 text-xs text-muted2">Operational status should reflect what is actually happening in the case.</p></div></CardHeader><CardContent className="flex flex-wrap items-end gap-3">{can(user,"CASE_UPDATE")?<form action={updateCaseStatus.bind(null,id)} className="flex flex-wrap items-end gap-2"><div><label className="mb-1 block text-xs text-muted2">Case status</label><Select name="status" defaultValue={c.status} className="w-52">{CASE_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select></div><Button variant="outline">Update status</Button></form>:<StatusBadge status={c.status}/>}<div className="text-xs text-muted2">Priority: <strong>{c.priority}</strong> · Due: <strong>{formatDate(c.dueDate)}</strong></div></CardContent></Card>

  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
   <div className="space-y-5">
    <Card><CardHeader><div><CardTitle>Operational milestones</CardTitle><p className="mt-1 text-xs text-muted2">Major stages that must be completed before the service can close.</p></div></CardHeader><CardContent className="space-y-3">{state.milestones.length?state.milestones.map(m=>{const late=Boolean(m.dueDate&&new Date(m.dueDate).getTime()<Date.now()&&!['DONE','CANCELLED'].includes(m.status));return <div key={m.id} className={`rounded-xl border p-4 ${m.blocker&& !['DONE','CANCELLED'].includes(m.status)?"border-amber-300 bg-amber-50/50":"border-line"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{m.title}</p><StatusBadge status={m.status}/>{late?<Badge className="bg-red-100 text-red-700">OVERDUE</Badge>:null}{m.blocker&&!['DONE','CANCELLED'].includes(m.status)?<Badge className="bg-amber-100 text-amber-800">BLOCKED</Badge>:null}</div>{m.description?<p className="mt-1 text-sm text-muted2">{m.description}</p>:null}<p className="mt-2 text-xs text-muted2">Owner: {m.ownerId?ownerMap.get(m.ownerId)||"Unknown":"Unassigned"} · Due: {m.dueDate?formatDate(new Date(m.dueDate)):"—"}</p>{m.blocker?<p className="mt-2 text-sm text-amber-800"><strong>Blocker:</strong> {m.blocker}</p>:null}</div></div>{can(user,"CASE_UPDATE")?<details className="mt-3"><summary className="cursor-pointer text-xs text-electric">Update milestone</summary><form action={updateCaseMilestone.bind(null,id,m.id)} className="mt-3 grid gap-2 sm:grid-cols-2"><Input name="title" defaultValue={m.title} required/><Select name="status" defaultValue={m.status}>{STEP_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select><Select name="ownerId" defaultValue={m.ownerId||""}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName} · {u.role}</option>)}</Select><Input name="dueDate" type="date" defaultValue={m.dueDate?.slice(0,10)||""}/><Textarea name="description" defaultValue={m.description} rows={2} className="sm:col-span-2"/><Textarea name="blocker" defaultValue={m.blocker} rows={2} placeholder="Blocker / reason this stage cannot advance" className="sm:col-span-2"/><div className="flex gap-2 sm:col-span-2"><Button variant="outline">Save milestone</Button><button formAction={deleteCaseMilestone.bind(null,id,m.id)} className="text-xs text-red-600 hover:underline">Remove milestone</button></div></form></details>:null}</div>}) : <p className="text-sm text-muted2">No milestone defined yet.</p>}
    {can(user,"CASE_UPDATE")?<details className="rounded-xl border border-dashed border-line p-4"><summary className="cursor-pointer text-sm font-medium text-electric">+ Add milestone</summary><form action={addCaseMilestone.bind(null,id)} className="mt-3 grid gap-2 sm:grid-cols-2"><Input name="title" required placeholder="Example: Receive client documents"/><Select name="ownerId" defaultValue=""><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName} · {u.role}</option>)}</Select><Input name="dueDate" type="date"/><Textarea name="description" rows={2} placeholder="What must be completed in this stage?" className="sm:col-span-2"/><Button className="sm:col-span-2" variant="outline">Add milestone</Button></form></details>:null}</CardContent></Card>

    <Card><CardHeader><div><CardTitle>Tasks</CardTitle><p className="mt-1 text-xs text-muted2">Day-to-day actions required to move this case forward.</p></div></CardHeader><CardContent className="p-0">{c.tasks.length?<ul className="divide-y divide-line">{c.tasks.map(t=>{const late=Boolean(t.dueDate&&t.dueDate.getTime()<Date.now()&&!['DONE','CANCELLED'].includes(t.status));return <li key={t.id} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-sm font-medium">{t.title}</p>{late?<Badge className="bg-red-100 text-red-700">OVERDUE</Badge>:null}</div><p className="mt-1 text-xs text-muted2">{t.assignee?`${t.assignee.firstName} ${t.assignee.lastName}`:"Unassigned"} · due {formatDate(t.dueDate)} · {t.priority}</p></div><div className="flex items-center gap-2"><StatusBadge status={t.status}/>{can(user,"TASK_UPDATE")?<form action={setTaskStatus.bind(null,t.id)} className="flex gap-1"><Select name="status" defaultValue={t.status} className="w-36">{STEP_STATUSES.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</Select><Button variant="outline">Save</Button></form>:null}</div></div></li>})}</ul>:<p className="p-5 text-sm text-muted2">No task yet.</p>}</CardContent></Card>
   </div>

   <div className="space-y-5">
    <Card><CardHeader><CardTitle>Operational health</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Health ok={facts.progress===100} label="Progress" detail={`${facts.progress}% complete`}/><Health ok={facts.overdueTasks.length===0&&facts.overdueMilestones.length===0} label="Deadlines" detail={overdue?`${overdue} overdue item(s)`:"No overdue work"}/><Health ok={blocked===0} label="Blockers" detail={blocked?`${blocked} milestone(s) blocked`:"No active blocker"}/><Health ok={Boolean(c.owner)} label="Ownership" detail={c.owner?`${c.owner.firstName} ${c.owner.lastName}`:"Case has no owner"}/></CardContent></Card>

    <Card><CardHeader><CardTitle>Recent operations activity</CardTitle></CardHeader><CardContent className="p-0">{c.activities.length?<ul className="divide-y divide-line">{c.activities.map(a=><li key={a.id} className="px-4 py-3"><p className="text-sm">{a.message}</p><p className="mt-1 text-xs text-muted2">{a.user?`${a.user.firstName} ${a.user.lastName} · `:""}{formatDateTime(a.createdAt)}</p></li>)}</ul>:<p className="p-4 text-sm text-muted2">No activity yet.</p>}</CardContent></Card>
   </div>
  </div>
 </div>;
}
function Metric({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub:string}){return <Card><CardContent className="p-4"><Icon className="h-4 w-4 text-electric"/><p className="mt-3 text-xs text-muted2">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p><p className="mt-1 text-xs text-muted2">{sub}</p></CardContent></Card>}
function Health({ok,label,detail}:{ok:boolean;label:string;detail:string}){return <div className="flex items-start gap-2 rounded-lg border border-line p-3">{ok?<CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-600"/>:<AlertTriangle className="mt-0.5 h-4 w-4 text-amber-600"/>}<div><p className="font-medium">{label}</p><p className="text-xs text-muted2">{detail}</p></div></div>}
