import "server-only";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import type { ManualTransferOrder, ManualTransferReceiver } from "@/lib/finance-manual-transfers";

const PAGE={w:595.28,h:841.89,m:46};
const INK=rgb(.055,.09,.16),MUTED=rgb(.42,.46,.54),LINE=rgb(.86,.88,.92),SOFT=rgb(.965,.97,.98),BLUE=rgb(.10,.42,.92);
type Ctx={pdf:PDFDocument;page:PDFPage;font:PDFFont;bold:PDFFont;y:number;pageNo:number;reference:string;company:string;website:string};

function safe(v:unknown){return String(v??"").replace(/[–—]/g,"-").replace(/\s+/g," ").trim()}
function money(v:number,currency:string){try{return new Intl.NumberFormat("en-US",{style:"currency",currency,minimumFractionDigits:2}).format(v)}catch{return `${currency} ${Number(v).toFixed(2)}`}}
function wrap(value:string,font:PDFFont,size:number,width:number){const out:string[]=[];for(const raw of String(value||"").split("\n")){const words=raw.trim().split(/\s+/).filter(Boolean);if(!words.length){out.push("");continue}let line="";for(const word of words){const probe=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(probe,size)<=width)line=probe;else{if(line)out.push(line);let part=word;while(font.widthOfTextAtSize(part,size)>width&&part.length>2){let cut=part.length-1;while(cut>1&&font.widthOfTextAtSize(part.slice(0,cut),size)>width)cut--;out.push(part.slice(0,cut));part=part.slice(cut)}line=part}}if(line)out.push(line)}return out.length?out:[""]}
async function company(){const rows=await prisma.appSetting.findMany({where:{key:{in:["company.name","company.website","company.mailing_address","company.address","company.phone","company.finance_email","company.email"]}},select:{key:true,value:true}}).catch(()=>[]);const s=Object.fromEntries(rows.map(r=>[r.key,r.value]));return{name:s["company.name"]||"JUN CREATIF AND TRAVEL LLC",website:(s["company.website"]||"www.juncreatif.org").replace(/^https?:\/\//,""),address:s["company.mailing_address"]||s["company.address"]||"",phone:s["company.phone"]||"",email:s["company.finance_email"]||s["company.email"]||""}}
function footer(c:Ctx){c.page.drawLine({start:{x:PAGE.m,y:35},end:{x:PAGE.w-PAGE.m,y:35},thickness:.5,color:LINE});c.page.drawText(`${c.company} · ${c.website}`,{x:PAGE.m,y:22,size:7.2,font:c.font,color:MUTED});const p=`${c.reference} · Page ${c.pageNo}`;c.page.drawText(p,{x:PAGE.w-PAGE.m-c.font.widthOfTextAtSize(p,7.2),y:22,size:7.2,font:c.font,color:MUTED})}
function addPage(c:Ctx){if(c.pageNo)footer(c);c.page=c.pdf.addPage([PAGE.w,PAGE.h]);c.pageNo++;c.y=PAGE.h-PAGE.m;c.page.drawText(c.company,{x:PAGE.m,y:c.y,size:9,font:c.bold,color:INK});c.page.drawText(c.website,{x:PAGE.w-PAGE.m-c.font.widthOfTextAtSize(c.website,8),y:c.y,size:8,font:c.font,color:MUTED});c.y-=18;c.page.drawLine({start:{x:PAGE.m,y:c.y},end:{x:PAGE.w-PAGE.m,y:c.y},thickness:1.2,color:INK});c.y-=22}
function need(c:Ctx,h:number){if(c.y-h<52)addPage(c)}
function section(c:Ctx,title:string){need(c,34);c.y-=2;c.page.drawText(safe(title),{x:PAGE.m,y:c.y,size:13,font:c.bold,color:INK});c.y-=10;c.page.drawLine({start:{x:PAGE.m,y:c.y},end:{x:PAGE.w-PAGE.m,y:c.y},thickness:.6,color:LINE});c.y-=17}
function field(c:Ctx,label:string,value:string,x:number,y:number,width:number){c.page.drawText(label.toUpperCase(),{x,y,size:6.6,font:c.bold,color:MUTED});const lines=wrap(value||"-",c.font,8.8,width);lines.slice(0,3).forEach((line,i)=>c.page.drawText(line,{x,y:y-13-i*11,size:8.8,font:c.font,color:INK}))}
function paragraph(c:Ctx,value:string,size=8.6){const lines=wrap(value,c.font,size,PAGE.w-PAGE.m*2);need(c,lines.length*11+8);for(const line of lines){if(line)c.page.drawText(line,{x:PAGE.m,y:c.y,size,font:c.font,color:INK});c.y-=11}c.y-=4}
function receiverName(r:ManualTransferReceiver){return [r.firstName,r.lastName].filter(Boolean).join(" ")||r.legalName||"-"}

export async function renderManualTransferOrderPdf(order:ManualTransferOrder){
 const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const co=await company();const c={pdf,page:null as unknown as PDFPage,font,bold,y:0,pageNo:0,reference:order.orderNumber,company:co.name,website:co.website};addPage(c);
 c.page.drawText("Manual Payment Order",{x:PAGE.m,y:c.y,size:22,font:bold,color:INK});const status=order.status.replaceAll("_"," ");c.page.drawText(status,{x:PAGE.w-PAGE.m-bold.widthOfTextAtSize(status,9),y:c.y+3,size:9,font:bold,color:BLUE});c.y-=28;c.page.drawText(order.orderNumber,{x:PAGE.m,y:c.y,size:8.5,font,color:MUTED});c.y-=15;c.page.drawText(`${order.receiverSnapshot.rail.replaceAll("_"," ")} · ${order.originCountry} → ${order.destinationCountry} · ${order.language}`,{x:PAGE.m,y:c.y,size:9,font,color:INK});c.y-=26;
 const boxW=(PAGE.w-PAGE.m*2-18)/4;const metrics=[["Amount to send",money(order.sendAmount,order.sendCurrency)],["Fees deducted",money(order.feeAmount,order.sendCurrency)],["Net after fees",money(order.netAfterFees,order.sendCurrency)],["Estimated received",money(order.receiveAmount,order.receiveCurrency)]];need(c,72);metrics.forEach(([label,value],i)=>{const x=PAGE.m+i*(boxW+6);c.page.drawRectangle({x,y:c.y-54,width:boxW,height:60,color:SOFT,borderColor:LINE,borderWidth:.5});c.page.drawText(label,{x:x+8,y:c.y-12,size:6.5,font:bold,color:MUTED});const lines=wrap(value,font,10.5,boxW-16);lines.slice(0,2).forEach((line,j)=>c.page.drawText(line,{x:x+8,y:c.y-31-j*12,size:10.5,font:j===0?bold:font,color:INK}))});c.y-=78;
 section(c,"Transfer details");need(c,100);field(c,"Payer / partner",order.payerName||"-",PAGE.m,c.y,220);field(c,"Purpose",order.purpose||"Commercial payment",320,c.y,220);c.y-=48;field(c,"Origin country",order.originCountry,PAGE.m,c.y,130);field(c,"Destination country",order.destinationCountry,190,c.y,130);field(c,"Exchange rate",String(order.exchangeRate),340,c.y,100);field(c,"Receiving currency",order.receiveCurrency,465,c.y,80);c.y-=55;
 const r=order.receiverSnapshot;section(c,"Receiver / Beneficiary");need(c,138);field(c,"Receiver name",receiverName(r),PAGE.m,c.y,220);field(c,"Legal / business name",r.legalName||receiverName(r),320,c.y,220);c.y-=48;field(c,"Phone",r.phone||"-",PAGE.m,c.y,150);field(c,"Email",r.email||"-",220,c.y,170);field(c,"Country",r.country||"-",420,c.y,120);c.y-=48;field(c,"City",r.city||"-",PAGE.m,c.y,140);field(c,"Full address",r.address||"-",220,c.y,320);c.y-=55;
 if(r.rail==="BANK_TRANSFER"||r.bankName||r.accountNumber||r.iban||r.swiftBic||r.routingNumber||r.clabe){section(c,"Bank information");need(c,196);field(c,"Bank name",r.bankName||"-",PAGE.m,c.y,220);field(c,"Bank country",r.bankCountry||"-",320,c.y,220);c.y-=48;field(c,"Bank address",r.bankAddress||"-",PAGE.m,c.y,494);c.y-=48;field(c,"Account holder",r.accountHolderName||receiverName(r),PAGE.m,c.y,220);field(c,"Account number",r.accountNumber||"-",320,c.y,220);c.y-=48;field(c,"IBAN",r.iban||"-",PAGE.m,c.y,220);field(c,"SWIFT / BIC",r.swiftBic||"-",320,c.y,220);c.y-=48;field(c,"Routing / ABA",r.routingNumber||"-",PAGE.m,c.y,145);field(c,"CLABE",r.clabe||"-",220,c.y,145);field(c,"Branch code",r.branchCode||"-",395,c.y,145);c.y-=55}
 if(r.complianceNote){section(c,"Compliance / special instructions");paragraph(c,r.complianceNote,8.2)}section(c,"Instructions to sender");paragraph(c,order.instructions||"No additional instructions.",8.7);need(c,66);c.page.drawRectangle({x:PAGE.m,y:c.y-44,width:PAGE.w-PAGE.m*2,height:50,borderColor:LINE,borderWidth:.6});c.page.drawText("IMPORTANT",{x:PAGE.m+10,y:c.y-10,size:7,font:bold,color:MUTED});const warning="Verify the beneficiary and bank details before sending funds. Use only the stated business purpose and keep the provider or bank transaction receipt for reconciliation.";wrap(warning,font,7.6,PAGE.w-PAGE.m*2-20).slice(0,3).forEach((line,i)=>c.page.drawText(line,{x:PAGE.m+10,y:c.y-23-i*10,size:7.6,font,color:INK}));footer(c);pdf.setTitle(`${order.orderNumber} - Manual Payment Order`);pdf.setAuthor(co.name);pdf.setCreator("JUN Business Hub Finance PDF Engine");return pdf.save();
}
