import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getFinancialAuthorizationPolicy, listFinancialAuthorizations } from "@/lib/company-funds-approvals";
import { formatDateTime, formatMoney } from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShieldCheck, CheckCircle2, XCircle, Clock3, AlertTriangle } from "lucide-react";
import { approveFinancialAuthorizationAction, rejectFinancialAuthorizationAction, updateFinancialAuthorizationPolicyAction } from "@/services/company-funds-approvals";

export const dynamic="force-dynamic";
export default async function FinancialAuthorizationsPage(){
 const user=await requireUser();if(user.role!=="SUPER_ADMIN")redirect("/app/forbidden");
 const [items,policy]=await Promise.all([listFinancialAuthorizations(),getFinancialAuthorizationPolicy()]);
 const pending=items.filter(a=>a.status==="PENDING"),approved=items.filter(a=>a.status==="APPROVED"),rejected=items.filter(a=>a.status==="REJECTED");
 return <div className="space-y-5">
  <div><p className="text-xs uppercase tracking-[0.18em] text-muted2">Super Admin · Gouvernance financière</p><h1 className="mt-1 text-3xl font-semibold">Autorisations financières</h1><p className="mt-1 max-w-4xl text-sm text-muted2">Contrôle des grosses sorties, double approbation, séparation demandeur/approbateur et protection des réserves avant exécution.</p></div>
  <div className="grid gap-3 md:grid-cols-4"><Metric icon={Clock3} label="En attente" value={String(pending.length)} hint="Décisions requises"/><Metric icon={CheckCircle2} label="Approuvées" value={String(approved.length)} hint="Autorisées à exécuter"/><Metric icon={XCircle} label="Rejetées" value={String(rejected.length)} hint="Bloquées"/><Metric icon={AlertTriangle} label="Impact réserves" value={String(items.filter(a=>a.reserveImpact&&a.status==="PENDING").length)} hint="Sorties utilisant du cash protégé"/></div>
  <Card><CardHeader><CardTitle>Politique d&apos;autorisation</CardTitle></CardHeader><CardContent><form action={updateFinancialAuthorizationPolicyAction} className="grid gap-3 md:grid-cols-4"><label className="text-xs">Seuil approbation simple<input name="singleApprovalThreshold" type="number" step="0.01" defaultValue={policy.singleApprovalThreshold} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><label className="text-xs">Seuil double approbation<input name="dualApprovalThreshold" type="number" step="0.01" defaultValue={policy.dualApprovalThreshold} className="mt-1 w-full rounded-lg border border-line px-3 py-2"/></label><label className="flex items-center gap-2 self-end rounded-lg border border-line px-3 py-2 text-xs"><input name="reserveOverrideAlwaysDual" type="checkbox" defaultChecked={policy.reserveOverrideAlwaysDual}/>Double approbation si réserve protégée touchée</label><button className="self-end rounded-lg bg-ink px-3 py-2 text-sm font-medium text-white">Enregistrer la politique</button></form><p className="mt-3 text-[11px] text-muted2">Les montants sont évalués dans la devise native de l&apos;opération, sans conversion implicite entre devises.</p></CardContent></Card>
  <Card><CardHeader><CardTitle>Demandes et décisions</CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead><tr className="border-b text-left text-xs text-muted2"><th className="p-2">Référence</th><th className="p-2">Type</th><th className="p-2 text-right">Montant</th><th className="p-2">Motif</th><th className="p-2">Approbations</th><th className="p-2">Statut</th><th className="p-2">Action</th></tr></thead><tbody>{items.map(a=>{const yes=a.decisions.filter(d=>d.decision==="APPROVE").length;return <tr key={a.id} className="border-b border-line/70 align-top"><td className="p-2 font-medium">{a.reference}<div className="text-[10px] text-muted2">{formatDateTime(a.createdAt)}</div></td><td className="p-2"><span className="rounded bg-surface px-2 py-1 text-[10px] font-semibold">{a.type}</span>{a.reserveImpact?<div className="mt-1 text-[10px] font-semibold text-red-700">IMPACT RÉSERVE</div>:null}</td><td className="p-2 text-right font-semibold">{formatMoney(a.amount,a.currency)}</td><td className="p-2 text-xs"><div>{a.description}</div><div className="mt-1 text-muted2">{a.reason}</div></td><td className="p-2"><div className="font-semibold">{yes}/{a.requiredApprovals}</div><div className="mt-1 text-[10px] text-muted2">{a.decisions.map(d=>`${d.decision} · ${formatDateTime(d.decidedAt)}`).join(" · ")||"Aucune décision"}</div></td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${a.status==="APPROVED"?"bg-emerald-50 text-emerald-700":a.status==="REJECTED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{a.status}</span></td><td className="p-2">{a.status==="PENDING"?<div className="space-y-1"><form action={approveFinancialAuthorizationAction.bind(null,a.id)} className="flex gap-1"><input name="note" placeholder="Note" className="w-32 rounded border border-line px-2 py-1 text-xs"/><button className="rounded bg-emerald-700 px-2 py-1 text-xs text-white">Approuver</button></form><form action={rejectFinancialAuthorizationAction.bind(null,a.id)} className="flex gap-1"><input name="note" placeholder="Motif rejet" className="w-32 rounded border border-line px-2 py-1 text-xs"/><button className="rounded bg-red-700 px-2 py-1 text-xs text-white">Rejeter</button></form></div>:<span className="text-xs text-muted2">Décision finale</span>}</td></tr>})}</tbody></table></div>{!items.length?<p className="py-5 text-center text-sm text-muted2">Aucune demande d&apos;autorisation.</p>:null}</CardContent></Card>
 </div>
}
function Metric({icon:Icon,label,value,hint}:{icon:typeof ShieldCheck;label:string;value:string;hint:string}){return <div className="rounded-xl border border-line bg-white p-4"><Icon className="mb-2 h-5 w-5 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted2">{hint}</div></div>}
