import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { EXPENSE_CATEGORIES, getFinanceExpense } from "@/lib/finance-expenses";
import { expenseEditMode, editPolicyMessage } from "@/lib/edit-policy";
import { correctExpense } from "@/services/finance-corrections";
import { PageHeader } from "@/components/app/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
export const dynamic="force-dynamic";
export default async function EditExpensePage({params}:{params:{id:string}}){
 await requirePermission("EXPENSE_READ");const [e,clients,cases]=await Promise.all([getFinanceExpense(params.id),prisma.client.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{lastName:"asc"},select:{id:true,firstName:true,lastName:true,internalId:true}}),prisma.case.findMany({where:{status:{not:"ARCHIVED"}},orderBy:{createdAt:"desc"},take:500,select:{id:true,caseNumber:true,title:true}})]);if(!e)notFound();const mode=expenseEditMode(e.status,e.payments.length);
 return <div><PageHeader title={`Correct ${e.expenseNumber}`} subtitle={editPolicyMessage(mode)}><Link href={`/app/finance/expenses/${e.id}`}><Button variant="outline">Cancel</Button></Link></PageHeader><Card><CardContent className="p-5">{mode==="LOCKED"?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">This expense is financially locked because payment has already started or the record is final. Use an adjusting/corrective expense instead.</div>:<form action={correctExpense.bind(null,e.id)} className="grid max-w-4xl gap-5 sm:grid-cols-2"><Field label="Vendor name"><Input name="vendorName" defaultValue={e.vendorName} required/></Field><Field label="Vendor country"><Input name="vendorCountry" defaultValue={e.vendorCountry}/></Field><Field label="Category"><Select name="category" defaultValue={e.category}>{EXPENSE_CATEGORIES.map(c=><option key={c} value={c}>{c.replaceAll("_"," ")}</option>)}</Select></Field><Field label="Vendor invoice #"><Input name="invoiceNumber" defaultValue={e.invoiceNumber}/></Field><Field label="Amount"><Input name="amount" type="number" step="0.01" min="0.01" defaultValue={e.amount} required/></Field><Field label="Currency"><Input name="currency" defaultValue={e.currency} maxLength={3} required/></Field><Field label="Due date"><Input name="dueDate" type="date" defaultValue={e.dueDate?e.dueDate.slice(0,10):""}/></Field><Field label="Client"><Select name="clientId" defaultValue={e.clientId||""}><option value="">No client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.lastName}, {c.firstName} — {c.internalId}</option>)}</Select></Field><div className="sm:col-span-2"><Field label="Case"><Select name="caseId" defaultValue={e.caseId||""}><option value="">No case</option>{cases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} — {c.title}</option>)}</Select></Field></div><div className="sm:col-span-2"><Field label="Description"><Textarea name="description" rows={4} defaultValue={e.description} required/></Field></div>{e.status==="APPROVED"?<div className="sm:col-span-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">Correcting an approved unpaid expense returns it to <strong>SUBMITTED</strong> so it must be approved again.</div>:null}<div className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4"><Field label="Correction reason" hint="Required and permanently audited."><Textarea name="correctionReason" rows={3} required/></Field></div><div className="sm:col-span-2"><Button variant="primary" type="submit">Save correction</Button></div></form>}</CardContent></Card></div>
}
