import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getClientFinanceOverview } from "@/lib/client-finance-overview";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge, Badge } from "@/components/ui/badge";
import { Table, THead, TH, TR, TD } from "@/components/ui/table";
import { formatDate, formatMoney } from "@/lib/utils";
import { AlertTriangle, Banknote, CircleDollarSign, FileText, ReceiptText, WalletCards } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ClientFinancePage({params}:{params:Promise<{id:string}>|{id:string}}){
  await requirePermission("CLIENT_READ");
  const {id}=await Promise.resolve(params);
  const [client,finance]=await Promise.all([
    prisma.client.findUnique({where:{id},select:{id:true,internalId:true,firstName:true,lastName:true,status:true}}),
    getClientFinanceOverview(id),
  ]);
  if(!client) notFound();

  const alertCount=finance.alerts.overallocatedPayments.length+finance.alerts.overdueInvoices.length+finance.alerts.pendingPayments.length+finance.alerts.pendingRefunds.length+finance.alerts.pendingExpenses.length;

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="registry-id text-muted2">{client.internalId}</p><div className="mt-1 flex items-center gap-2"><h1 className="text-2xl font-semibold">{client.firstName} {client.lastName} · Finance</h1><StatusBadge status={client.status}/></div><p className="mt-1 text-sm text-muted2">Invoices, payments, transfer fees, expenses, net receipts, profitability, balances and refunds.</p></div>
      <div className="flex flex-wrap gap-2"><Link href={`/app/clients/${id}/dashboard`}><Button variant="outline">Client 360</Button></Link><Link href={`/app/clients/${id}/services`}><Button variant="outline">Services & Cases</Button></Link><Link href={`/app/clients/${id}/profitability`}><Button variant="outline">Profitability</Button></Link><Link href={`/app/clients/${id}/statement`}><Button variant="outline">Statement</Button></Link><Link href={`/app/finance/expenses/new?clientId=${id}`}><Button variant="outline">New expense</Button></Link><Link href={`/app/finance/invoices/new?clientId=${id}`}><Button variant="primary">New invoice</Button></Link></div>
    </div>

    {finance.summaries.length===0?<Card><CardContent className="p-5 text-sm text-muted2">No financial activity recorded for this client yet.</CardContent></Card>:<div className="space-y-4">{finance.summaries.map((s)=><Card key={s.currency}><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle>{s.currency} financial position</CardTitle><Badge className="border border-line bg-surface text-muted2">NET BASIS</Badge></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
      <Metric icon={CircleDollarSign} label="Gross sent" value={formatMoney(s.grossReceived,s.currency)}/>
      <Metric icon={Banknote} label="Transfer fees" value={`-${formatMoney(s.fees,s.currency)}`}/>
      <Metric icon={WalletCards} label="Net received" value={formatMoney(s.netReceived,s.currency)}/>
      <Metric icon={ReceiptText} label="Expenses paid" value={`-${formatMoney(s.expensePaid,s.currency)}`}/>
      <Metric icon={ReceiptText} label="Committed costs" value={formatMoney(s.expenseCommitted,s.currency)}/>
      <Metric icon={CircleDollarSign} label="Realized profit" value={formatMoney(s.realizedProfit,s.currency)}/>
      <Metric icon={CircleDollarSign} label="Forecast profit" value={formatMoney(s.forecastProfit,s.currency)}/>
      <Metric icon={AlertTriangle} label="Receivable" value={formatMoney(s.receivable,s.currency)}/>
    </div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-1 border-t border-line pt-3 text-xs text-muted2"><span>Billed: <strong className="text-ink">{formatMoney(s.billed,s.currency)}</strong></span><span>Invoice paid: <strong className="text-ink">{formatMoney(s.invoicePaid,s.currency)}</strong></span><span>Applied: <strong className="text-ink">{formatMoney(s.appliedToInvoices,s.currency)}</strong></span><span>Unapplied: <strong className="text-ink">{formatMoney(s.unappliedFunds,s.currency)}</strong></span><span>Pending expense approval: <strong className="text-ink">{formatMoney(s.expensePendingApproval,s.currency)}</strong></span><span>Approved cost remaining: <strong className="text-ink">{formatMoney(s.expenseRemaining,s.currency)}</strong></span><span>Approved refunds: <strong className="text-ink">{formatMoney(s.approvedRefunds,s.currency)}</strong></span><span>Refunds paid: <strong className="text-ink">{formatMoney(s.refundPaid,s.currency)}</strong></span><span>Realized margin: <strong className="text-ink">{s.realizedMarginPercent==null?"—":`${s.realizedMarginPercent.toFixed(2)}%`}</strong></span><span>Forecast margin: <strong className="text-ink">{s.forecastMarginPercent==null?"—":`${s.forecastMarginPercent.toFixed(2)}%`}</strong></span></div></CardContent></Card>)}</div>}

    {alertCount>0?<Card><CardHeader><CardTitle>Finance attention</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
      <AlertBox title="Overallocated payments" count={finance.alerts.overallocatedPayments.length} text="Invoice allocations exceed the net payment available."/>
      <AlertBox title="Overdue invoices" count={finance.alerts.overdueInvoices.length} text="Invoices still have an overdue balance."/>
      <AlertBox title="Pending payments" count={finance.alerts.pendingPayments.length} text="Payments still require confirmation."/>
      <AlertBox title="Pending expenses" count={finance.alerts.pendingExpenses.length} text="Client expenses are draft or awaiting approval."/>
      <AlertBox title="Pending refunds" count={finance.alerts.pendingRefunds.length} text="Refund requests are awaiting a decision."/>
    </CardContent></Card>:null}

    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Invoices</CardTitle><Link href={`/app/finance/invoices/new?clientId=${id}`} className="text-sm font-medium text-electric hover:underline">Create invoice</Link></div></CardHeader><CardContent className="p-0">{finance.invoices.length===0?<p className="p-5 text-sm text-muted2">No invoices for this client.</p>:<div className="overflow-x-auto"><Table><THead><tr><TH>Invoice</TH><TH>Service</TH><TH>Total</TH><TH>Paid</TH><TH>Balance</TH><TH>Status</TH><TH>Due</TH></tr></THead><tbody>{finance.invoices.map(({invoice,state})=><TR key={invoice.id}><TD><Link className="registry-id hover:text-electric" href={`/app/finance/invoices/${invoice.id}`}>{invoice.invoiceNumber}</Link></TD><TD><div className="font-medium">{invoice.title}</div>{invoice.caseId?<Link href={`/app/cases/${invoice.caseId}`} className="text-xs text-electric hover:underline">Open case</Link>:<div className="text-xs text-muted2">No case linked</div>}</TD><TD className="font-medium">{formatMoney(invoice.total,invoice.currency)}</TD><TD className="text-emerald-700">{formatMoney(state.paid,invoice.currency)}</TD><TD className={state.balance>0?"font-medium text-amber-700":"font-medium text-emerald-700"}>{formatMoney(state.balance,invoice.currency)}</TD><TD><StatusBadge status={state.effectiveStatus}/></TD><TD className="text-muted2">{formatDate(new Date(invoice.dueDate))}</TD></TR>)}</tbody></Table></div>}</CardContent></Card>

    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Payments</CardTitle><Link href={`/app/finance/payments/new?clientId=${id}`} className="text-sm font-medium text-electric hover:underline">Record payment</Link></div></CardHeader><CardContent className="p-0">{finance.payments.length===0?<p className="p-5 text-sm text-muted2">No payments recorded.</p>:<div className="overflow-x-auto"><Table><THead><tr><TH>Reference</TH><TH>Gross</TH><TH>Fees</TH><TH>Net received</TH><TH>Applied</TH><TH>Unapplied</TH><TH>Status</TH><TH>Date</TH></tr></THead><tbody>{finance.payments.map((p)=><TR key={p.id}><TD><Link className="registry-id hover:text-electric" href={`/app/finance/payments/${p.id}`}>{p.reference}</Link><div className="mt-1 text-xs text-muted2">{p.serviceLabel||p.method.replaceAll("_"," ")}</div></TD><TD>{formatMoney(p.gross,p.currency)}</TD><TD className={p.fee>0?"text-red-700":"text-muted2"}>{p.fee>0?`-${formatMoney(p.fee,p.currency)}`:"—"}</TD><TD className="font-semibold">{formatMoney(p.net,p.currency)}</TD><TD>{formatMoney(p.applied,p.currency)}</TD><TD className={p.unapplied>0?"font-medium text-blue-700":"text-muted2"}>{formatMoney(p.unapplied,p.currency)}{p.overallocated>0?<div className="mt-1 text-xs text-red-700">Overallocated by {formatMoney(p.overallocated,p.currency)}</div>:null}</TD><TD><StatusBadge status={p.status}/></TD><TD className="text-muted2">{formatDate(p.paidAt||p.createdAt)}</TD></TR>)}</tbody></Table></div>}</CardContent></Card>

    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Expenses</CardTitle><Link href={`/app/finance/expenses/new?clientId=${id}`} className="text-sm font-medium text-electric hover:underline">Record client expense</Link></div></CardHeader><CardContent className="p-0">{finance.expenses.length===0?<p className="p-5 text-sm text-muted2">No expense linked to this client.</p>:<div className="overflow-x-auto"><Table><THead><tr><TH>Expense</TH><TH>Vendor / service</TH><TH>Amount</TH><TH>Paid</TH><TH>Remaining</TH><TH>Status</TH><TH>Case</TH><TH>Updated</TH></tr></THead><tbody>{finance.expenses.map((e)=><TR key={e.id}><TD><Link className="registry-id hover:text-electric" href={`/app/finance/expenses/${e.id}`}>{e.expenseNumber}</Link><div className="mt-1 text-xs text-muted2">{e.category.replaceAll("_"," ")}</div></TD><TD><div className="font-medium">{e.vendorName}</div><div className="max-w-xs truncate text-xs text-muted2">{e.description}</div></TD><TD className="font-medium">{formatMoney(e.amount,e.currency)}</TD><TD className={e.paidNumber>0?"text-red-700":"text-muted2"}>{formatMoney(e.paidNumber,e.currency)}</TD><TD>{formatMoney(e.remainingNumber,e.currency)}</TD><TD><StatusBadge status={e.effectiveStatus}/></TD><TD>{e.caseId?<Link href={`/app/cases/${e.caseId}`} className="text-electric hover:underline">{e.caseLabel||"Open case"}</Link>:<span className="text-amber-700">No case linked</span>}</TD><TD className="text-muted2">{formatDate(new Date(e.updatedAt))}</TD></TR>)}</tbody></Table></div>}</CardContent></Card>

    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Refunds</CardTitle><Link href={`/app/finance/refunds/new?clientId=${id}`} className="text-sm font-medium text-electric hover:underline">New refund</Link></div></CardHeader><CardContent className="p-0">{finance.refunds.length===0?<p className="p-5 text-sm text-muted2">No refunds for this client.</p>:<div className="overflow-x-auto"><Table><THead><tr><TH>Reference</TH><TH>Requested</TH><TH>Paid</TH><TH>Remaining</TH><TH>Status</TH><TH>Reason</TH><TH>Created</TH></tr></THead><tbody>{finance.refunds.map((r)=><TR key={r.id}><TD><Link className="registry-id hover:text-electric" href={`/app/finance/refunds/${r.id}`}>{r.refundNumber}</Link></TD><TD>{formatMoney(r.amountNumber,r.currency)}</TD><TD className="text-red-700">{formatMoney(r.paidNumber,r.currency)}</TD><TD className="font-medium">{formatMoney(r.remainingNumber,r.currency)}</TD><TD><StatusBadge status={r.status}/></TD><TD className="max-w-xs truncate text-muted2">{r.reason}</TD><TD className="text-muted2">{formatDate(r.createdAt)}</TD></TR>)}</tbody></Table></div>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Finance rules used on this client</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm md:grid-cols-2"><Rule title="Net received" text="Gross payment minus transfer fees. This is the money JUN actually received."/><Rule title="Expenses" text="Every expense linked to the client appears here. Draft/submitted expenses are visible but do not become committed cost until approved."/><Rule title="Realized profit" text="Net received minus refunds actually paid and expenses actually paid by JUN."/><Rule title="Forecast profit" text="Net received minus approved refunds and approved/committed expenses."/></CardContent></Card>
  </div>;
}

function Metric({icon:Icon,label,value}:{icon:typeof CircleDollarSign;label:string;value:string}){return <div className="rounded-xl border border-line bg-surface/40 p-3"><Icon className="mb-2 h-4 w-4 text-electric"/><div className="text-xs text-muted2">{label}</div><div className="mt-1 break-words font-semibold">{value}</div></div>}
function AlertBox({title,count,text}:{title:string;count:number;text:string}){return <div className={count?"rounded-xl border border-amber-200 bg-amber-50 p-4":"rounded-xl border border-line bg-surface/40 p-4"}><div className="flex items-center justify-between gap-2"><div className="font-medium">{title}</div><Badge className={count?"border border-amber-200 bg-white text-amber-800":"border border-line bg-white text-muted2"}>{count}</Badge></div><div className="mt-1 text-xs text-muted2">{text}</div></div>}
function Rule({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-line p-4"><div className="font-medium">{title}</div><div className="mt-1 text-xs text-muted2">{text}</div></div>}
